# FMKMF_F90 not set: using f90
# FMKMF_SFTAG not set: using f90
# FMKMF_SPATH not set: using . 
# FMKMF_LINKOPTS not set: using no link options 
# Using search path .:DO3SE/src from cmd line
# Using source file tag (f90|F90) from cmd line
# Main program is esx_tester.f90 
# process_fsource called with arg esx_tester.f90 
# esx_tester.f90 Uses Module AllocInits
# esx_tester.f90 Uses Module Ammonium_ml
# esx_tester.f90 Uses Module ChemSpecs
# esx_tester.f90 Uses Module CheckStops
# esx_tester.f90 Uses Module esx_gleaf
# esx_tester.f90 Uses Module esx_GetData
# esx_tester.f90 Uses Module esx_ChemRun
# esx_tester.f90 Uses Module esx_MassBudget
# esx_tester.f90 Uses Module esx_Variables
# esx_tester.f90 Uses Module esx_Zchem
# esx_tester.f90 Uses Module esx_ZdiffSolver
# esx_tester.f90 Uses Module esx_Zgrid
# esx_tester.f90 Uses Module esx_Zmet
# esx_tester.f90 Uses Module esx_Zveg
# esx_tester.f90 Uses Module Io_ml
# esx_tester.f90 Uses Module Io_Progs
# esx_tester.f90 Uses Module Io_Routines
# esx_tester.f90 Uses Module ZchemData
# esx_tester.f90 Uses Module Zmet_ml
# esx_tester.f90 Uses Module Zmet_ml
# esx_tester.f90 Uses Module SmallUtils_ml
# esx_tester.f90 Uses Module TimeDate_ml
# Full list of modules in esx_tester.f90: AllocInits Ammonium_ml ChemSpecs CheckStops esx_gleaf esx_GetData esx_ChemRun esx_MassBudget esx_Variables esx_Zchem esx_ZdiffSolver esx_Zgrid esx_Zmet esx_Zveg Io_ml Io_Progs Io_Routines ZchemData Zmet_ml Zmet_ml SmallUtils_ml TimeDate_ml 
# Uses AllocInits which is in ./AllocInit.f90
# process_fsource called with arg ./AllocInit.f90 
# ./AllocInit.f90 Uses Module CheckStops
# Full list of modules in ./AllocInit.f90: CheckStops 
# Uses CheckStops which is in ./CheckStops.f90
# process_fsource called with arg ./CheckStops.f90 
# Full list of modules in ./CheckStops.f90:  
# Uses Ammonium_ml which is in ./Ammonium_ml.f90
# process_fsource called with arg ./Ammonium_ml.f90 
# ./Ammonium_ml.f90 Uses Module ChemSpecs
# ./Ammonium_ml.f90 Uses Module ModelConstants
# ./Ammonium_ml.f90 Uses Module SmallUtils_ml
# ./Ammonium_ml.f90 Uses Module ZchemData
# ./Ammonium_ml.f90 Uses Module Zmet_ml
# Full list of modules in ./Ammonium_ml.f90: ChemSpecs ModelConstants SmallUtils_ml ZchemData Zmet_ml 
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# process_fsource called with arg ./CM_ChemSpecs.f90 
# Full list of modules in ./CM_ChemSpecs.f90:  
# Uses ModelConstants which is in ./ModelConstants.f90
# process_fsource called with arg ./ModelConstants.f90 
# Full list of modules in ./ModelConstants.f90:  
# Uses SmallUtils_ml which is in ./SmallUtils_ml.f90
# process_fsource called with arg ./SmallUtils_ml.f90 
# Full list of modules in ./SmallUtils_ml.f90:  
# Uses ZchemData which is in ./ZchemData.f90
# process_fsource called with arg ./ZchemData.f90 
# ./ZchemData.f90 Uses Module AllocInits
# ./ZchemData.f90 Uses Module ChemSpecs
# ./ZchemData.f90 Uses Module DefPhotolysis
# Full list of modules in ./ZchemData.f90: AllocInits ChemSpecs DefPhotolysis 
# Uses AllocInits which is in ./AllocInit.f90
# ./AllocInit.f90 already in list
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses DefPhotolysis which is in ./DefPhotolysis.f90
# process_fsource called with arg ./DefPhotolysis.f90 
# Full list of modules in ./DefPhotolysis.f90:  
# Uses Zmet_ml which is in ./Zmet_ml.f90
# process_fsource called with arg ./Zmet_ml.f90 
# ./Zmet_ml.f90 Uses Module AllocInits
# ./Zmet_ml.f90 Uses Module esx_Variables
# ./Zmet_ml.f90 Uses Module Io_Progs
# Full list of modules in ./Zmet_ml.f90: AllocInits esx_Variables Io_Progs 
# Uses AllocInits which is in ./AllocInit.f90
# ./AllocInit.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# process_fsource called with arg ./esx_Variables.f90 
# ./esx_Variables.f90 Uses Module CheckStops
# ./esx_Variables.f90 Uses Module ChemSpecs
# ./esx_Variables.f90 Uses Module KeyValueTypes
# ./esx_Variables.f90 Uses Module LocalVariables
# ./esx_Variables.f90 Uses Module ModelConstants
# ./esx_Variables.f90 Uses Module PhysicalConstants_ml
# ./esx_Variables.f90 Uses Module SmallUtils_ml
# ./esx_Variables.f90 Uses Module TimeDate_ml
# Full list of modules in ./esx_Variables.f90: CheckStops ChemSpecs KeyValueTypes LocalVariables ModelConstants PhysicalConstants_ml SmallUtils_ml TimeDate_ml 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses KeyValueTypes which is in ./KeyValueTypes.f90
# process_fsource called with arg ./KeyValueTypes.f90 
# Full list of modules in ./KeyValueTypes.f90:  
# Uses LocalVariables which is in ./LocalVariables.f90
# process_fsource called with arg ./LocalVariables.f90 
# Full list of modules in ./LocalVariables.f90:  
# Uses ModelConstants which is in ./ModelConstants.f90
# ./ModelConstants.f90 already in list
# Uses PhysicalConstants_ml which is in ./PhysicalConstants_ml.f90
# process_fsource called with arg ./PhysicalConstants_ml.f90 
# Full list of modules in ./PhysicalConstants_ml.f90:  
# Uses SmallUtils_ml which is in ./SmallUtils_ml.f90
# ./SmallUtils_ml.f90 already in list
# Uses TimeDate_ml which is in ./TimeDate_ml.f90
# process_fsource called with arg ./TimeDate_ml.f90 
# Full list of modules in ./TimeDate_ml.f90:  
# Uses Io_Progs which is in ./Io_Progs.f90
# process_fsource called with arg ./Io_Progs.f90 
# ./Io_Progs.f90 Uses Module Io_ml
# Full list of modules in ./Io_Progs.f90: Io_ml 
# Uses Io_ml which is in ./Io_ml.f90
# process_fsource called with arg ./Io_ml.f90 
# Full list of modules in ./Io_ml.f90:  
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses esx_gleaf which is in ./esx_gleaf.f90
# process_fsource called with arg ./esx_gleaf.f90 
# ./esx_gleaf.f90 Uses Module CheckStops
# ./esx_gleaf.f90 Uses Module esx_Variables
# ./esx_gleaf.f90 Uses Module esx_Zveg
# ./esx_gleaf.f90 Uses Module esx_DO3SE
# Full list of modules in ./esx_gleaf.f90: CheckStops esx_Variables esx_Zveg esx_DO3SE 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses esx_Zveg which is in ./esx_Zveg.f90
# process_fsource called with arg ./esx_Zveg.f90 
# ./esx_Zveg.f90 Uses Module CheckStops
# ./esx_Zveg.f90 Uses Module esx_Variables
# ./esx_Zveg.f90 Uses Module Io_Routines
# Full list of modules in ./esx_Zveg.f90: CheckStops esx_Variables Io_Routines 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses Io_Routines which is in ./Io_Routines.f90
# process_fsource called with arg ./Io_Routines.f90 
# ./Io_Routines.f90 Uses Module Io_ml
# Full list of modules in ./Io_Routines.f90: Io_ml 
# Uses Io_ml which is in ./Io_ml.f90
# ./Io_ml.f90 already in list
# Uses esx_DO3SE which is in ./esx_DO3SE.f90
# process_fsource called with arg ./esx_DO3SE.f90 
# ./esx_DO3SE.f90 Uses Module CheckStops
# ./esx_DO3SE.f90 Uses Module DO3SE_GstoTypes_ml
# ./esx_DO3SE.f90 Uses Module DO3SE_Gsto_ml
# ./esx_DO3SE.f90 Uses Module DO3SE_Photosynthesis_ml
# ./esx_DO3SE.f90 Uses Module DO3SE_SMD_ml
# ./esx_DO3SE.f90 Uses Module DO3SE_Util_ml
# ./esx_DO3SE.f90 Uses Module DO3SE_PhysicalConstants_ml
# ./esx_DO3SE.f90 Uses Module esx_Variables
# ./esx_DO3SE.f90 Uses Module esx_Zveg
# Full list of modules in ./esx_DO3SE.f90: CheckStops DO3SE_GstoTypes_ml DO3SE_Gsto_ml DO3SE_Photosynthesis_ml DO3SE_SMD_ml DO3SE_Util_ml DO3SE_PhysicalConstants_ml esx_Variables esx_Zveg 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses DO3SE_GstoTypes_ml which is in DO3SE/src/DO3SE_GstoTypes_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_GstoTypes_ml.F90 
# DO3SE/src/DO3SE_GstoTypes_ml.F90 Uses Module DO3SE_Util_ml
# DO3SE/src/DO3SE_GstoTypes_ml.F90 Uses Module DO3SE_ModelConstants_ml
# Full list of modules in DO3SE/src/DO3SE_GstoTypes_ml.F90: DO3SE_Util_ml DO3SE_ModelConstants_ml 
# Uses DO3SE_Util_ml which is in DO3SE/src/DO3SE_Util_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_Util_ml.F90 
# DO3SE/src/DO3SE_Util_ml.F90 Uses Module iso_fortran_env
# DO3SE/src/DO3SE_Util_ml.F90 Uses Module DO3SE_ModelConstants_ml
# Full list of modules in DO3SE/src/DO3SE_Util_ml.F90: iso_fortran_env DO3SE_ModelConstants_ml 
# Uses DO3SE_ModelConstants_ml which is in DO3SE/src/DO3SE_ModelConstants_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_ModelConstants_ml.F90 
# Full list of modules in DO3SE/src/DO3SE_ModelConstants_ml.F90:  
# Uses DO3SE_ModelConstants_ml which is in DO3SE/src/DO3SE_ModelConstants_ml.F90
# DO3SE/src/DO3SE_ModelConstants_ml.F90 already in list
# Uses DO3SE_Gsto_ml which is in DO3SE/src/DO3SE_Gsto_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_Gsto_ml.F90 
# DO3SE/src/DO3SE_Gsto_ml.F90 Uses Module DO3SE_GstoTypes_ml
# DO3SE/src/DO3SE_Gsto_ml.F90 Uses Module DO3SE_Util_ml
# DO3SE/src/DO3SE_Gsto_ml.F90 Uses Module DO3SE_PhysicalConstants_ml
# Full list of modules in DO3SE/src/DO3SE_Gsto_ml.F90: DO3SE_GstoTypes_ml DO3SE_Util_ml DO3SE_PhysicalConstants_ml 
# Uses DO3SE_GstoTypes_ml which is in DO3SE/src/DO3SE_GstoTypes_ml.F90
# DO3SE/src/DO3SE_GstoTypes_ml.F90 already in list
# Uses DO3SE_Util_ml which is in DO3SE/src/DO3SE_Util_ml.F90
# DO3SE/src/DO3SE_Util_ml.F90 already in list
# Uses DO3SE_PhysicalConstants_ml which is in DO3SE/src/DO3SE_PhysicalConstants_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_PhysicalConstants_ml.F90 
# Full list of modules in DO3SE/src/DO3SE_PhysicalConstants_ml.F90:  
# Uses DO3SE_Photosynthesis_ml which is in DO3SE/src/DO3SE_Photosynthesis_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_Photosynthesis_ml.F90 
# DO3SE/src/DO3SE_Photosynthesis_ml.F90 Uses Module DO3SE_ModelConstants_ml
# DO3SE/src/DO3SE_Photosynthesis_ml.F90 Uses Module DO3SE_GstoTypes_ml
# DO3SE/src/DO3SE_Photosynthesis_ml.F90 Uses Module DO3SE_Util_ml
# Full list of modules in DO3SE/src/DO3SE_Photosynthesis_ml.F90: DO3SE_ModelConstants_ml DO3SE_GstoTypes_ml DO3SE_Util_ml 
# Uses DO3SE_ModelConstants_ml which is in DO3SE/src/DO3SE_ModelConstants_ml.F90
# DO3SE/src/DO3SE_ModelConstants_ml.F90 already in list
# Uses DO3SE_GstoTypes_ml which is in DO3SE/src/DO3SE_GstoTypes_ml.F90
# DO3SE/src/DO3SE_GstoTypes_ml.F90 already in list
# Uses DO3SE_Util_ml which is in DO3SE/src/DO3SE_Util_ml.F90
# DO3SE/src/DO3SE_Util_ml.F90 already in list
# Uses DO3SE_SMD_ml which is in DO3SE/src/DO3SE_SMD_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_SMD_ml.F90 
# DO3SE/src/DO3SE_SMD_ml.F90 Uses Module DO3SE_ModelConstants_ml
# DO3SE/src/DO3SE_SMD_ml.F90 Uses Module DO3SE_Resistance_ml
# DO3SE/src/DO3SE_SMD_ml.F90 Uses Module DO3SE_Util_ml
# Full list of modules in DO3SE/src/DO3SE_SMD_ml.F90: DO3SE_ModelConstants_ml DO3SE_Resistance_ml DO3SE_Util_ml 
# Uses DO3SE_ModelConstants_ml which is in DO3SE/src/DO3SE_ModelConstants_ml.F90
# DO3SE/src/DO3SE_ModelConstants_ml.F90 already in list
# Uses DO3SE_Resistance_ml which is in DO3SE/src/DO3SE_Resistance_ml.F90
# process_fsource called with arg DO3SE/src/DO3SE_Resistance_ml.F90 
# DO3SE/src/DO3SE_Resistance_ml.F90 Uses Module DO3SE_ModelConstants_ml
# Full list of modules in DO3SE/src/DO3SE_Resistance_ml.F90: DO3SE_ModelConstants_ml 
# Uses DO3SE_ModelConstants_ml which is in DO3SE/src/DO3SE_ModelConstants_ml.F90
# DO3SE/src/DO3SE_ModelConstants_ml.F90 already in list
# Uses DO3SE_Util_ml which is in DO3SE/src/DO3SE_Util_ml.F90
# DO3SE/src/DO3SE_Util_ml.F90 already in list
# Uses DO3SE_Util_ml which is in DO3SE/src/DO3SE_Util_ml.F90
# DO3SE/src/DO3SE_Util_ml.F90 already in list
# Uses DO3SE_PhysicalConstants_ml which is in DO3SE/src/DO3SE_PhysicalConstants_ml.F90
# DO3SE/src/DO3SE_PhysicalConstants_ml.F90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses esx_Zveg which is in ./esx_Zveg.f90
# ./esx_Zveg.f90 already in list
# Uses esx_GetData which is in ./esx_GetData.f90
# process_fsource called with arg ./esx_GetData.f90 
# ./esx_GetData.f90 Uses Module CheckStops
# ./esx_GetData.f90 Uses Module esx_Variables
# ./esx_GetData.f90 Uses Module ModelConstants
# ./esx_GetData.f90 Uses Module Radiation_ml
# ./esx_GetData.f90 Uses Module TimeDate_ml
# Full list of modules in ./esx_GetData.f90: CheckStops esx_Variables ModelConstants Radiation_ml TimeDate_ml 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses ModelConstants which is in ./ModelConstants.f90
# ./ModelConstants.f90 already in list
# Uses Radiation_ml which is in ./Radiation_ml.f90
# process_fsource called with arg ./Radiation_ml.f90 
# ./Radiation_ml.f90 Uses Module PhysicalConstants_ml
# ./Radiation_ml.f90 Uses Module TimeDate_ml
# Full list of modules in ./Radiation_ml.f90: PhysicalConstants_ml TimeDate_ml 
# Uses PhysicalConstants_ml which is in ./PhysicalConstants_ml.f90
# ./PhysicalConstants_ml.f90 already in list
# Uses TimeDate_ml which is in ./TimeDate_ml.f90
# ./TimeDate_ml.f90 already in list
# Uses TimeDate_ml which is in ./TimeDate_ml.f90
# ./TimeDate_ml.f90 already in list
# Uses esx_ChemRun which is in ./esx_ChemRun.f90
# process_fsource called with arg ./esx_ChemRun.f90 
# ./esx_ChemRun.f90 Uses Module ChemSpecs
# ./esx_ChemRun.f90 Uses Module ChemRates
# ./esx_ChemRun.f90 Uses Module ChemSolver
# ./esx_ChemRun.f90 Uses Module DefPhotolysis
# ./esx_ChemRun.f90 Uses Module esx_Variables
# ./esx_ChemRun.f90 Uses Module PhysicalConstants_ml
# ./esx_ChemRun.f90 Uses Module ZchemData
# ./esx_ChemRun.f90 Uses Module Zmet_ml
# Full list of modules in ./esx_ChemRun.f90: ChemSpecs ChemRates ChemSolver DefPhotolysis esx_Variables PhysicalConstants_ml ZchemData Zmet_ml 
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses ChemRates which is in ./CM_ChemRates.f90
# process_fsource called with arg ./CM_ChemRates.f90 
# ./CM_ChemRates.f90 Uses Module ChemFunctions
# ./CM_ChemRates.f90 Uses Module Zmet_ml
# ./CM_ChemRates.f90 Uses Module ZchemData
# ./CM_ChemRates.f90 Uses Module ChemSpecs
# ./CM_ChemRates.f90 Uses Module DefPhotolysis
# Full list of modules in ./CM_ChemRates.f90: ChemFunctions Zmet_ml ZchemData ChemSpecs DefPhotolysis 
# Uses ChemFunctions which is in ./ChemFunctions.f90
# process_fsource called with arg ./ChemFunctions.f90 
# ./ChemFunctions.f90 Uses Module PhysicalConstants_ml
# ./ChemFunctions.f90 Uses Module ZchemData
# ./ChemFunctions.f90 Uses Module ZchemData
# ./ChemFunctions.f90 Uses Module Zmet_ml
# ./ChemFunctions.f90 Uses Module ChemSpecs
# Full list of modules in ./ChemFunctions.f90: PhysicalConstants_ml ZchemData ZchemData Zmet_ml ChemSpecs 
# Uses PhysicalConstants_ml which is in ./PhysicalConstants_ml.f90
# ./PhysicalConstants_ml.f90 already in list
# Uses ZchemData which is in ./ZchemData.f90
# ./ZchemData.f90 already in list
# Uses ZchemData which is in ./ZchemData.f90
# ./ZchemData.f90 already in list
# Uses Zmet_ml which is in ./Zmet_ml.f90
# ./Zmet_ml.f90 already in list
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses Zmet_ml which is in ./Zmet_ml.f90
# ./Zmet_ml.f90 already in list
# Uses ZchemData which is in ./ZchemData.f90
# ./ZchemData.f90 already in list
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses DefPhotolysis which is in ./DefPhotolysis.f90
# ./DefPhotolysis.f90 already in list
# Uses ChemSolver which is in ./ChemSolver.f90
# process_fsource called with arg ./ChemSolver.f90 
# ./ChemSolver.f90 Uses Module CheckStops
# ./ChemSolver.f90 Uses Module DefPhotolysis
# ./ChemSolver.f90 Uses Module ChemSpecs
# ./ChemSolver.f90 Uses Module Io_ml
# ./ChemSolver.f90 Uses Module ModelConstants
# ./ChemSolver.f90 Uses Module ZchemData
# Full list of modules in ./ChemSolver.f90: CheckStops DefPhotolysis ChemSpecs Io_ml ModelConstants ZchemData 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses DefPhotolysis which is in ./DefPhotolysis.f90
# ./DefPhotolysis.f90 already in list
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses Io_ml which is in ./Io_ml.f90
# ./Io_ml.f90 already in list
# Uses ModelConstants which is in ./ModelConstants.f90
# ./ModelConstants.f90 already in list
# Uses ZchemData which is in ./ZchemData.f90
# ./ZchemData.f90 already in list
# Uses DefPhotolysis which is in ./DefPhotolysis.f90
# ./DefPhotolysis.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses PhysicalConstants_ml which is in ./PhysicalConstants_ml.f90
# ./PhysicalConstants_ml.f90 already in list
# Uses ZchemData which is in ./ZchemData.f90
# ./ZchemData.f90 already in list
# Uses Zmet_ml which is in ./Zmet_ml.f90
# ./Zmet_ml.f90 already in list
# Uses esx_MassBudget which is in ./esx_MassBudget.f90
# process_fsource called with arg ./esx_MassBudget.f90 
# ./esx_MassBudget.f90 Uses Module ChemSpecs
# ./esx_MassBudget.f90 Uses Module esx_Variables
# Full list of modules in ./esx_MassBudget.f90: ChemSpecs esx_Variables 
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses esx_Zchem which is in ./esx_Zchem.f90
# process_fsource called with arg ./esx_Zchem.f90 
# ./esx_Zchem.f90 Uses Module CheckStops
# ./esx_Zchem.f90 Uses Module ChemSpecs
# ./esx_Zchem.f90 Uses Module ChemRates
# ./esx_Zchem.f90 Uses Module esx_Variables
# ./esx_Zchem.f90 Uses Module SmallUtils_ml
# ./esx_Zchem.f90 Uses Module ZchemData
# Full list of modules in ./esx_Zchem.f90: CheckStops ChemSpecs ChemRates esx_Variables SmallUtils_ml ZchemData 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses ChemSpecs which is in ./CM_ChemSpecs.f90
# ./CM_ChemSpecs.f90 already in list
# Uses ChemRates which is in ./CM_ChemRates.f90
# ./CM_ChemRates.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses SmallUtils_ml which is in ./SmallUtils_ml.f90
# ./SmallUtils_ml.f90 already in list
# Uses ZchemData which is in ./ZchemData.f90
# ./ZchemData.f90 already in list
# Uses esx_ZdiffSolver which is in ./esx_ZdiffSolver.f90
# process_fsource called with arg ./esx_ZdiffSolver.f90 
# ./esx_ZdiffSolver.f90 Uses Module esx_MassBudget
# ./esx_ZdiffSolver.f90 Uses Module esx_Variables
# Full list of modules in ./esx_ZdiffSolver.f90: esx_MassBudget esx_Variables 
# Uses esx_MassBudget which is in ./esx_MassBudget.f90
# ./esx_MassBudget.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses esx_Zgrid which is in ./esx_Zgrid.f90
# process_fsource called with arg ./esx_Zgrid.f90 
# ./esx_Zgrid.f90 Uses Module esx_Variables
# ./esx_Zgrid.f90 Uses Module Io_Progs
# ./esx_Zgrid.f90 Uses Module SmallUtils_ml
# Full list of modules in ./esx_Zgrid.f90: esx_Variables Io_Progs SmallUtils_ml 
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses Io_Progs which is in ./Io_Progs.f90
# ./Io_Progs.f90 already in list
# Uses SmallUtils_ml which is in ./SmallUtils_ml.f90
# ./SmallUtils_ml.f90 already in list
# Uses esx_Zmet which is in ./esx_Zmet.f90
# process_fsource called with arg ./esx_Zmet.f90 
# ./esx_Zmet.f90 Uses Module CheckStops
# ./esx_Zmet.f90 Uses Module Io_Routines
# ./esx_Zmet.f90 Uses Module KeyValueTypes
# ./esx_Zmet.f90 Uses Module esx_Variables
# ./esx_Zmet.f90 Uses Module esx_Zveg
# ./esx_Zmet.f90 Uses Module Kz_ml
# ./esx_Zmet.f90 Uses Module MicroMet_ml
# ./esx_Zmet.f90 Uses Module ModelConstants
# ./esx_Zmet.f90 Uses Module PhysicalConstants_ml
# Full list of modules in ./esx_Zmet.f90: CheckStops Io_Routines KeyValueTypes esx_Variables esx_Zveg Kz_ml MicroMet_ml ModelConstants PhysicalConstants_ml 
# Uses CheckStops which is in ./CheckStops.f90
# ./CheckStops.f90 already in list
# Uses Io_Routines which is in ./Io_Routines.f90
# ./Io_Routines.f90 already in list
# Uses KeyValueTypes which is in ./KeyValueTypes.f90
# ./KeyValueTypes.f90 already in list
# Uses esx_Variables which is in ./esx_Variables.f90
# ./esx_Variables.f90 already in list
# Uses esx_Zveg which is in ./esx_Zveg.f90
# ./esx_Zveg.f90 already in list
# Uses Kz_ml which is in ./Kz_ml.f90
# process_fsource called with arg ./Kz_ml.f90 
# ./Kz_ml.f90 Uses Module PhysicalConstants_ml
# ./Kz_ml.f90 Uses Module MicroMet_ml
# Full list of modules in ./Kz_ml.f90: PhysicalConstants_ml MicroMet_ml 
# Uses PhysicalConstants_ml which is in ./PhysicalConstants_ml.f90
# ./PhysicalConstants_ml.f90 already in list
# Uses MicroMet_ml which is in ./MicroMet_ml.f90
# process_fsource called with arg ./MicroMet_ml.f90 
# Full list of modules in ./MicroMet_ml.f90:  
# Uses MicroMet_ml which is in ./MicroMet_ml.f90
# ./MicroMet_ml.f90 already in list
# Uses ModelConstants which is in ./ModelConstants.f90
# ./ModelConstants.f90 already in list
# Uses PhysicalConstants_ml which is in ./PhysicalConstants_ml.f90
# ./PhysicalConstants_ml.f90 already in list
# Uses esx_Zveg which is in ./esx_Zveg.f90
# ./esx_Zveg.f90 already in list
# Uses Io_ml which is in ./Io_ml.f90
# ./Io_ml.f90 already in list
# Uses Io_Progs which is in ./Io_Progs.f90
# ./Io_Progs.f90 already in list
# Uses Io_Routines which is in ./Io_Routines.f90
# ./Io_Routines.f90 already in list
# Uses ZchemData which is in ./ZchemData.f90
# ./ZchemData.f90 already in list
# Uses Zmet_ml which is in ./Zmet_ml.f90
# ./Zmet_ml.f90 already in list
# Uses Zmet_ml which is in ./Zmet_ml.f90
# ./Zmet_ml.f90 already in list
# Uses SmallUtils_ml which is in ./SmallUtils_ml.f90
# ./SmallUtils_ml.f90 already in list
# Uses TimeDate_ml which is in ./TimeDate_ml.f90
# ./TimeDate_ml.f90 already in list

# ------------------Macro-Defs---------------------
F90=gfortran  -pedantic -Wall -fbounds-check -fdefault-real-8 

# -------------------End-macro-Defs---------------------------

# Here is the link step 
esx_tester:CheckStops.o AllocInit.o CM_ChemSpecs.o ModelConstants.o SmallUtils_ml.o DefPhotolysis.o ZchemData.o KeyValueTypes.o LocalVariables.o PhysicalConstants_ml.o TimeDate_ml.o esx_Variables.o Io_ml.o Io_Progs.o Zmet_ml.o Ammonium_ml.o Io_Routines.o esx_Zveg.o DO3SE_ModelConstants_ml.o DO3SE_Util_ml.o DO3SE_GstoTypes_ml.o DO3SE_PhysicalConstants_ml.o DO3SE_Gsto_ml.o DO3SE_Photosynthesis_ml.o DO3SE_Resistance_ml.o DO3SE_SMD_ml.o esx_DO3SE.o esx_gleaf.o Radiation_ml.o esx_GetData.o ChemFunctions.o CM_ChemRates.o ChemSolver.o esx_ChemRun.o esx_MassBudget.o esx_Zchem.o esx_ZdiffSolver.o esx_Zgrid.o MicroMet_ml.o Kz_ml.o esx_Zmet.o esx_tester.o 
	 $(F90) -o esx_tester CheckStops.o AllocInit.o CM_ChemSpecs.o ModelConstants.o SmallUtils_ml.o DefPhotolysis.o ZchemData.o KeyValueTypes.o LocalVariables.o PhysicalConstants_ml.o TimeDate_ml.o esx_Variables.o Io_ml.o Io_Progs.o Zmet_ml.o Ammonium_ml.o Io_Routines.o esx_Zveg.o DO3SE_ModelConstants_ml.o DO3SE_Util_ml.o DO3SE_GstoTypes_ml.o DO3SE_PhysicalConstants_ml.o DO3SE_Gsto_ml.o DO3SE_Photosynthesis_ml.o DO3SE_Resistance_ml.o DO3SE_SMD_ml.o esx_DO3SE.o esx_gleaf.o Radiation_ml.o esx_GetData.o ChemFunctions.o CM_ChemRates.o ChemSolver.o esx_ChemRun.o esx_MassBudget.o esx_Zchem.o esx_ZdiffSolver.o esx_Zgrid.o MicroMet_ml.o Kz_ml.o esx_Zmet.o esx_tester.o   

# Here are the compile steps
 
CheckStops.o:./CheckStops.f90  
	 $(F90) -c ./CheckStops.f90 

AllocInit.o:./AllocInit.f90 CheckStops.o 
	 $(F90) -c ./AllocInit.f90 

CM_ChemSpecs.o:./CM_ChemSpecs.f90  
	 $(F90) -c ./CM_ChemSpecs.f90 

ModelConstants.o:./ModelConstants.f90  
	 $(F90) -c ./ModelConstants.f90 

SmallUtils_ml.o:./SmallUtils_ml.f90  
	 $(F90) -c ./SmallUtils_ml.f90 

DefPhotolysis.o:./DefPhotolysis.f90  
	 $(F90) -c ./DefPhotolysis.f90 

ZchemData.o:./ZchemData.f90 AllocInit.o CM_ChemSpecs.o DefPhotolysis.o 
	 $(F90) -c ./ZchemData.f90 

KeyValueTypes.o:./KeyValueTypes.f90  
	 $(F90) -c ./KeyValueTypes.f90 

LocalVariables.o:./LocalVariables.f90  
	 $(F90) -c ./LocalVariables.f90 

PhysicalConstants_ml.o:./PhysicalConstants_ml.f90  
	 $(F90) -c ./PhysicalConstants_ml.f90 

TimeDate_ml.o:./TimeDate_ml.f90  
	 $(F90) -c ./TimeDate_ml.f90 

esx_Variables.o:./esx_Variables.f90 CheckStops.o CM_ChemSpecs.o KeyValueTypes.o LocalVariables.o ModelConstants.o PhysicalConstants_ml.o SmallUtils_ml.o TimeDate_ml.o 
	 $(F90) -c ./esx_Variables.f90 

Io_ml.o:./Io_ml.f90  
	 $(F90) -c ./Io_ml.f90 

Io_Progs.o:./Io_Progs.f90 Io_ml.o 
	 $(F90) -c ./Io_Progs.f90 

Zmet_ml.o:./Zmet_ml.f90 AllocInit.o esx_Variables.o Io_Progs.o 
	 $(F90) -c ./Zmet_ml.f90 

Ammonium_ml.o:./Ammonium_ml.f90 CM_ChemSpecs.o ModelConstants.o SmallUtils_ml.o ZchemData.o Zmet_ml.o 
	 $(F90) -c ./Ammonium_ml.f90 

Io_Routines.o:./Io_Routines.f90 Io_ml.o 
	 $(F90) -c ./Io_Routines.f90 

esx_Zveg.o:./esx_Zveg.f90 CheckStops.o esx_Variables.o Io_Routines.o 
	 $(F90) -c ./esx_Zveg.f90 

DO3SE_ModelConstants_ml.o:DO3SE/src/DO3SE_ModelConstants_ml.F90  
	 $(F90) -c DO3SE/src/DO3SE_ModelConstants_ml.F90 

DO3SE_Util_ml.o:DO3SE/src/DO3SE_Util_ml.F90 DO3SE_ModelConstants_ml.o 
	 $(F90) -c DO3SE/src/DO3SE_Util_ml.F90 

DO3SE_GstoTypes_ml.o:DO3SE/src/DO3SE_GstoTypes_ml.F90 DO3SE_Util_ml.o DO3SE_ModelConstants_ml.o 
	 $(F90) -c DO3SE/src/DO3SE_GstoTypes_ml.F90 

DO3SE_PhysicalConstants_ml.o:DO3SE/src/DO3SE_PhysicalConstants_ml.F90  
	 $(F90) -c DO3SE/src/DO3SE_PhysicalConstants_ml.F90 

DO3SE_Gsto_ml.o:DO3SE/src/DO3SE_Gsto_ml.F90 DO3SE_GstoTypes_ml.o DO3SE_Util_ml.o DO3SE_PhysicalConstants_ml.o 
	 $(F90) -c DO3SE/src/DO3SE_Gsto_ml.F90 

DO3SE_Photosynthesis_ml.o:DO3SE/src/DO3SE_Photosynthesis_ml.F90 DO3SE_ModelConstants_ml.o DO3SE_GstoTypes_ml.o DO3SE_Util_ml.o 
	 $(F90) -c DO3SE/src/DO3SE_Photosynthesis_ml.F90 

DO3SE_Resistance_ml.o:DO3SE/src/DO3SE_Resistance_ml.F90 DO3SE_ModelConstants_ml.o 
	 $(F90) -c DO3SE/src/DO3SE_Resistance_ml.F90 

DO3SE_SMD_ml.o:DO3SE/src/DO3SE_SMD_ml.F90 DO3SE_ModelConstants_ml.o DO3SE_Resistance_ml.o DO3SE_Util_ml.o 
	 $(F90) -c DO3SE/src/DO3SE_SMD_ml.F90 

esx_DO3SE.o:./esx_DO3SE.f90 CheckStops.o DO3SE_GstoTypes_ml.o DO3SE_Gsto_ml.o DO3SE_Photosynthesis_ml.o DO3SE_SMD_ml.o DO3SE_Util_ml.o DO3SE_PhysicalConstants_ml.o esx_Variables.o esx_Zveg.o 
	 $(F90) -c ./esx_DO3SE.f90 

esx_gleaf.o:./esx_gleaf.f90 CheckStops.o esx_Variables.o esx_Zveg.o esx_DO3SE.o 
	 $(F90) -c ./esx_gleaf.f90 

Radiation_ml.o:./Radiation_ml.f90 PhysicalConstants_ml.o TimeDate_ml.o 
	 $(F90) -c ./Radiation_ml.f90 

esx_GetData.o:./esx_GetData.f90 CheckStops.o esx_Variables.o ModelConstants.o Radiation_ml.o TimeDate_ml.o 
	 $(F90) -c ./esx_GetData.f90 

ChemFunctions.o:./ChemFunctions.f90 PhysicalConstants_ml.o ZchemData.o ZchemData.o Zmet_ml.o CM_ChemSpecs.o 
	 $(F90) -c ./ChemFunctions.f90 

CM_ChemRates.o:./CM_ChemRates.f90 ChemFunctions.o Zmet_ml.o ZchemData.o CM_ChemSpecs.o DefPhotolysis.o 
	 $(F90) -c ./CM_ChemRates.f90 

ChemSolver.o:./ChemSolver.f90 CheckStops.o DefPhotolysis.o CM_ChemSpecs.o Io_ml.o ModelConstants.o ZchemData.o 
	 $(F90) -c ./ChemSolver.f90 

esx_ChemRun.o:./esx_ChemRun.f90 CM_ChemSpecs.o CM_ChemRates.o ChemSolver.o DefPhotolysis.o esx_Variables.o PhysicalConstants_ml.o ZchemData.o Zmet_ml.o 
	 $(F90) -c ./esx_ChemRun.f90 

esx_MassBudget.o:./esx_MassBudget.f90 CM_ChemSpecs.o esx_Variables.o 
	 $(F90) -c ./esx_MassBudget.f90 

esx_Zchem.o:./esx_Zchem.f90 CheckStops.o CM_ChemSpecs.o CM_ChemRates.o esx_Variables.o SmallUtils_ml.o ZchemData.o 
	 $(F90) -c ./esx_Zchem.f90 

esx_ZdiffSolver.o:./esx_ZdiffSolver.f90 esx_MassBudget.o esx_Variables.o 
	 $(F90) -c ./esx_ZdiffSolver.f90 

esx_Zgrid.o:./esx_Zgrid.f90 esx_Variables.o Io_Progs.o SmallUtils_ml.o 
	 $(F90) -c ./esx_Zgrid.f90 

MicroMet_ml.o:./MicroMet_ml.f90  
	 $(F90) -c ./MicroMet_ml.f90 

Kz_ml.o:./Kz_ml.f90 PhysicalConstants_ml.o MicroMet_ml.o 
	 $(F90) -c ./Kz_ml.f90 

esx_Zmet.o:./esx_Zmet.f90 CheckStops.o Io_Routines.o KeyValueTypes.o esx_Variables.o esx_Zveg.o Kz_ml.o MicroMet_ml.o ModelConstants.o PhysicalConstants_ml.o 
	 $(F90) -c ./esx_Zmet.f90 

esx_tester.o:esx_tester.f90 AllocInit.o Ammonium_ml.o CM_ChemSpecs.o CheckStops.o esx_gleaf.o esx_GetData.o esx_ChemRun.o esx_MassBudget.o esx_Variables.o esx_Zchem.o esx_ZdiffSolver.o esx_Zgrid.o esx_Zmet.o esx_Zveg.o Io_ml.o Io_Progs.o Io_Routines.o ZchemData.o Zmet_ml.o Zmet_ml.o SmallUtils_ml.o TimeDate_ml.o 
	 $(F90) -c esx_tester.f90 
# This entry allows you to type " make clean " to get rid of
# all object and module files 
clean:
	rm *.o *.mod 

  
