! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem09 VBS_acp2012 APINENE_BVOC_emis BVOC_EmChem19 Aqueous_EmChem16x Aero2017nx Ash ShipNOx FFireInert SeaSalt DustExtended Pollen
module ChemSpecs_mod

  use ChemDims_mod      ! => NSPEC_TOT, NCHEMRATES, ....
  
  implicit none
  private
  character(len=*),parameter, public :: CM_schemes_ChemSpecs = " EmChem09 VBS_acp2012 APINENE_BVOC_emis BVOC_EmChem19 Aqueous_EmChem16x Aero2017nx Ash ShipNOx FFireInert SeaSalt DustExtended Pollen"
  
  
  integer, public, parameter :: &
      OD          =   1  &
    , OP          =   2  &
    , OH          =   3  &
    , HO2         =   4  &
    , CH3O2       =   5  &
    , C2H5O2      =   6  &
    , SECC4H9O2   =   7  &
    , ISRO2       =   8  &
    , ETRO2       =   9  &
    , PRRO2       =  10
  
  integer, public, parameter :: &
      OXYO2       =  11  &
    , MEKO2       =  12  &
    , MALO2       =  13  &
    , MVKO2       =  14  &
    , MACRO2      =  15  &
    , MACO3       =  16  &
    , TERPO2      =  17  &
    , O3          =  18  &
    , NO          =  19  &
    , NO2         =  20
  
  integer, public, parameter :: &
      PAN         =  21  &
    , MPAN        =  22  &
    , NO3         =  23  &
    , N2O5        =  24  &
    , ISONO3      =  25  &
    , HNO3        =  26  &
    , HONO        =  27  &
    , CH3COO2     =  28  &
    , MACR        =  29  &
    , ISNI        =  30
  
  integer, public, parameter :: &
      ISNIR       =  31  &
    , GLYOX       =  32  &
    , MGLYOX      =  33  &
    , MAL         =  34  &
    , MEK         =  35  &
    , MVK         =  36  &
    , HCHO        =  37  &
    , CH3CHO      =  38  &
    , C2H6        =  39  &
    , NC4H10      =  40
  
  integer, public, parameter :: &
      C2H4        =  41  &
    , C3H6        =  42  &
    , OXYL        =  43  &
    , C5H8        =  44  &
    , CH3OOH      =  45  &
    , C2H5OOH     =  46  &
    , BURO2H      =  47  &
    , ETRO2H      =  48  &
    , PRRO2H      =  49  &
    , OXYO2H      =  50
  
  integer, public, parameter :: &
      MEKO2H      =  51  &
    , MALO2H      =  52  &
    , MVKO2H      =  53  &
    , MACROOH     =  54  &
    , MACO3H      =  55  &
    , MACO2H      =  56  &
    , ISRO2H      =  57  &
    , H2O2        =  58  &
    , CH3COO2H    =  59  &
    , ISONO3H     =  60
  
  integer, public, parameter :: &
      ISNIRH      =  61  &
    , CH3OH       =  62  &
    , C2H5OH      =  63  &
    , ACETOL      =  64  &
    , CO          =  65  &
    , SO2         =  66  &
    , SO4         =  67  &
    , NH3         =  68  &
    , NO3_f       =  69  &
    , NH4_f       =  70
  
  integer, public, parameter :: &
      NO3_c       =  71  &
    , TERPPeroxy  =  72  &
    , VBS_TEST    =  73  &
    , APINENE     =  74  &
    , SQT_SOA_nv  =  75  &
    , TERPOOH     =  76  &
    , shipNOx     =  77  &
    , Dust_road_f =  78  &
    , Dust_road_c =  79  &
    , Dust_wb_f   =  80
  
  integer, public, parameter :: &
      Dust_wb_c   =  81  &
    , Dust_sah_f  =  82  &
    , Dust_sah_c  =  83  &
    , POLLEN_BIRCH=  84  &
    , POLLEN_OLIVE=  85  &
    , POLLEN_RWEED=  86  &
    , POLLEN_GRASS=  87  &
    , ASOC_ng100  =  88  &
    , ASOC_ug1    =  89  &
    , ASOC_ug10   =  90
  
  integer, public, parameter :: &
      ASOC_ug1e2  =  91  &
    , ASOC_ug1e3  =  92  &
    , NON_C_ASOA_ng100=  93  &
    , NON_C_ASOA_ug1=  94  &
    , NON_C_ASOA_ug10=  95  &
    , NON_C_ASOA_ug1e2=  96  &
    , NON_C_ASOA_ug1e3=  97  &
    , BSOC_ng100  =  98  &
    , BSOC_ug1    =  99  &
    , BSOC_ug10   = 100
  
  integer, public, parameter :: &
      BSOC_ug1e2  = 101  &
    , BSOC_ug1e3  = 102  &
    , NON_C_BSOA_ng100= 103  &
    , NON_C_BSOA_ug1= 104  &
    , NON_C_BSOA_ug10= 105  &
    , NON_C_BSOA_ug1e2= 106  &
    , NON_C_BSOA_ug1e3= 107  &
    , Fffuel_ng10 = 108  &
    , woodOA_ng10 = 109  &
    , H2          = 110
  
  integer, public, parameter :: &
      CH4         = 111  &
    , POM_f_wood  = 112  &
    , POM_f_ffuel = 113  &
    , POM_c_ffuel = 114  &
    , EC_f_wood_new= 115  &
    , EC_f_wood_age= 116  &
    , EC_c_wood   = 117  &
    , EC_f_ffuel_new= 118  &
    , EC_f_ffuel_age= 119  &
    , EC_c_ffuel  = 120
  
  integer, public, parameter :: &
      REMPPM25    = 121  &
    , REMPPM_c    = 122  &
    , OM25_BGND   = 123  &
    , OM25_p      = 124  &
    , Ash_f       = 125  &
    , Ash_c       = 126  &
    , ffire_OM    = 127  &
    , ffire_BC    = 128  &
    , ffire_remPPM25= 129  &
    , ffire_c     = 130
  
  integer, public, parameter :: &
      SeaSalt_f   = 131  &
    , SeaSalt_c   = 132
  
  !+ Defines indices for ADV : Advected species
  integer, public, parameter :: FIRST_ADV=18, &
                                 LAST_ADV=132
  
  integer, public, parameter :: &
      IXADV_O3          =   1  &
    , IXADV_NO          =   2  &
    , IXADV_NO2         =   3  &
    , IXADV_PAN         =   4  &
    , IXADV_MPAN        =   5  &
    , IXADV_NO3         =   6  &
    , IXADV_N2O5        =   7  &
    , IXADV_ISONO3      =   8  &
    , IXADV_HNO3        =   9  &
    , IXADV_HONO        =  10
  
  integer, public, parameter :: &
      IXADV_CH3COO2     =  11  &
    , IXADV_MACR        =  12  &
    , IXADV_ISNI        =  13  &
    , IXADV_ISNIR       =  14  &
    , IXADV_GLYOX       =  15  &
    , IXADV_MGLYOX      =  16  &
    , IXADV_MAL         =  17  &
    , IXADV_MEK         =  18  &
    , IXADV_MVK         =  19  &
    , IXADV_HCHO        =  20
  
  integer, public, parameter :: &
      IXADV_CH3CHO      =  21  &
    , IXADV_C2H6        =  22  &
    , IXADV_NC4H10      =  23  &
    , IXADV_C2H4        =  24  &
    , IXADV_C3H6        =  25  &
    , IXADV_OXYL        =  26  &
    , IXADV_C5H8        =  27  &
    , IXADV_CH3OOH      =  28  &
    , IXADV_C2H5OOH     =  29  &
    , IXADV_BURO2H      =  30
  
  integer, public, parameter :: &
      IXADV_ETRO2H      =  31  &
    , IXADV_PRRO2H      =  32  &
    , IXADV_OXYO2H      =  33  &
    , IXADV_MEKO2H      =  34  &
    , IXADV_MALO2H      =  35  &
    , IXADV_MVKO2H      =  36  &
    , IXADV_MACROOH     =  37  &
    , IXADV_MACO3H      =  38  &
    , IXADV_MACO2H      =  39  &
    , IXADV_ISRO2H      =  40
  
  integer, public, parameter :: &
      IXADV_H2O2        =  41  &
    , IXADV_CH3COO2H    =  42  &
    , IXADV_ISONO3H     =  43  &
    , IXADV_ISNIRH      =  44  &
    , IXADV_CH3OH       =  45  &
    , IXADV_C2H5OH      =  46  &
    , IXADV_ACETOL      =  47  &
    , IXADV_CO          =  48  &
    , IXADV_SO2         =  49  &
    , IXADV_SO4         =  50
  
  integer, public, parameter :: &
      IXADV_NH3         =  51  &
    , IXADV_NO3_f       =  52  &
    , IXADV_NH4_f       =  53  &
    , IXADV_NO3_c       =  54  &
    , IXADV_TERPPeroxy  =  55  &
    , IXADV_VBS_TEST    =  56  &
    , IXADV_APINENE     =  57  &
    , IXADV_SQT_SOA_nv  =  58  &
    , IXADV_TERPOOH     =  59  &
    , IXADV_shipNOx     =  60
  
  integer, public, parameter :: &
      IXADV_Dust_road_f =  61  &
    , IXADV_Dust_road_c =  62  &
    , IXADV_Dust_wb_f   =  63  &
    , IXADV_Dust_wb_c   =  64  &
    , IXADV_Dust_sah_f  =  65  &
    , IXADV_Dust_sah_c  =  66  &
    , IXADV_POLLEN_BIRCH=  67  &
    , IXADV_POLLEN_OLIVE=  68  &
    , IXADV_POLLEN_RWEED=  69  &
    , IXADV_POLLEN_GRASS=  70
  
  integer, public, parameter :: &
      IXADV_ASOC_ng100  =  71  &
    , IXADV_ASOC_ug1    =  72  &
    , IXADV_ASOC_ug10   =  73  &
    , IXADV_ASOC_ug1e2  =  74  &
    , IXADV_ASOC_ug1e3  =  75  &
    , IXADV_NON_C_ASOA_ng100=  76  &
    , IXADV_NON_C_ASOA_ug1=  77  &
    , IXADV_NON_C_ASOA_ug10=  78  &
    , IXADV_NON_C_ASOA_ug1e2=  79  &
    , IXADV_NON_C_ASOA_ug1e3=  80
  
  integer, public, parameter :: &
      IXADV_BSOC_ng100  =  81  &
    , IXADV_BSOC_ug1    =  82  &
    , IXADV_BSOC_ug10   =  83  &
    , IXADV_BSOC_ug1e2  =  84  &
    , IXADV_BSOC_ug1e3  =  85  &
    , IXADV_NON_C_BSOA_ng100=  86  &
    , IXADV_NON_C_BSOA_ug1=  87  &
    , IXADV_NON_C_BSOA_ug10=  88  &
    , IXADV_NON_C_BSOA_ug1e2=  89  &
    , IXADV_NON_C_BSOA_ug1e3=  90
  
  integer, public, parameter :: &
      IXADV_Fffuel_ng10 =  91  &
    , IXADV_woodOA_ng10 =  92  &
    , IXADV_H2          =  93  &
    , IXADV_CH4         =  94  &
    , IXADV_POM_f_wood  =  95  &
    , IXADV_POM_f_ffuel =  96  &
    , IXADV_POM_c_ffuel =  97  &
    , IXADV_EC_f_wood_new=  98  &
    , IXADV_EC_f_wood_age=  99  &
    , IXADV_EC_c_wood   = 100
  
  integer, public, parameter :: &
      IXADV_EC_f_ffuel_new= 101  &
    , IXADV_EC_f_ffuel_age= 102  &
    , IXADV_EC_c_ffuel  = 103  &
    , IXADV_REMPPM25    = 104  &
    , IXADV_REMPPM_c    = 105  &
    , IXADV_OM25_BGND   = 106  &
    , IXADV_OM25_p      = 107  &
    , IXADV_Ash_f       = 108  &
    , IXADV_Ash_c       = 109  &
    , IXADV_ffire_OM    = 110
  
  integer, public, parameter :: &
      IXADV_ffire_BC    = 111  &
    , IXADV_ffire_remPPM25= 112  &
    , IXADV_ffire_c     = 113  &
    , IXADV_SeaSalt_f   = 114  &
    , IXADV_SeaSalt_c   = 115
  
  !+ Defines indices for SHL : Short-lived (non-advected) species
  integer, public, parameter :: FIRST_SHL=1, &
                                 LAST_SHL=17
  
  integer, public, parameter :: &
      IXSHL_OD          =   1  &
    , IXSHL_OP          =   2  &
    , IXSHL_OH          =   3  &
    , IXSHL_HO2         =   4  &
    , IXSHL_CH3O2       =   5  &
    , IXSHL_C2H5O2      =   6  &
    , IXSHL_SECC4H9O2   =   7  &
    , IXSHL_ISRO2       =   8  &
    , IXSHL_ETRO2       =   9  &
    , IXSHL_PRRO2       =  10
  
  integer, public, parameter :: &
      IXSHL_OXYO2       =  11  &
    , IXSHL_MEKO2       =  12  &
    , IXSHL_MALO2       =  13  &
    , IXSHL_MVKO2       =  14  &
    , IXSHL_MACRO2      =  15  &
    , IXSHL_MACO3       =  16  &
    , IXSHL_TERPO2      =  17
  
  !+ Defines indices for SEMIVOL : Semi-volatile organic aerosols
  integer, public, parameter :: FIRST_SEMIVOL=88, &
                                 LAST_SEMIVOL=109
  
  integer, public, parameter :: &
      IXSOA_ASOC_ng100  =   1  &
    , IXSOA_ASOC_ug1    =   2  &
    , IXSOA_ASOC_ug10   =   3  &
    , IXSOA_ASOC_ug1e2  =   4  &
    , IXSOA_ASOC_ug1e3  =   5  &
    , IXSOA_NON_C_ASOA_ng100=   6  &
    , IXSOA_NON_C_ASOA_ug1=   7  &
    , IXSOA_NON_C_ASOA_ug10=   8  &
    , IXSOA_NON_C_ASOA_ug1e2=   9  &
    , IXSOA_NON_C_ASOA_ug1e3=  10
  
  integer, public, parameter :: &
      IXSOA_BSOC_ng100  =  11  &
    , IXSOA_BSOC_ug1    =  12  &
    , IXSOA_BSOC_ug10   =  13  &
    , IXSOA_BSOC_ug1e2  =  14  &
    , IXSOA_BSOC_ug1e3  =  15  &
    , IXSOA_NON_C_BSOA_ng100=  16  &
    , IXSOA_NON_C_BSOA_ug1=  17  &
    , IXSOA_NON_C_BSOA_ug10=  18  &
    , IXSOA_NON_C_BSOA_ug1e2=  19  &
    , IXSOA_NON_C_BSOA_ug1e3=  20
  
  integer, public, parameter :: &
      IXSOA_Fffuel_ng10 =  21  &
    , IXSOA_woodOA_ng10 =  22
  
  !/--   Characteristics of species:
  !/--   Number, name, molwt, carbon num, nmhc (1) or not(0)
  
  public :: define_chemicals    ! Sets names, molwts, carbon num, advec, nmhc
  
  type, public :: Chemical
       character(len=20) :: name
       real              :: molwt
       integer           :: nmhc      ! nmhc (1) or not(0)
       real              :: carbons   ! Carbon-number
       real              :: nitrogens ! Nitrogen-number
       real              :: sulphurs  ! Sulphur-number
  endtype Chemical
  type(Chemical), public, dimension(NSPEC_TOT), target :: species
  
  ! Pointers to parts of species (e.g. short-lived, advected)
  type(Chemical), public, dimension(:), pointer :: species_adv=>null()
  type(Chemical), public, dimension(:), pointer :: species_shl=>null()
  type(Chemical), public, dimension(:), pointer :: species_semivol=>null()

contains
  subroutine define_chemicals()
    integer :: istart ! For NAG compliance
    !+
    ! Pointers to parts of species (e.g. short-lived, advected), only assigned if
    ! non-empty.
    !
    istart = 1
    if (NSPEC_ADV > 0) then
      if( FIRST_ADV > 0 ) istart = FIRST_ADV
      species_adv => species(istart:LAST_ADV)
    end if
    istart = 1
    if (NSPEC_SHL > 0) then
      if( FIRST_SHL > 0 ) istart = FIRST_SHL
      species_shl => species(istart:LAST_SHL)
    end if
    istart = 1
    if (NSPEC_SEMIVOL > 0) then
      if( FIRST_SEMIVOL > 0 ) istart = FIRST_SEMIVOL
      species_semivol => species(istart:LAST_SEMIVOL)
    end if
    
    !+
    ! Assigns names, mol wts, carbon numbers, advec,  nmhc to user-defined Chemical
    ! array, using indices from total list of species (advected + short-lived).
    !                                                      MW  NM   C    N   S
    species(OD          ) = Chemical("OD          ",  16.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(OP          ) = Chemical("OP          ",  16.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(OH          ) = Chemical("OH          ",  17.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(HO2         ) = Chemical("HO2         ",  33.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(CH3O2       ) = Chemical("CH3O2       ",  47.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(C2H5O2      ) = Chemical("C2H5O2      ",  61.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(SECC4H9O2   ) = Chemical("SECC4H9O2   ",  89.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(ISRO2       ) = Chemical("ISRO2       ", 101.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(ETRO2       ) = Chemical("ETRO2       ",  77.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(PRRO2       ) = Chemical("PRRO2       ",  91.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(OXYO2       ) = Chemical("OXYO2       ",   0.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(MEKO2       ) = Chemical("MEKO2       ", 103.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MALO2       ) = Chemical("MALO2       ", 147.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(MVKO2       ) = Chemical("MVKO2       ", 119.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MACRO2      ) = Chemical("MACRO2      ", 119.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MACO3       ) = Chemical("MACO3       ", 101.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(TERPO2      ) = Chemical("TERPO2      ",   0.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(O3          ) = Chemical("O3          ",  48.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NO          ) = Chemical("NO          ",  30.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NO2         ) = Chemical("NO2         ",  46.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(PAN         ) = Chemical("PAN         ", 121.0000,  0,   2.0000,   1.0000,   0.0000 )
    species(MPAN        ) = Chemical("MPAN        ", 132.0000,  0,   4.0000,   1.0000,   0.0000 )
    species(NO3         ) = Chemical("NO3         ",  62.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(N2O5        ) = Chemical("N2O5        ", 108.0000,  0,   0.0000,   2.0000,   0.0000 )
    species(ISONO3      ) = Chemical("ISONO3      ",   0.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(HNO3        ) = Chemical("HNO3        ",  63.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(HONO        ) = Chemical("HONO        ",  47.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(CH3COO2     ) = Chemical("CH3COO2     ",  75.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(MACR        ) = Chemical("MACR        ",  70.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(ISNI        ) = Chemical("ISNI        ",   0.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(ISNIR       ) = Chemical("ISNIR       ",   0.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(GLYOX       ) = Chemical("GLYOX       ",  58.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(MGLYOX      ) = Chemical("MGLYOX      ",  72.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(MAL         ) = Chemical("MAL         ",  98.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(MEK         ) = Chemical("MEK         ",  72.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MVK         ) = Chemical("MVK         ",  70.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(HCHO        ) = Chemical("HCHO        ",  30.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(CH3CHO      ) = Chemical("CH3CHO      ",  44.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(C2H6        ) = Chemical("C2H6        ",  30.0000,  1,   2.0000,   0.0000,   0.0000 )
    species(NC4H10      ) = Chemical("NC4H10      ",  58.0000,  1,   4.0000,   0.0000,   0.0000 )
    species(C2H4        ) = Chemical("C2H4        ",  28.0000,  1,   2.0000,   0.0000,   0.0000 )
    species(C3H6        ) = Chemical("C3H6        ",  42.0000,  1,   3.0000,   0.0000,   0.0000 )
    species(OXYL        ) = Chemical("OXYL        ", 106.0000,  1,   8.0000,   0.0000,   0.0000 )
    species(C5H8        ) = Chemical("C5H8        ",  68.0000,  1,   5.0000,   0.0000,   0.0000 )
    species(CH3OOH      ) = Chemical("CH3OOH      ",  48.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(C2H5OOH     ) = Chemical("C2H5OOH     ",  62.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(BURO2H      ) = Chemical("BURO2H      ",  90.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(ETRO2H      ) = Chemical("ETRO2H      ",  78.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(PRRO2H      ) = Chemical("PRRO2H      ",  92.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(OXYO2H      ) = Chemical("OXYO2H      ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(MEKO2H      ) = Chemical("MEKO2H      ", 104.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MALO2H      ) = Chemical("MALO2H      ", 147.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(MVKO2H      ) = Chemical("MVKO2H      ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(MACROOH     ) = Chemical("MACROOH     ", 120.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MACO3H      ) = Chemical("MACO3H      ", 102.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MACO2H      ) = Chemical("MACO2H      ",  86.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(ISRO2H      ) = Chemical("ISRO2H      ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(H2O2        ) = Chemical("H2O2        ",  34.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(CH3COO2H    ) = Chemical("CH3COO2H    ",  76.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(ISONO3H     ) = Chemical("ISONO3H     ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(ISNIRH      ) = Chemical("ISNIRH      ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(CH3OH       ) = Chemical("CH3OH       ",  32.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(C2H5OH      ) = Chemical("C2H5OH      ",  46.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(ACETOL      ) = Chemical("ACETOL      ",  74.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(CO          ) = Chemical("CO          ",  28.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(SO2         ) = Chemical("SO2         ",  64.0000,  0,   0.0000,   0.0000,   1.0000 )
    species(SO4         ) = Chemical("SO4         ",  96.0000,  0,   0.0000,   0.0000,   1.0000 )
    species(NH3         ) = Chemical("NH3         ",  17.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NO3_f       ) = Chemical("NO3_f       ",  62.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NH4_f       ) = Chemical("NH4_f       ",  18.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NO3_c       ) = Chemical("NO3_c       ",  62.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(TERPPeroxy  ) = Chemical("TERPPeroxy  ",   0.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(VBS_TEST    ) = Chemical("VBS_TEST    ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(APINENE     ) = Chemical("APINENE     ", 136.0000,  1,  10.0000,   0.0000,   0.0000 )
    species(SQT_SOA_nv  ) = Chemical("SQT_SOA_nv  ", 302.0000,  0,  14.0000,   0.0000,   0.0000 )
    species(TERPOOH     ) = Chemical("TERPOOH     ", 186.0000,  0,  10.0000,   0.0000,   0.0000 )
    species(shipNOx     ) = Chemical("shipNOx     ",  46.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(Dust_road_f ) = Chemical("Dust_road_f ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_road_c ) = Chemical("Dust_road_c ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_wb_f   ) = Chemical("Dust_wb_f   ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_wb_c   ) = Chemical("Dust_wb_c   ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_sah_f  ) = Chemical("Dust_sah_f  ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_sah_c  ) = Chemical("Dust_sah_c  ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(POLLEN_BIRCH) = Chemical("POLLEN_BIRCH",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(POLLEN_OLIVE) = Chemical("POLLEN_OLIVE",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(POLLEN_RWEED) = Chemical("POLLEN_RWEED",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(POLLEN_GRASS) = Chemical("POLLEN_GRASS",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(ASOC_ng100  ) = Chemical("ASOC_ng100  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug1    ) = Chemical("ASOC_ug1    ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug10   ) = Chemical("ASOC_ug10   ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug1e2  ) = Chemical("ASOC_ug1e2  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug1e3  ) = Chemical("ASOC_ug1e3  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(NON_C_ASOA_ng100) = Chemical("NON_C_ASOA_ng100",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_ASOA_ug1) = Chemical("NON_C_ASOA_ug1",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_ASOA_ug10) = Chemical("NON_C_ASOA_ug10",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_ASOA_ug1e2) = Chemical("NON_C_ASOA_ug1e2",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_ASOA_ug1e3) = Chemical("NON_C_ASOA_ug1e3",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(BSOC_ng100  ) = Chemical("BSOC_ng100  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug1    ) = Chemical("BSOC_ug1    ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug10   ) = Chemical("BSOC_ug10   ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug1e2  ) = Chemical("BSOC_ug1e2  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug1e3  ) = Chemical("BSOC_ug1e3  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(NON_C_BSOA_ng100) = Chemical("NON_C_BSOA_ng100",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_BSOA_ug1) = Chemical("NON_C_BSOA_ug1",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_BSOA_ug10) = Chemical("NON_C_BSOA_ug10",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_BSOA_ug1e2) = Chemical("NON_C_BSOA_ug1e2",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NON_C_BSOA_ug1e3) = Chemical("NON_C_BSOA_ug1e3",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Fffuel_ng10 ) = Chemical("Fffuel_ng10 ",  15.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(woodOA_ng10 ) = Chemical("woodOA_ng10 ",  20.4000,  0,   1.0000,   0.0000,   0.0000 )
    species(H2          ) = Chemical("H2          ",   2.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(CH4         ) = Chemical("CH4         ",  16.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(POM_f_wood  ) = Chemical("POM_f_wood  ",  20.4000,  0,   1.0000,   0.0000,   0.0000 )
    species(POM_f_ffuel ) = Chemical("POM_f_ffuel ",  15.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(POM_c_ffuel ) = Chemical("POM_c_ffuel ",  15.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_wood_new) = Chemical("EC_f_wood_new",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_wood_age) = Chemical("EC_f_wood_age",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_c_wood   ) = Chemical("EC_c_wood   ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_ffuel_new) = Chemical("EC_f_ffuel_new",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_ffuel_age) = Chemical("EC_f_ffuel_age",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_c_ffuel  ) = Chemical("EC_c_ffuel  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(REMPPM25    ) = Chemical("REMPPM25    ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(REMPPM_c    ) = Chemical("REMPPM_c    ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(OM25_BGND   ) = Chemical("OM25_BGND   ",  24.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(OM25_p      ) = Chemical("OM25_p      ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Ash_f       ) = Chemical("Ash_f       ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Ash_c       ) = Chemical("Ash_c       ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(ffire_OM    ) = Chemical("ffire_OM    ",  20.4000,  0,   1.0000,   0.0000,   0.0000 )
    species(ffire_BC    ) = Chemical("ffire_BC    ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ffire_remPPM25) = Chemical("ffire_remPPM25",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(ffire_c     ) = Chemical("ffire_c     ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(SeaSalt_f   ) = Chemical("SeaSalt_f   ",  58.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(SeaSalt_c   ) = Chemical("SeaSalt_c   ",  58.0000,  0,   0.0000,   0.0000,   0.0000 )
  end subroutine define_chemicals

end module ChemSpecs_mod
