! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem19X PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis
module ChemSpecs_mod

  use ChemDims_mod      ! => NSPEC_TOT, NCHEMRATES, ....
  
  implicit none
  private
  character(len=*),parameter, public :: CM_schemes_ChemSpecs = " EmChem19X PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis"
  
  
  integer, public, parameter :: &
      OD          =   1  &
    , OP          =   2  &
    , OH          =   3  &
    , HO2         =   4  &
    , CH3O2       =   5  &
    , C2H5O2      =   6  &
    , C4H9O2      =   7  &
    , ISRO2       =   8  &
    , HCOCH2O2    =   9  &
    , ETRO2       =  10
  
  integer, public, parameter :: &
      PRRO2       =  11  &
    , HMVKO2      =  12  &
    , OXYBIPERO2  =  13  &
    , MACO3       =  14  &
    , MEKO2       =  15  &
    , C5DICARBO2  =  16  &
    , DM123O2     =  17  &
    , OXCATEC1O2  =  18  &
    , CH2O2CO3H   =  19  &
    , MACRO2      =  20
  
  integer, public, parameter :: &
      HOCH2CO3    =  21  &
    , CH3CO3      =  22  &
    , C2H5CO3     =  23  &
    , CO2H3CO3    =  24  &
    , IBUTOLBO2   =  25  &
    , HOCH2CH2O   =  26  &
    , OXY1O       =  27  &
    , OXCATEC1O   =  28  &
    , TERPO2      =  29  &
    , RO2POOL     =  30
  
  integer, public, parameter :: &
      NRN9O2      =  31  &
    , NISOPO2     =  32  &
    , NC4CO3      =  33  &
    , NOXYOLO2    =  34  &
    , OXNCATECO2  =  35  &
    , OXNNCATCO2  =  36  &
    , NOXYOL1O2   =  37  &
    , NOXYOL1O    =  38  &
    , NMVOC       =  39  &
    , O3          =  40
  
  integer, public, parameter :: &
      NO          =  41  &
    , NO2         =  42  &
    , NO3         =  43  &
    , N2O5        =  44  &
    , H2          =  45  &
    , H2O2        =  46  &
    , HONO        =  47  &
    , HNO3        =  48  &
    , HO2NO2      =  49  &
    , CO          =  50
  
  integer, public, parameter :: &
      CH4         =  51  &
    , C2H6        =  52  &
    , NC4H10      =  53  &
    , C2H4        =  54  &
    , C3H6        =  55  &
    , BENZENE     =  56  &
    , TOLUENE     =  57  &
    , OXYL        =  58  &
    , C5H8        =  59  &
    , CH3OH       =  60
  
  integer, public, parameter :: &
      C2H5OH      =  61  &
    , OXYLOL      =  62  &
    , OXYCATECH   =  63  &
    , HCHO        =  64  &
    , CH3CHO      =  65  &
    , MACR        =  66  &
    , MEK         =  67  &
    , MVK         =  68  &
    , HOCH2CHO    =  69  &
    , HCOCH2OOH   =  70
  
  integer, public, parameter :: &
      ACETOL      =  71  &
    , GLYOX       =  72  &
    , MGLYOX      =  73  &
    , EGLYOX      =  74  &
    , CO2H3CHO    =  75  &
    , CO23C3CHO   =  76  &
    , BIACET      =  77  &
    , BIACETOH    =  78  &
    , C5DICARB    =  79  &
    , BZFUONE     =  80
  
  integer, public, parameter :: &
      HOCH2CO2H   =  81  &
    , CH3COCO2H   =  82  &
    , MACO2H      =  83  &
    , CH3OOH      =  84  &
    , C2H5OOH     =  85  &
    , BURO2H      =  86  &
    , DM123OOH    =  87  &
    , ETRO2H      =  88  &
    , MEKO2H      =  89  &
    , ISRO2H      =  90
  
  integer, public, parameter :: &
      C5DICAROOH  =  91  &
    , OCATEC1OOH  =  92  &
    , HPALD       =  93  &
    , MVKO2H      =  94  &
    , MACROOH     =  95  &
    , OXYBPEROOH  =  96  &
    , CH3CO3H     =  97  &
    , CO2H3CO3H   =  98  &
    , IEPOX       =  99  &
    , SC4H9NO3    = 100
  
  integer, public, parameter :: &
      MVKNO3      = 101  &
    , OXY1OHNO2   = 102  &
    , OXNCATECH   = 103  &
    , NOXYOL1OOH  = 104  &
    , CO2N3CHO    = 105  &
    , NALD        = 106  &
    , NOA         = 107  &
    , ISON        = 108  &
    , ISON2       = 109  &
    , NC4MDCO2H   = 110
  
  integer, public, parameter :: &
      NOXYOLOOH   = 111  &
    , OXNCATCOOH  = 112  &
    , PAN         = 113  &
    , PHAN        = 114  &
    , PPN         = 115  &
    , MPAN        = 116  &
    , C4PAN6      = 117  &
    , C5PAN18     = 118  &
    , OXNNCATOOH  = 119  &
    , APINENE     = 120
  
  integer, public, parameter :: &
      TERPOOH     = 121  &
    , SO2         = 122  &
    , shipNOx     = 123  &
    , Dust_road_f = 124  &
    , Dust_road_c = 125  &
    , Dust_wb_f   = 126  &
    , Dust_wb_c   = 127  &
    , Dust_sah_f  = 128  &
    , Dust_sah_c  = 129  &
    , SQT_SOA_NV  = 130
  
  integer, public, parameter :: &
      ASOC_ng1e2  = 131  &
    , ASOC_ug1    = 132  &
    , ASOC_ug10   = 133  &
    , ASOC_ug1e2  = 134  &
    , ASOC_ug1e3  = 135  &
    , non_C_ASOA_ng1e2= 136  &
    , non_C_ASOA_ug1= 137  &
    , non_C_ASOA_ug10= 138  &
    , non_C_ASOA_ug1e2= 139  &
    , non_C_ASOA_ug1e3= 140
  
  integer, public, parameter :: &
      BSOC_ng1e2  = 141  &
    , BSOC_ug1    = 142  &
    , BSOC_ug10   = 143  &
    , BSOC_ug1e2  = 144  &
    , BSOC_ug1e3  = 145  &
    , non_C_BSOA_ng1e2= 146  &
    , non_C_BSOA_ug1= 147  &
    , non_C_BSOA_ug10= 148  &
    , non_C_BSOA_ug1e2= 149  &
    , non_C_BSOA_ug1e3= 150
  
  integer, public, parameter :: &
      SO4         = 151  &
    , NH3         = 152  &
    , NO3_f       = 153  &
    , NO3_c       = 154  &
    , NH4_f       = 155  &
    , OM25_bgnd   = 156  &
    , OM25_p      = 157  &
    , ffire_OM    = 158  &
    , ffire_BC    = 159  &
    , ffire_remPPM25= 160
  
  integer, public, parameter :: &
      ffire_c     = 161  &
    , SeaSalt_f   = 162  &
    , SeaSalt_c   = 163  &
    , Ash_f       = 164  &
    , Ash_c       = 165  &
    , POM_f_wood  = 166  &
    , POM_c_wood  = 167  &
    , POM_f_ffuel = 168  &
    , POM_c_ffuel = 169  &
    , EC_f_wood_new= 170
  
  integer, public, parameter :: &
      EC_f_wood_age= 171  &
    , EC_c_wood   = 172  &
    , EC_f_ffuel_new= 173  &
    , EC_f_ffuel_age= 174  &
    , EC_c_ffuel  = 175  &
    , pSO4f       = 176  &
    , pSO4c       = 177  &
    , remPPM25    = 178  &
    , remPPM_c    = 179
  
  !+ Defines indices for ADV : Advected species
  integer, public, parameter :: FIRST_ADV=30, &
                                 LAST_ADV=179
  
  integer, public, parameter :: &
      IXADV_RO2POOL     =   1  &
    , IXADV_NRN9O2      =   2  &
    , IXADV_NISOPO2     =   3  &
    , IXADV_NC4CO3      =   4  &
    , IXADV_NOXYOLO2    =   5  &
    , IXADV_OXNCATECO2  =   6  &
    , IXADV_OXNNCATCO2  =   7  &
    , IXADV_NOXYOL1O2   =   8  &
    , IXADV_NOXYOL1O    =   9  &
    , IXADV_NMVOC       =  10
  
  integer, public, parameter :: &
      IXADV_O3          =  11  &
    , IXADV_NO          =  12  &
    , IXADV_NO2         =  13  &
    , IXADV_NO3         =  14  &
    , IXADV_N2O5        =  15  &
    , IXADV_H2          =  16  &
    , IXADV_H2O2        =  17  &
    , IXADV_HONO        =  18  &
    , IXADV_HNO3        =  19  &
    , IXADV_HO2NO2      =  20
  
  integer, public, parameter :: &
      IXADV_CO          =  21  &
    , IXADV_CH4         =  22  &
    , IXADV_C2H6        =  23  &
    , IXADV_NC4H10      =  24  &
    , IXADV_C2H4        =  25  &
    , IXADV_C3H6        =  26  &
    , IXADV_BENZENE     =  27  &
    , IXADV_TOLUENE     =  28  &
    , IXADV_OXYL        =  29  &
    , IXADV_C5H8        =  30
  
  integer, public, parameter :: &
      IXADV_CH3OH       =  31  &
    , IXADV_C2H5OH      =  32  &
    , IXADV_OXYLOL      =  33  &
    , IXADV_OXYCATECH   =  34  &
    , IXADV_HCHO        =  35  &
    , IXADV_CH3CHO      =  36  &
    , IXADV_MACR        =  37  &
    , IXADV_MEK         =  38  &
    , IXADV_MVK         =  39  &
    , IXADV_HOCH2CHO    =  40
  
  integer, public, parameter :: &
      IXADV_HCOCH2OOH   =  41  &
    , IXADV_ACETOL      =  42  &
    , IXADV_GLYOX       =  43  &
    , IXADV_MGLYOX      =  44  &
    , IXADV_EGLYOX      =  45  &
    , IXADV_CO2H3CHO    =  46  &
    , IXADV_CO23C3CHO   =  47  &
    , IXADV_BIACET      =  48  &
    , IXADV_BIACETOH    =  49  &
    , IXADV_C5DICARB    =  50
  
  integer, public, parameter :: &
      IXADV_BZFUONE     =  51  &
    , IXADV_HOCH2CO2H   =  52  &
    , IXADV_CH3COCO2H   =  53  &
    , IXADV_MACO2H      =  54  &
    , IXADV_CH3OOH      =  55  &
    , IXADV_C2H5OOH     =  56  &
    , IXADV_BURO2H      =  57  &
    , IXADV_DM123OOH    =  58  &
    , IXADV_ETRO2H      =  59  &
    , IXADV_MEKO2H      =  60
  
  integer, public, parameter :: &
      IXADV_ISRO2H      =  61  &
    , IXADV_C5DICAROOH  =  62  &
    , IXADV_OCATEC1OOH  =  63  &
    , IXADV_HPALD       =  64  &
    , IXADV_MVKO2H      =  65  &
    , IXADV_MACROOH     =  66  &
    , IXADV_OXYBPEROOH  =  67  &
    , IXADV_CH3CO3H     =  68  &
    , IXADV_CO2H3CO3H   =  69  &
    , IXADV_IEPOX       =  70
  
  integer, public, parameter :: &
      IXADV_SC4H9NO3    =  71  &
    , IXADV_MVKNO3      =  72  &
    , IXADV_OXY1OHNO2   =  73  &
    , IXADV_OXNCATECH   =  74  &
    , IXADV_NOXYOL1OOH  =  75  &
    , IXADV_CO2N3CHO    =  76  &
    , IXADV_NALD        =  77  &
    , IXADV_NOA         =  78  &
    , IXADV_ISON        =  79  &
    , IXADV_ISON2       =  80
  
  integer, public, parameter :: &
      IXADV_NC4MDCO2H   =  81  &
    , IXADV_NOXYOLOOH   =  82  &
    , IXADV_OXNCATCOOH  =  83  &
    , IXADV_PAN         =  84  &
    , IXADV_PHAN        =  85  &
    , IXADV_PPN         =  86  &
    , IXADV_MPAN        =  87  &
    , IXADV_C4PAN6      =  88  &
    , IXADV_C5PAN18     =  89  &
    , IXADV_OXNNCATOOH  =  90
  
  integer, public, parameter :: &
      IXADV_APINENE     =  91  &
    , IXADV_TERPOOH     =  92  &
    , IXADV_SO2         =  93  &
    , IXADV_shipNOx     =  94  &
    , IXADV_Dust_road_f =  95  &
    , IXADV_Dust_road_c =  96  &
    , IXADV_Dust_wb_f   =  97  &
    , IXADV_Dust_wb_c   =  98  &
    , IXADV_Dust_sah_f  =  99  &
    , IXADV_Dust_sah_c  = 100
  
  integer, public, parameter :: &
      IXADV_SQT_SOA_NV  = 101  &
    , IXADV_ASOC_ng1e2  = 102  &
    , IXADV_ASOC_ug1    = 103  &
    , IXADV_ASOC_ug10   = 104  &
    , IXADV_ASOC_ug1e2  = 105  &
    , IXADV_ASOC_ug1e3  = 106  &
    , IXADV_non_C_ASOA_ng1e2= 107  &
    , IXADV_non_C_ASOA_ug1= 108  &
    , IXADV_non_C_ASOA_ug10= 109  &
    , IXADV_non_C_ASOA_ug1e2= 110
  
  integer, public, parameter :: &
      IXADV_non_C_ASOA_ug1e3= 111  &
    , IXADV_BSOC_ng1e2  = 112  &
    , IXADV_BSOC_ug1    = 113  &
    , IXADV_BSOC_ug10   = 114  &
    , IXADV_BSOC_ug1e2  = 115  &
    , IXADV_BSOC_ug1e3  = 116  &
    , IXADV_non_C_BSOA_ng1e2= 117  &
    , IXADV_non_C_BSOA_ug1= 118  &
    , IXADV_non_C_BSOA_ug10= 119  &
    , IXADV_non_C_BSOA_ug1e2= 120
  
  integer, public, parameter :: &
      IXADV_non_C_BSOA_ug1e3= 121  &
    , IXADV_SO4         = 122  &
    , IXADV_NH3         = 123  &
    , IXADV_NO3_f       = 124  &
    , IXADV_NO3_c       = 125  &
    , IXADV_NH4_f       = 126  &
    , IXADV_OM25_bgnd   = 127  &
    , IXADV_OM25_p      = 128  &
    , IXADV_ffire_OM    = 129  &
    , IXADV_ffire_BC    = 130
  
  integer, public, parameter :: &
      IXADV_ffire_remPPM25= 131  &
    , IXADV_ffire_c     = 132  &
    , IXADV_SeaSalt_f   = 133  &
    , IXADV_SeaSalt_c   = 134  &
    , IXADV_Ash_f       = 135  &
    , IXADV_Ash_c       = 136  &
    , IXADV_POM_f_wood  = 137  &
    , IXADV_POM_c_wood  = 138  &
    , IXADV_POM_f_ffuel = 139  &
    , IXADV_POM_c_ffuel = 140
  
  integer, public, parameter :: &
      IXADV_EC_f_wood_new= 141  &
    , IXADV_EC_f_wood_age= 142  &
    , IXADV_EC_c_wood   = 143  &
    , IXADV_EC_f_ffuel_new= 144  &
    , IXADV_EC_f_ffuel_age= 145  &
    , IXADV_EC_c_ffuel  = 146  &
    , IXADV_pSO4f       = 147  &
    , IXADV_pSO4c       = 148  &
    , IXADV_remPPM25    = 149  &
    , IXADV_remPPM_c    = 150
  
  !+ Defines indices for SHL : Short-lived (non-advected) species
  integer, public, parameter :: FIRST_SHL=1, &
                                 LAST_SHL=29
  
  integer, public, parameter :: &
      IXSHL_OD          =   1  &
    , IXSHL_OP          =   2  &
    , IXSHL_OH          =   3  &
    , IXSHL_HO2         =   4  &
    , IXSHL_CH3O2       =   5  &
    , IXSHL_C2H5O2      =   6  &
    , IXSHL_C4H9O2      =   7  &
    , IXSHL_ISRO2       =   8  &
    , IXSHL_HCOCH2O2    =   9  &
    , IXSHL_ETRO2       =  10
  
  integer, public, parameter :: &
      IXSHL_PRRO2       =  11  &
    , IXSHL_HMVKO2      =  12  &
    , IXSHL_OXYBIPERO2  =  13  &
    , IXSHL_MACO3       =  14  &
    , IXSHL_MEKO2       =  15  &
    , IXSHL_C5DICARBO2  =  16  &
    , IXSHL_DM123O2     =  17  &
    , IXSHL_OXCATEC1O2  =  18  &
    , IXSHL_CH2O2CO3H   =  19  &
    , IXSHL_MACRO2      =  20
  
  integer, public, parameter :: &
      IXSHL_HOCH2CO3    =  21  &
    , IXSHL_CH3CO3      =  22  &
    , IXSHL_C2H5CO3     =  23  &
    , IXSHL_CO2H3CO3    =  24  &
    , IXSHL_IBUTOLBO2   =  25  &
    , IXSHL_HOCH2CH2O   =  26  &
    , IXSHL_OXY1O       =  27  &
    , IXSHL_OXCATEC1O   =  28  &
    , IXSHL_TERPO2      =  29
  
  !+ Defines indices for SEMIVOL : Semi-volatile organic aerosols
  integer, public, parameter :: FIRST_SEMIVOL=131, &
                                 LAST_SEMIVOL=150
  
  integer, public, parameter :: &
      IXSOA_ASOC_ng1e2  =   1  &
    , IXSOA_ASOC_ug1    =   2  &
    , IXSOA_ASOC_ug10   =   3  &
    , IXSOA_ASOC_ug1e2  =   4  &
    , IXSOA_ASOC_ug1e3  =   5  &
    , IXSOA_non_C_ASOA_ng1e2=   6  &
    , IXSOA_non_C_ASOA_ug1=   7  &
    , IXSOA_non_C_ASOA_ug10=   8  &
    , IXSOA_non_C_ASOA_ug1e2=   9  &
    , IXSOA_non_C_ASOA_ug1e3=  10
  
  integer, public, parameter :: &
      IXSOA_BSOC_ng1e2  =  11  &
    , IXSOA_BSOC_ug1    =  12  &
    , IXSOA_BSOC_ug10   =  13  &
    , IXSOA_BSOC_ug1e2  =  14  &
    , IXSOA_BSOC_ug1e3  =  15  &
    , IXSOA_non_C_BSOA_ng1e2=  16  &
    , IXSOA_non_C_BSOA_ug1=  17  &
    , IXSOA_non_C_BSOA_ug10=  18  &
    , IXSOA_non_C_BSOA_ug1e2=  19  &
    , IXSOA_non_C_BSOA_ug1e3=  20
  
  !/--   Characteristics of species:
  !/--   Number, name, molwt, carbon num, nmhc (1) or not(0)
  
  public :: define_chemicals    ! Sets names, molwts, carbon num, advec, nmhc
  
  type, public :: Chemical
       character(len=20) :: name
       real              :: molwt
       integer           :: nmhc      ! nmhc (1) or not(0)
       real              :: carbons   ! Carbon-number
       real              :: nitrogens ! Nitrogen-number
       real              :: sulphurs  ! Sulphur-number
  endtype Chemical
  type(Chemical), public, dimension(NSPEC_TOT), target :: species
  
  ! Pointers to parts of species (e.g. short-lived, advected)
  type(Chemical), public, dimension(:), pointer :: species_adv=>null()
  type(Chemical), public, dimension(:), pointer :: species_shl=>null()
  type(Chemical), public, dimension(:), pointer :: species_semivol=>null()

contains
  subroutine define_chemicals()
    integer :: istart ! For NAG compliance
    !+
    ! Pointers to parts of species (e.g. short-lived, advected), only assigned if
    ! non-empty.
    !
    istart = 1
    if (NSPEC_ADV > 0) then
      if( FIRST_ADV > 0 ) istart = FIRST_ADV
      species_adv => species(istart:LAST_ADV)
    end if
    istart = 1
    if (NSPEC_SHL > 0) then
      if( FIRST_SHL > 0 ) istart = FIRST_SHL
      species_shl => species(istart:LAST_SHL)
    end if
    istart = 1
    if (NSPEC_SEMIVOL > 0) then
      if( FIRST_SEMIVOL > 0 ) istart = FIRST_SEMIVOL
      species_semivol => species(istart:LAST_SEMIVOL)
    end if
    
    !+
    ! Assigns names, mol wts, carbon numbers, advec,  nmhc to user-defined Chemical
    ! array, using indices from total list of species (advected + short-lived).
    !                                                      MW  NM   C    N   S
    species(OD          ) = Chemical("OD          ",  16.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(OP          ) = Chemical("OP          ",  16.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(OH          ) = Chemical("OH          ",  17.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(HO2         ) = Chemical("HO2         ",  33.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(CH3O2       ) = Chemical("CH3O2       ",  47.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(C2H5O2      ) = Chemical("C2H5O2      ",  61.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(C4H9O2      ) = Chemical("C4H9O2      ",  89.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(ISRO2       ) = Chemical("ISRO2       ", 101.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(HCOCH2O2    ) = Chemical("HCOCH2O2    ",  75.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(ETRO2       ) = Chemical("ETRO2       ",  77.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(PRRO2       ) = Chemical("PRRO2       ",  91.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(HMVKO2      ) = Chemical("HMVKO2      ", 119.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(OXYBIPERO2  ) = Chemical("OXYBIPERO2  ", 187.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(MACO3       ) = Chemical("MACO3       ", 101.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MEKO2       ) = Chemical("MEKO2       ", 103.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(C5DICARBO2  ) = Chemical("C5DICARBO2  ", 147.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(DM123O2     ) = Chemical("DM123O2     ", 137.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(OXCATEC1O2  ) = Chemical("OXCATEC1O2  ", 153.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(CH2O2CO3H   ) = Chemical("CH2O2CO3H   ", 107.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(MACRO2      ) = Chemical("MACRO2      ", 119.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(HOCH2CO3    ) = Chemical("HOCH2CO3    ",  91.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(CH3CO3      ) = Chemical("CH3CO3      ",  75.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(C2H5CO3     ) = Chemical("C2H5CO3     ",  89.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(CO2H3CO3    ) = Chemical("CO2H3CO3    ", 133.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(IBUTOLBO2   ) = Chemical("IBUTOLBO2   ", 105.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(HOCH2CH2O   ) = Chemical("HOCH2CH2O   ",  61.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(OXY1O       ) = Chemical("OXY1O       ", 121.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(OXCATEC1O   ) = Chemical("OXCATEC1O   ", 137.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(TERPO2      ) = Chemical("TERPO2      ",   0.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(RO2POOL     ) = Chemical("RO2POOL     ",  64.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NRN9O2      ) = Chemical("NRN9O2      ", 136.0000,  0,   3.0000,   1.0000,   0.0000 )
    species(NISOPO2     ) = Chemical("NISOPO2     ", 162.0000,  0,   5.0000,   1.0000,   0.0000 )
    species(NC4CO3      ) = Chemical("NC4CO3      ", 176.0000,  0,   5.0000,   1.0000,   0.0000 )
    species(NOXYOLO2    ) = Chemical("NOXYOLO2    ", 248.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(OXNCATECO2  ) = Chemical("OXNCATECO2  ", 264.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(OXNNCATCO2  ) = Chemical("OXNNCATCO2  ", 309.0000,  0,   8.0000,   2.0000,   0.0000 )
    species(NOXYOL1O2   ) = Chemical("NOXYOL1O2   ", 182.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(NOXYOL1O    ) = Chemical("NOXYOL1O    ", 166.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(NMVOC       ) = Chemical("NMVOC       ",  36.7670,  0,   0.0000,   0.0000,   0.0000 )
    species(O3          ) = Chemical("O3          ",  48.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(NO          ) = Chemical("NO          ",  30.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NO2         ) = Chemical("NO2         ",  46.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NO3         ) = Chemical("NO3         ",  62.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(N2O5        ) = Chemical("N2O5        ", 108.0000,  0,   0.0000,   2.0000,   0.0000 )
    species(H2          ) = Chemical("H2          ",   2.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(H2O2        ) = Chemical("H2O2        ",  34.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(HONO        ) = Chemical("HONO        ",  47.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(HNO3        ) = Chemical("HNO3        ",  63.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(HO2NO2      ) = Chemical("HO2NO2      ",  79.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(CO          ) = Chemical("CO          ",  28.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(CH4         ) = Chemical("CH4         ",  16.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(C2H6        ) = Chemical("C2H6        ",  30.0000,  1,   2.0000,   0.0000,   0.0000 )
    species(NC4H10      ) = Chemical("NC4H10      ",  58.0000,  1,   4.0000,   0.0000,   0.0000 )
    species(C2H4        ) = Chemical("C2H4        ",  28.0000,  1,   2.0000,   0.0000,   0.0000 )
    species(C3H6        ) = Chemical("C3H6        ",  42.0000,  1,   3.0000,   0.0000,   0.0000 )
    species(BENZENE     ) = Chemical("BENZENE     ",  78.0000,  1,   6.0000,   0.0000,   0.0000 )
    species(TOLUENE     ) = Chemical("TOLUENE     ",  92.0000,  1,   7.0000,   0.0000,   0.0000 )
    species(OXYL        ) = Chemical("OXYL        ", 106.0000,  1,   8.0000,   0.0000,   0.0000 )
    species(C5H8        ) = Chemical("C5H8        ",  68.0000,  1,   5.0000,   0.0000,   0.0000 )
    species(CH3OH       ) = Chemical("CH3OH       ",  32.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(C2H5OH      ) = Chemical("C2H5OH      ",  46.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(OXYLOL      ) = Chemical("OXYLOL      ", 122.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(OXYCATECH   ) = Chemical("OXYCATECH   ", 138.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(HCHO        ) = Chemical("HCHO        ",  30.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(CH3CHO      ) = Chemical("CH3CHO      ",  44.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(MACR        ) = Chemical("MACR        ",  70.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MEK         ) = Chemical("MEK         ",  72.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MVK         ) = Chemical("MVK         ",  70.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(HOCH2CHO    ) = Chemical("HOCH2CHO    ",  60.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(HCOCH2OOH   ) = Chemical("HCOCH2OOH   ",  76.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(ACETOL      ) = Chemical("ACETOL      ",  74.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(GLYOX       ) = Chemical("GLYOX       ",  58.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(MGLYOX      ) = Chemical("MGLYOX      ",  72.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(EGLYOX      ) = Chemical("EGLYOX      ",  86.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(CO2H3CHO    ) = Chemical("CO2H3CHO    ", 102.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(CO23C3CHO   ) = Chemical("CO23C3CHO   ", 100.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(BIACET      ) = Chemical("BIACET      ",  86.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(BIACETOH    ) = Chemical("BIACETOH    ", 102.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(C5DICARB    ) = Chemical("C5DICARB    ",  98.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(BZFUONE     ) = Chemical("BZFUONE     ",  84.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(HOCH2CO2H   ) = Chemical("HOCH2CO2H   ",  76.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(CH3COCO2H   ) = Chemical("CH3COCO2H   ",  88.0000,  0,   3.0000,   0.0000,   0.0000 )
    species(MACO2H      ) = Chemical("MACO2H      ",  86.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(CH3OOH      ) = Chemical("CH3OOH      ",  48.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(C2H5OOH     ) = Chemical("C2H5OOH     ",  62.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(BURO2H      ) = Chemical("BURO2H      ",  90.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(DM123OOH    ) = Chemical("DM123OOH    ", 138.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(ETRO2H      ) = Chemical("ETRO2H      ",  78.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(MEKO2H      ) = Chemical("MEKO2H      ", 104.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(ISRO2H      ) = Chemical("ISRO2H      ", 118.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(C5DICAROOH  ) = Chemical("C5DICAROOH  ", 147.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(OCATEC1OOH  ) = Chemical("OCATEC1OOH  ", 154.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(HPALD       ) = Chemical("HPALD       ", 116.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(MVKO2H      ) = Chemical("MVKO2H      ", 120.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(MACROOH     ) = Chemical("MACROOH     ", 120.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(OXYBPEROOH  ) = Chemical("OXYBPEROOH  ", 188.0000,  0,   8.0000,   0.0000,   0.0000 )
    species(CH3CO3H     ) = Chemical("CH3CO3H     ",  76.0000,  0,   2.0000,   0.0000,   0.0000 )
    species(CO2H3CO3H   ) = Chemical("CO2H3CO3H   ", 134.0000,  0,   4.0000,   0.0000,   0.0000 )
    species(IEPOX       ) = Chemical("IEPOX       ", 118.0000,  0,   5.0000,   0.0000,   0.0000 )
    species(SC4H9NO3    ) = Chemical("SC4H9NO3    ", 119.0000,  0,   4.0000,   1.0000,   0.0000 )
    species(MVKNO3      ) = Chemical("MVKNO3      ", 149.0000,  0,   4.0000,   1.0000,   0.0000 )
    species(OXY1OHNO2   ) = Chemical("OXY1OHNO2   ", 167.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(OXNCATECH   ) = Chemical("OXNCATECH   ", 183.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(NOXYOL1OOH  ) = Chemical("NOXYOL1OOH  ", 183.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(CO2N3CHO    ) = Chemical("CO2N3CHO    ", 159.0000,  0,   5.0000,   1.0000,   0.0000 )
    species(NALD        ) = Chemical("NALD        ", 105.0000,  0,   2.0000,   1.0000,   0.0000 )
    species(NOA         ) = Chemical("NOA         ", 119.0000,  0,   3.0000,   1.0000,   0.0000 )
    species(ISON        ) = Chemical("ISON        ", 147.0000,  0,   5.0000,   1.0000,   0.0000 )
    species(ISON2       ) = Chemical("ISON2       ", 145.0000,  0,   5.0000,   1.0000,   0.0000 )
    species(NC4MDCO2H   ) = Chemical("NC4MDCO2H   ", 159.0000,  0,   5.0000,   1.0000,   0.0000 )
    species(NOXYOLOOH   ) = Chemical("NOXYOLOOH   ", 249.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(OXNCATCOOH  ) = Chemical("OXNCATCOOH  ", 265.0000,  0,   8.0000,   1.0000,   0.0000 )
    species(PAN         ) = Chemical("PAN         ", 121.0000,  0,   2.0000,   1.0000,   0.0000 )
    species(PHAN        ) = Chemical("PHAN        ", 137.0000,  0,   2.0000,   1.0000,   0.0000 )
    species(PPN         ) = Chemical("PPN         ", 135.0000,  0,   3.0000,   1.0000,   0.0000 )
    species(MPAN        ) = Chemical("MPAN        ", 132.0000,  0,   4.0000,   1.0000,   0.0000 )
    species(C4PAN6      ) = Chemical("C4PAN6      ", 179.0000,  0,   4.0000,   1.0000,   0.0000 )
    species(C5PAN18     ) = Chemical("C5PAN18     ", 222.0000,  0,   5.0000,   2.0000,   0.0000 )
    species(OXNNCATOOH  ) = Chemical("OXNNCATOOH  ", 310.0000,  0,   8.0000,   2.0000,   0.0000 )
    species(APINENE     ) = Chemical("APINENE     ", 136.0000,  1,  10.0000,   0.0000,   0.0000 )
    species(TERPOOH     ) = Chemical("TERPOOH     ", 186.0000,  0,  10.0000,   0.0000,   0.0000 )
    species(SO2         ) = Chemical("SO2         ",  64.0000,  0,   0.0000,   0.0000,   1.0000 )
    species(shipNOx     ) = Chemical("shipNOx     ",  46.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(Dust_road_f ) = Chemical("Dust_road_f ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_road_c ) = Chemical("Dust_road_c ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_wb_f   ) = Chemical("Dust_wb_f   ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_wb_c   ) = Chemical("Dust_wb_c   ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_sah_f  ) = Chemical("Dust_sah_f  ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Dust_sah_c  ) = Chemical("Dust_sah_c  ", 200.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(SQT_SOA_NV  ) = Chemical("SQT_SOA_NV  ", 302.0000,  0,  14.0000,   0.0000,   0.0000 )
    species(ASOC_ng1e2  ) = Chemical("ASOC_ng1e2  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug1    ) = Chemical("ASOC_ug1    ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug10   ) = Chemical("ASOC_ug10   ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug1e2  ) = Chemical("ASOC_ug1e2  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ASOC_ug1e3  ) = Chemical("ASOC_ug1e3  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(non_C_ASOA_ng1e2) = Chemical("non_C_ASOA_ng1e2",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_ASOA_ug1) = Chemical("non_C_ASOA_ug1",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_ASOA_ug10) = Chemical("non_C_ASOA_ug10",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_ASOA_ug1e2) = Chemical("non_C_ASOA_ug1e2",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_ASOA_ug1e3) = Chemical("non_C_ASOA_ug1e3",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(BSOC_ng1e2  ) = Chemical("BSOC_ng1e2  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug1    ) = Chemical("BSOC_ug1    ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug10   ) = Chemical("BSOC_ug10   ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug1e2  ) = Chemical("BSOC_ug1e2  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(BSOC_ug1e3  ) = Chemical("BSOC_ug1e3  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(non_C_BSOA_ng1e2) = Chemical("non_C_BSOA_ng1e2",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_BSOA_ug1) = Chemical("non_C_BSOA_ug1",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_BSOA_ug10) = Chemical("non_C_BSOA_ug10",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_BSOA_ug1e2) = Chemical("non_C_BSOA_ug1e2",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(non_C_BSOA_ug1e3) = Chemical("non_C_BSOA_ug1e3",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(SO4         ) = Chemical("SO4         ",  96.0000,  0,   0.0000,   0.0000,   1.0000 )
    species(NH3         ) = Chemical("NH3         ",  17.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NO3_f       ) = Chemical("NO3_f       ",  62.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NO3_c       ) = Chemical("NO3_c       ",  62.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(NH4_f       ) = Chemical("NH4_f       ",  18.0000,  0,   0.0000,   1.0000,   0.0000 )
    species(OM25_bgnd   ) = Chemical("OM25_bgnd   ",  24.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(OM25_p      ) = Chemical("OM25_p      ",   1.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(ffire_OM    ) = Chemical("ffire_OM    ",  20.4000,  0,   1.0000,   0.0000,   0.0000 )
    species(ffire_BC    ) = Chemical("ffire_BC    ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(ffire_remPPM25) = Chemical("ffire_remPPM25",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(ffire_c     ) = Chemical("ffire_c     ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(SeaSalt_f   ) = Chemical("SeaSalt_f   ",  58.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(SeaSalt_c   ) = Chemical("SeaSalt_c   ",  58.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Ash_f       ) = Chemical("Ash_f       ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(Ash_c       ) = Chemical("Ash_c       ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(POM_f_wood  ) = Chemical("POM_f_wood  ",  20.4000,  0,   1.0000,   0.0000,   0.0000 )
    species(POM_c_wood  ) = Chemical("POM_c_wood  ",  20.4000,  0,   1.0000,   0.0000,   0.0000 )
    species(POM_f_ffuel ) = Chemical("POM_f_ffuel ",  15.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(POM_c_ffuel ) = Chemical("POM_c_ffuel ",  15.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_wood_new) = Chemical("EC_f_wood_new",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_wood_age) = Chemical("EC_f_wood_age",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_c_wood   ) = Chemical("EC_c_wood   ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_ffuel_new) = Chemical("EC_f_ffuel_new",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_f_ffuel_age) = Chemical("EC_f_ffuel_age",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(EC_c_ffuel  ) = Chemical("EC_c_ffuel  ",  12.0000,  0,   1.0000,   0.0000,   0.0000 )
    species(pSO4f       ) = Chemical("pSO4f       ",  96.0000,  0,   0.0000,   0.0000,   1.0000 )
    species(pSO4c       ) = Chemical("pSO4c       ",  96.0000,  0,   0.0000,   0.0000,   1.0000 )
    species(remPPM25    ) = Chemical("remPPM25    ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
    species(remPPM_c    ) = Chemical("remPPM_c    ",  12.0000,  0,   0.0000,   0.0000,   0.0000 )
  end subroutine define_chemicals

end module ChemSpecs_mod
