! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem19X PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis
module ChemGroups_mod

  use ChemSpecs_mod        ! => species indices
  use OwnDataTypes_mod  ! => typ_sp, typ_factors, typ_maps
  
  implicit none
  private
  character(len=*),parameter, public :: CM_schemes_ChemGroups = " EmChem19X PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis"
  
  
  ! Assignment of groups from GenIn_Species.csv
  public :: Init_ChemGroups
  
  type(typ_sp), dimension(418), public, save :: chemgroups
  type(typ_factors), dimension(2), public, save :: chemgroups_factors
  type(typ_maps), dimension(1), public, save :: chemgroups_maps
  
  integer, public, target, save, dimension (29) :: &
    RO2_GROUP = (/  &
      CH3O2, C2H5O2, C4H9O2, ISRO2, HCOCH2O2, ETRO2, PRRO2,  &
      HMVKO2, OXYBIPERO2, MACO3, MEKO2, C5DICARBO2, DM123O2,  &
      OXCATEC1O2, CH2O2CO3H, MACRO2, HOCH2CO3, CH3CO3, C2H5CO3,  &
      CO2H3CO3, IBUTOLBO2, NRN9O2, NISOPO2, NC4CO3, NOXYOLO2,  &
      OXNCATECO2, OXNNCATCO2, NOXYOL1O2, TERPO2  &
    /)
  
  integer, public, target, save, dimension (38) :: &
    OXN_GROUP = (/  &
      NRN9O2, NISOPO2, NC4CO3, NOXYOLO2, OXNCATECO2, OXNNCATCO2,  &
      NOXYOL1O2, NOXYOL1O, NO, NO2, NO3, N2O5, HONO, HNO3,  &
      HO2NO2, SC4H9NO3, MVKNO3, OXY1OHNO2, OXNCATECH, NOXYOL1OOH,  &
      CO2N3CHO, NALD, NOA, ISON, ISON2, NC4MDCO2H, NOXYOLOOH,  &
      OXNCATCOOH, PAN, PHAN, PPN, MPAN, C4PAN6, C5PAN18,  &
      OXNNCATOOH, NO3_f, NO3_c, shipNOx  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    DAOBS_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DAOBS_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    OX_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_OX_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (3) :: &
    NOX_GROUP = (/ NO, NO2, shipNOx /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_NOX_GROUP = (/ NO2, shipNOx /)
  
  integer, public, target, save, dimension (27) :: &
    DDEP_OXN_GROUP = (/  &
      NO2, N2O5, HONO, HNO3, HO2NO2, SC4H9NO3, MVKNO3, OXNCATECH,  &
      NOXYOL1OOH, CO2N3CHO, NALD, NOA, ISON, ISON2, NC4MDCO2H,  &
      NOXYOLOOH, OXNCATCOOH, PAN, PHAN, PPN, MPAN, C4PAN6,  &
      C5PAN18, OXNNCATOOH, NO3_f, NO3_c, shipNOx  &
    /)
  
  integer, public, target, save, dimension (20) :: &
    WDEP_OXN_GROUP = (/  &
      N2O5, HONO, HNO3, HO2NO2, MVKNO3, OXNCATECH, NOXYOL1OOH,  &
      CO2N3CHO, NALD, NOA, ISON, ISON2, NC4MDCO2H, NOXYOLOOH,  &
      OXNCATCOOH, C4PAN6, C5PAN18, OXNNCATOOH, NO3_f, NO3_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P0E5_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P0E5_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P0E5_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (2) :: &
    F0_1P0_GROUP = (/ H2O2, HO2NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_F0_1P0_GROUP = (/ H2O2, HO2NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_F0_1P0_GROUP = (/ H2O2, HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P36_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_1P36_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P36_GROUP = (/ H2O2 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P6E5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P6E5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P6E5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (4) :: &
    F0_0P5_GROUP = (/ HONO, PAN, PHAN, PPN /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_F0_0P5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_F0_0P5_GROUP = (/ HONO, PAN, PHAN, PPN /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_1P6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P0E4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_6P0E4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_6P0E4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_2P1_GROUP = (/ HO2NO2, CH3CHO, GLYOX /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_2P1_GROUP = (/ HO2NO2, GLYOX /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_2P1_GROUP = (/ HO2NO2, CH3CHO, GLYOX /)
  
  integer, public, target, save, dimension (2) :: &
    BVOC_GROUP = (/ C5H8, APINENE /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_9P4E2_GROUP = (/ OXYLOL /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_3P6_GROUP = (/ OXYLOL, ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P76_GROUP = (/ OXYCATECH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P76_GROUP = (/ OXYCATECH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P76_GROUP = (/ OXYCATECH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P1E7_GROUP = (/ OXYCATECH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P1E7_GROUP = (/ OXYCATECH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P1E7_GROUP = (/ OXYCATECH /)
  
  integer, public, target, save, dimension (18) :: &
    RCHO_GROUP = (/  &
      HCHO, CH3CHO, MACR, HOCH2CHO, HCOCH2OOH, GLYOX, MGLYOX,  &
      EGLYOX, CO2H3CHO, CO23C3CHO, C5DICARB, C5DICAROOH, HPALD,  &
      MACROOH, CO2N3CHO, NALD, ISON2, NC4MDCO2H  &
    /)
  
  integer, public, target, save, dimension (16) :: &
    WDEP_RCHO_GROUP = (/  &
      HCHO, HOCH2CHO, HCOCH2OOH, GLYOX, MGLYOX, EGLYOX, CO2H3CHO,  &
      CO23C3CHO, C5DICARB, C5DICAROOH, HPALD, MACROOH, CO2N3CHO,  &
      NALD, ISON2, NC4MDCO2H  &
    /)
  
  integer, public, target, save, dimension (18) :: &
    DDEP_RCHO_GROUP = (/  &
      HCHO, CH3CHO, MACR, HOCH2CHO, HCOCH2OOH, GLYOX, MGLYOX,  &
      EGLYOX, CO2H3CHO, CO23C3CHO, C5DICARB, C5DICAROOH, HPALD,  &
      MACROOH, CO2N3CHO, NALD, ISON2, NC4MDCO2H  &
    /)
  
  integer, public, target, save, dimension (30) :: &
    CARBONYL_GROUP = (/  &
      HCHO, CH3CHO, MACR, MEK, MVK, HOCH2CHO, HCOCH2OOH, ACETOL,  &
      GLYOX, MGLYOX, EGLYOX, CO2H3CHO, CO23C3CHO, BIACET,  &
      BIACETOH, C5DICARB, BZFUONE, CH3COCO2H, MEKO2H, C5DICAROOH,  &
      HPALD, MVKO2H, MACROOH, CO2H3CO3H, MVKNO3, CO2N3CHO, NALD,  &
      NOA, ISON2, NC4MDCO2H  &
    /)
  
  integer, public, target, save, dimension (24) :: &
    WDEP_CARBONYL_GROUP = (/  &
      HCHO, HOCH2CHO, HCOCH2OOH, ACETOL, GLYOX, MGLYOX, EGLYOX,  &
      CO2H3CHO, CO23C3CHO, BIACETOH, C5DICARB, CH3COCO2H, MEKO2H,  &
      C5DICAROOH, HPALD, MVKO2H, MACROOH, CO2H3CO3H, MVKNO3,  &
      CO2N3CHO, NALD, NOA, ISON2, NC4MDCO2H  &
    /)
  
  integer, public, target, save, dimension (30) :: &
    DDEP_CARBONYL_GROUP = (/  &
      HCHO, CH3CHO, MACR, MEK, MVK, HOCH2CHO, HCOCH2OOH, ACETOL,  &
      GLYOX, MGLYOX, EGLYOX, CO2H3CHO, CO23C3CHO, BIACET,  &
      BIACETOH, C5DICARB, BZFUONE, CH3COCO2H, MEKO2H, C5DICAROOH,  &
      HPALD, MVKO2H, MACROOH, CO2H3CO3H, MVKNO3, CO2N3CHO, NALD,  &
      NOA, ISON2, NC4MDCO2H  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P2E3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P2E3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P2E3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (12) :: &
    F0_0P2_GROUP = (/  &
      HCHO, HCOCH2OOH, MGLYOX, EGLYOX, CH3OOH, C2H5OOH, DM123OOH,  &
      ETRO2H, OXYBPEROOH, CH3CO3H, MPAN, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (8) :: &
    WDEP_F0_0P2_GROUP = (/  &
      HCHO, HCOCH2OOH, MGLYOX, EGLYOX, ETRO2H, OXYBPEROOH,  &
      CH3CO3H, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (12) :: &
    DDEP_F0_0P2_GROUP = (/  &
      HCHO, HCOCH2OOH, MGLYOX, EGLYOX, CH3OOH, C2H5OOH, DM123OOH,  &
      ETRO2H, OXYBPEROOH, CH3CO3H, MPAN, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_1P4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P3E1_GROUP = (/ CH3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P3E1_GROUP = (/ CH3CHO /)
  
  integer, public, target, save, dimension (6) :: &
    F0_0P05_GROUP = (/ CH3CHO, MACR, MEK, MVK, ACETOL, BIACET /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_F0_0P05_GROUP = (/ CH3CHO, MACR, MEK, MVK, ACETOL, BIACET /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P0E0_GROUP = (/ MACR /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_5P0E0_GROUP = (/ MACR /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_2P6_GROUP = (/ MACR, MVK, ACETOL /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_2P6_GROUP = (/ MACR, MVK, ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P0E1_GROUP = (/ MEK /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P0E1_GROUP = (/ MEK /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_2P7_GROUP = (/ MEK, BZFUONE, NALD /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_2P7_GROUP = (/ MEK, BZFUONE, NALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P0E1_GROUP = (/ MVK /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P0E1_GROUP = (/ MVK /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_4P1E4_GROUP = (/ HOCH2CHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_4P1E4_GROUP = (/ HOCH2CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_4P1E4_GROUP = (/ HOCH2CHO /)
  
  integer, public, target, save, dimension (2) :: &
    F0_0P0_GROUP = (/ HOCH2CHO, GLYOX /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_F0_0P0_GROUP = (/ HOCH2CHO, GLYOX /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_F0_0P0_GROUP = (/ HOCH2CHO, GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P2_GROUP = (/ HOCH2CHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P2_GROUP = (/ HOCH2CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_2P2_GROUP = (/ HOCH2CHO /)
  
  integer, public, target, save, dimension (19) :: &
    ROOH_GROUP = (/  &
      HCOCH2OOH, CH3OOH, C2H5OOH, BURO2H, DM123OOH, ETRO2H,  &
      MEKO2H, ISRO2H, C5DICAROOH, OCATEC1OOH, HPALD, MVKO2H,  &
      MACROOH, OXYBPEROOH, NOXYOL1OOH, NOXYOLOOH, OXNCATCOOH,  &
      OXNNCATOOH, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (15) :: &
    WDEP_ROOH_GROUP = (/  &
      HCOCH2OOH, ETRO2H, MEKO2H, ISRO2H, C5DICAROOH, OCATEC1OOH,  &
      HPALD, MVKO2H, MACROOH, OXYBPEROOH, NOXYOL1OOH, NOXYOLOOH,  &
      OXNCATCOOH, OXNNCATOOH, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (19) :: &
    DDEP_ROOH_GROUP = (/  &
      HCOCH2OOH, CH3OOH, C2H5OOH, BURO2H, DM123OOH, ETRO2H,  &
      MEKO2H, ISRO2H, C5DICAROOH, OCATEC1OOH, HPALD, MVKO2H,  &
      MACROOH, OXYBPEROOH, NOXYOL1OOH, NOXYOLOOH, OXNCATCOOH,  &
      OXNNCATOOH, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P2E4_GROUP = (/ HCOCH2OOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P2E4_GROUP = (/ HCOCH2OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P2E4_GROUP = (/ HCOCH2OOH /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P4_GROUP = (/ HCOCH2OOH, CH3CO3H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_2P4_GROUP = (/ HCOCH2OOH, CH3CO3H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_2P4_GROUP = (/ HCOCH2OOH, CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P0E3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_8P0E3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_8P0E3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_F0_0P05_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P6_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P0E5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P0E5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P0E5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P4E4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P4E4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P4E4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_2P5_GROUP = (/ MGLYOX, HOCH2CO2H, ETRO2H /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_DRX_2P5_GROUP = (/ MGLYOX, HOCH2CO2H, ETRO2H /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_2P5_GROUP = (/ MGLYOX, HOCH2CO2H, ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P8E3_GROUP = (/ EGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P8E3_GROUP = (/ EGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P8E3_GROUP = (/ EGLYOX /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_2P8_GROUP = (/ EGLYOX, BIACET, PAN /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P8_GROUP = (/ EGLYOX /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_2P8_GROUP = (/ EGLYOX, BIACET, PAN /)
  
  integer, public, target, save, dimension (5) :: &
    DRX_3P0_GROUP = (/ CO2H3CHO, BIACETOH, BURO2H, NOA, PHAN /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_DRX_3P0_GROUP = (/ CO2H3CHO, BIACETOH, NOA /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_DRX_3P0_GROUP = (/ CO2H3CHO, BIACETOH, BURO2H, NOA, PHAN /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P4E5_GROUP = (/ CO2H3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P4E5_GROUP = (/ CO2H3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P4E5_GROUP = (/ CO2H3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P9_GROUP = (/ CO23C3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P9_GROUP = (/ CO23C3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_2P9_GROUP = (/ CO23C3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_9P3E5_GROUP = (/ CO23C3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_9P3E5_GROUP = (/ CO23C3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_9P3E5_GROUP = (/ CO23C3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_7P3E1_GROUP = (/ BIACET /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_7P3E1_GROUP = (/ BIACET /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P2E4_GROUP = (/ BIACETOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P2E4_GROUP = (/ BIACETOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P2E4_GROUP = (/ BIACETOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P0E5_GROUP = (/ C5DICARB /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_6P0E5_GROUP = (/ C5DICARB /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_6P0E5_GROUP = (/ C5DICARB /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_3P1_GROUP = (/ C5DICARB, MEKO2H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_3P1_GROUP = (/ C5DICARB, MEKO2H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRX_3P1_GROUP = (/ C5DICARB, MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P0E2_GROUP = (/ BZFUONE /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P0E2_GROUP = (/ BZFUONE /)
  
  integer, public, target, save, dimension (3) :: &
    ACID_GROUP = (/ HOCH2CO2H, CH3COCO2H, MACO2H /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_ACID_GROUP = (/ HOCH2CO2H, CH3COCO2H, MACO2H /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_ACID_GROUP = (/ HOCH2CO2H, CH3COCO2H, MACO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_4P2E7_GROUP = (/ HOCH2CO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_4P2E7_GROUP = (/ HOCH2CO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_4P2E7_GROUP = (/ HOCH2CO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P3E10_GROUP = (/ CH3COCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P3E10_GROUP = (/ CH3COCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P3E10_GROUP = (/ CH3COCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P0E2_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P0E2_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P9_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_1P9_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (2) :: &
    HSTAR_3P3E2_GROUP = (/ C2H5OOH, DM123OOH /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_HSTAR_3P3E2_GROUP = (/ C2H5OOH, DM123OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P3_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_2P3_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P2E1_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_6P2E1_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P75_GROUP = (/ DM123OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P75_GROUP = (/ DM123OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P3E6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P3E6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P3E6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_9P0E4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_9P0E4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_9P0E4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P6E8_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P6E8_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P6E8_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P55_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P55_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P55_GROUP = (/ C5DICAROOH /)
  
  integer, public, target, save, dimension (6) :: &
    F0_0P3_GROUP = (/ C5DICAROOH, SC4H9NO3, MVKNO3, NOA, ISON, ISON2 /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_F0_0P3_GROUP = (/ C5DICAROOH, MVKNO3, NOA, ISON, ISON2 /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_F0_0P3_GROUP = (/ C5DICAROOH, SC4H9NO3, MVKNO3, NOA, ISON, ISON2 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P1E6_GROUP = (/ OCATEC1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P1E6_GROUP = (/ OCATEC1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P1E6_GROUP = (/ OCATEC1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P88_GROUP = (/ OCATEC1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P88_GROUP = (/ OCATEC1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P88_GROUP = (/ OCATEC1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P2E5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P2E5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P2E5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_3P3_GROUP = (/ HPALD, CO2H3CO3H, SC4H9NO3 /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_3P3_GROUP = (/ HPALD, CO2H3CO3H /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_3P3_GROUP = (/ HPALD, CO2H3CO3H, SC4H9NO3 /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_3P2_GROUP = (/ MVKO2H, MACROOH, PPN /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_3P2_GROUP = (/ MVKO2H, MACROOH /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_3P2_GROUP = (/ MVKO2H, MACROOH, PPN /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_4P4E8_GROUP = (/ MVKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_4P4E8_GROUP = (/ MVKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_4P4E8_GROUP = (/ MVKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P5E8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P5E8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P5E8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P4E8_GROUP = (/ OXYBPEROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P4E8_GROUP = (/ OXYBPEROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P4E8_GROUP = (/ OXYBPEROOH /)
  
  integer, public, target, save, dimension (4) :: &
    DRX_4P1_GROUP = (/ OXYBPEROOH, OXNCATECH, NOXYOL1OOH, C5PAN18 /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_DRX_4P1_GROUP = (/ OXYBPEROOH, OXNCATECH, NOXYOL1OOH, C5PAN18 /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_DRX_4P1_GROUP = (/ OXYBPEROOH, OXNCATECH, NOXYOL1OOH, C5PAN18 /)
  
  integer, public, target, save, dimension (2) :: &
    PEROXYACID_GROUP = (/ CH3CO3H, CO2H3CO3H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_PEROXYACID_GROUP = (/ CH3CO3H, CO2H3CO3H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_PEROXYACID_GROUP = (/ CH3CO3H, CO2H3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P3E2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_8P3E2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_8P3E2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P8E6_GROUP = (/ CO2H3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_6P8E6_GROUP = (/ CO2H3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_6P8E6_GROUP = (/ CO2H3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    EPOXIDE_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_EPOXIDE_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_EPOXIDE_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_0P0E0_GROUP = (/ SC4H9NO3 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_0P0E0_GROUP = (/ SC4H9NO3 /)
  
  integer, public, target, save, dimension (1) :: &
    NITRATE_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NITRATE_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NITRATE_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    ORGNO3_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_ORGNO3_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_ORGNO3_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P5E8_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P5E8_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P5E8_GROUP = (/ MVKNO3 /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_3P4_GROUP = (/ MVKNO3, CO2N3CHO, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRX_3P4_GROUP = (/ MVKNO3, CO2N3CHO /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRX_3P4_GROUP = (/ MVKNO3, CO2N3CHO, MPAN /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_7P0E1_GROUP = (/ OXY1OHNO2 /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_4P0_GROUP = (/ OXY1OHNO2 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P3E4_GROUP = (/ NOXYOL1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_8P3E4_GROUP = (/ NOXYOL1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_8P3E4_GROUP = (/ NOXYOL1OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P1E6_GROUP = (/ CO2N3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_8P1E6_GROUP = (/ CO2N3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_8P1E6_GROUP = (/ CO2N3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P5E3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_5P5E3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_5P5E3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_2P7_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P0E3_GROUP = (/ NOA /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P0E3_GROUP = (/ NOA /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P0E3_GROUP = (/ NOA /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P0E4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_5P0E4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_5P0E4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_4P2E3_GROUP = (/ ISON2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_4P2E3_GROUP = (/ ISON2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_4P2E3_GROUP = (/ ISON2 /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P5_GROUP = (/ ISON2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P5_GROUP = (/ ISON2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P5_GROUP = (/ ISON2 /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P77_GROUP = (/ NC4MDCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P77_GROUP = (/ NC4MDCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P77_GROUP = (/ NC4MDCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P1E9_GROUP = (/ NC4MDCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_3P1E9_GROUP = (/ NC4MDCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_3P1E9_GROUP = (/ NC4MDCO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P0E13_GROUP = (/ OXNCATCOOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P0E13_GROUP = (/ OXNCATCOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P0E13_GROUP = (/ OXNCATCOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_4P7_GROUP = (/ OXNCATCOOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_4P7_GROUP = (/ OXNCATCOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_4P7_GROUP = (/ OXNCATCOOH /)
  
  integer, public, target, save, dimension (6) :: &
    PANS_GROUP = (/ PAN, PHAN, PPN, MPAN, C4PAN6, C5PAN18 /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_PANS_GROUP = (/ PAN, PHAN, PPN, MPAN, C4PAN6, C5PAN18 /)
  
  integer, public, target, save, dimension (2) :: &
    HSTAR_3P0E0_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_HSTAR_3P0E0_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P5E1_GROUP = (/ PHAN /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_5P5E1_GROUP = (/ PHAN /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P9E0_GROUP = (/ PPN /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P9E0_GROUP = (/ PPN /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_PANS_GROUP = (/ C4PAN6, C5PAN18 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P1E4_GROUP = (/ C4PAN6 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_8P1E4_GROUP = (/ C4PAN6 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_8P1E4_GROUP = (/ C4PAN6 /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P65_GROUP = (/ C4PAN6 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_3P65_GROUP = (/ C4PAN6 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_3P65_GROUP = (/ C4PAN6 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P4E3_GROUP = (/ C5PAN18 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P4E3_GROUP = (/ C5PAN18 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P4E3_GROUP = (/ C5PAN18 /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P7E14_GROUP = (/ OXNNCATOOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_2P7E14_GROUP = (/ OXNNCATOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_2P7E14_GROUP = (/ OXNNCATOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_4P95_GROUP = (/ OXNNCATOOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_4P95_GROUP = (/ OXNNCATOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_4P95_GROUP = (/ OXNNCATOOH /)
  
  integer, public, target, save, dimension (1) :: &
    MONOTERP_GROUP = (/ APINENE /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P5E6_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_HSTAR_1P5E6_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_HSTAR_1P5E6_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_4P5_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRX_4P5_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRX_4P5_GROUP = (/ TERPOOH /)
  
  integer, public, target, save, dimension (4) :: &
    SOX_GROUP = (/ SO2, SO4, pSO4f, pSO4c /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_SOX_GROUP = (/ SO2, SO4, pSO4f, pSO4c /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_SOX_GROUP = (/ SO2, SO4, pSO4f, pSO4c /)
  
  integer, public, target, save, dimension (30) :: &
    PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, OM25_p, ffire_BC, ffire_remPPM25,  &
      ffire_c, SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c,  &
      Dust_wb_f, Dust_wb_c, Dust_sah_f, Dust_sah_c, Ash_f, Ash_c,  &
      POM_c_wood, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      pSO4f, pSO4c, remPPM25, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    WDEP_PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, ffire_BC, ffire_remPPM25, ffire_c,  &
      SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c, Dust_wb_f,  &
      Dust_wb_c, Dust_sah_f, Dust_sah_c, Ash_f, Ash_c,  &
      POM_c_wood, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      pSO4f, pSO4c, remPPM25, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    DDEP_PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, ffire_BC, ffire_remPPM25, ffire_c,  &
      SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c, Dust_wb_f,  &
      Dust_wb_c, Dust_sah_f, Dust_sah_c, Ash_f, Ash_c,  &
      POM_c_wood, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      pSO4f, pSO4c, remPPM25, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (17) :: &
    PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, OM25_p, ffire_BC, ffire_remPPM25,  &
      SeaSalt_f, Dust_road_f, Dust_wb_f, Dust_sah_f, Ash_f,  &
      EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (16) :: &
    WDEP_PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, ffire_BC, ffire_remPPM25, SeaSalt_f,  &
      Dust_road_f, Dust_wb_f, Dust_sah_f, Ash_f, EC_f_wood_new,  &
      EC_f_wood_age, EC_f_ffuel_new, EC_f_ffuel_age, pSO4f,  &
      remPPM25  &
    /)
  
  integer, public, target, save, dimension (16) :: &
    DDEP_PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, ffire_BC, ffire_remPPM25, SeaSalt_f,  &
      Dust_road_f, Dust_wb_f, Dust_sah_f, Ash_f, EC_f_wood_new,  &
      EC_f_wood_age, EC_f_ffuel_new, EC_f_ffuel_age, pSO4f,  &
      remPPM25  &
    /)
  
  integer, public, target, save, dimension (4) :: &
    SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    TNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_TNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_TNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (11) :: &
    PMCOARSE_GROUP = (/  &
      NO3_c, ffire_c, SeaSalt_c, Dust_road_c, Dust_wb_c,  &
      Dust_sah_c, Ash_c, POM_c_wood, POM_c_ffuel, pSO4c, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    WDEP_PMCOARSE_GROUP = (/  &
      NO3_c, ffire_c, SeaSalt_c, Dust_road_c, Dust_wb_c,  &
      Dust_sah_c, Ash_c, POM_c_wood, POM_c_ffuel, pSO4c, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_PMCOARSE_GROUP = (/  &
      NO3_c, ffire_c, SeaSalt_c, Dust_road_c, Dust_wb_c,  &
      Dust_sah_c, Ash_c, POM_c_wood, POM_c_ffuel, pSO4c, remPPM_c  &
    /)
  
  integer, public, target, save, dimension (25) :: &
    OM25_GROUP = (/  &
      OM25_bgnd, ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2,  &
      ASOC_ug1e3, non_C_ASOA_ng1e2, non_C_ASOA_ug1,  &
      non_C_ASOA_ug10, non_C_ASOA_ug1e2, non_C_ASOA_ug1e3,  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, ffire_OM, POM_f_wood,  &
      POM_f_ffuel, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    NONVOLPCM_GROUP = (/  &
      OM25_bgnd, ffire_OM, ffire_BC, POM_f_wood, POM_c_wood,  &
      POM_f_ffuel, POM_c_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_c_wood, EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel,  &
      SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    NVABSOM_GROUP = (/ OM25_bgnd, ffire_OM, POM_f_wood, POM_f_ffuel, SQT_SOA_NV /)
  
  integer, public, target, save, dimension (2) :: &
    OC_GROUP = (/ OM25_p, ffire_OM /)
  
  integer, public, target, save, dimension (24) :: &
    WDEP_OM25_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, POM_f_wood, POM_f_ffuel,  &
      SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (24) :: &
    DDEP_OM25_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, POM_f_wood, POM_f_ffuel,  &
      SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    PCM_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, ffire_BC, POM_f_wood,  &
      POM_f_ffuel, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    WDEP_PCM_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, ffire_BC, POM_f_wood,  &
      POM_f_ffuel, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    DDEP_PCM_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3, ffire_OM, ffire_BC, POM_f_wood,  &
      POM_f_ffuel, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    ASOA_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    WDEP_ASOA_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    DDEP_ASOA_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    BSOA_GROUP = (/  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    WDEP_BSOA_GROUP = (/  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_BSOA_GROUP = (/  &
      BSOC_ng1e2, BSOC_ug1, BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3,  &
      non_C_BSOA_ng1e2, non_C_BSOA_ug1, non_C_BSOA_ug10,  &
      non_C_BSOA_ug1e2, non_C_BSOA_ug1e3, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    TMPX_GROUP = (/ shipNOx /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_TMPX_GROUP = (/ shipNOx /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_OC_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_OC_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (3) :: &
    PPM25_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25 /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_PPM25_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25 /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_PPM25_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25 /)
  
  integer, public, target, save, dimension (4) :: &
    PPM10_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25, ffire_c /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_PPM10_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25, ffire_c /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_PPM10_FIRE_GROUP = (/ ffire_OM, ffire_BC, ffire_remPPM25, ffire_c /)
  
  integer, public, target, save, dimension (13) :: &
    WDEP_NONVOLPCM_GROUP = (/  &
      ffire_OM, ffire_BC, POM_f_wood, POM_c_wood, POM_f_ffuel,  &
      POM_c_ffuel, EC_f_wood_new, EC_f_wood_age, EC_c_wood,  &
      EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (13) :: &
    DDEP_NONVOLPCM_GROUP = (/  &
      ffire_OM, ffire_BC, POM_f_wood, POM_c_wood, POM_f_ffuel,  &
      POM_c_ffuel, EC_f_wood_new, EC_f_wood_age, EC_c_wood,  &
      EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel, SQT_SOA_NV  &
    /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_NVABSOM_GROUP = (/ ffire_OM, POM_f_wood, POM_f_ffuel, SQT_SOA_NV /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_NVABSOM_GROUP = (/ ffire_OM, POM_f_wood, POM_f_ffuel, SQT_SOA_NV /)
  
  integer, public, target, save, dimension (1) :: &
    FBBPOA25_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_FBBPOA25_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_FBBPOA25_GROUP = (/ ffire_OM /)
  
  integer, public, target, save, dimension (5) :: &
    EC_F_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_EC_F_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_EC_F_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    FFIREBC_GROUP = (/ ffire_BC /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_FFIREBC_GROUP = (/ ffire_BC /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_FFIREBC_GROUP = (/ ffire_BC /)
  
  integer, public, target, save, dimension (5) :: &
    ECFINE_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_ECFINE_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_ECFINE_GROUP = (/  &
      ffire_BC, EC_f_wood_new, EC_f_wood_age, EC_f_ffuel_new,  &
      EC_f_ffuel_age  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (6) :: &
    DUST_GROUP = (/  &
      Dust_road_f, Dust_road_c, Dust_wb_f, Dust_wb_c, Dust_sah_f,  &
      Dust_sah_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    WDEP_DUST_GROUP = (/  &
      Dust_road_f, Dust_road_c, Dust_wb_f, Dust_wb_c, Dust_sah_f,  &
      Dust_sah_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_DUST_GROUP = (/  &
      Dust_road_f, Dust_road_c, Dust_wb_f, Dust_wb_c, Dust_sah_f,  &
      Dust_sah_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    DUST_ANT_F_GROUP = (/ Dust_road_f /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DUST_ANT_F_GROUP = (/ Dust_road_f /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DUST_ANT_F_GROUP = (/ Dust_road_f /)
  
  integer, public, target, save, dimension (1) :: &
    DUST_ANT_C_GROUP = (/ Dust_road_c /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DUST_ANT_C_GROUP = (/ Dust_road_c /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DUST_ANT_C_GROUP = (/ Dust_road_c /)
  
  integer, public, target, save, dimension (2) :: &
    DUST_NAT_F_GROUP = (/ Dust_wb_f, Dust_sah_f /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DUST_NAT_F_GROUP = (/ Dust_wb_f, Dust_sah_f /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DUST_NAT_F_GROUP = (/ Dust_wb_f, Dust_sah_f /)
  
  integer, public, target, save, dimension (2) :: &
    DUST_NAT_C_GROUP = (/ Dust_wb_c, Dust_sah_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DUST_NAT_C_GROUP = (/ Dust_wb_c, Dust_sah_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DUST_NAT_C_GROUP = (/ Dust_wb_c, Dust_sah_c /)
  
  integer, public, target, save, dimension (2) :: &
    ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (8) :: &
    PPM25_GROUP = (/  &
      POM_f_wood, POM_f_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_f_ffuel_new, EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (8) :: &
    WDEP_PPM25_GROUP = (/  &
      POM_f_wood, POM_f_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_f_ffuel_new, EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (8) :: &
    DDEP_PPM25_GROUP = (/  &
      POM_f_wood, POM_f_ffuel, EC_f_wood_new, EC_f_wood_age,  &
      EC_f_ffuel_new, EC_f_ffuel_age, pSO4f, remPPM25  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    PPM10_GROUP = (/  &
      POM_f_wood, POM_c_wood, POM_f_ffuel, POM_c_ffuel,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    WDEP_PPM10_GROUP = (/  &
      POM_f_wood, POM_c_wood, POM_f_ffuel, POM_c_ffuel,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (14) :: &
    DDEP_PPM10_GROUP = (/  &
      POM_f_wood, POM_c_wood, POM_f_ffuel, POM_c_ffuel,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    NVWOODOC25_GROUP = (/ POM_f_wood /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVWOODOC25_GROUP = (/ POM_f_wood /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVWOODOC25_GROUP = (/ POM_f_wood /)
  
  integer, public, target, save, dimension (6) :: &
    PPM_C_GROUP = (/  &
      POM_c_wood, POM_c_ffuel, EC_c_wood, EC_c_ffuel, pSO4c,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    WDEP_PPM_C_GROUP = (/  &
      POM_c_wood, POM_c_ffuel, EC_c_wood, EC_c_ffuel, pSO4c,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_PPM_C_GROUP = (/  &
      POM_c_wood, POM_c_ffuel, EC_c_wood, EC_c_ffuel, pSO4c,  &
      remPPM_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    NVWOODOC_COARSE_GROUP = (/ POM_c_wood /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVWOODOC_COARSE_GROUP = (/ POM_c_wood /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVWOODOC_COARSE_GROUP = (/ POM_c_wood /)
  
  integer, public, target, save, dimension (2) :: &
    OMCOARSE_GROUP = (/ POM_c_wood, POM_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_OMCOARSE_GROUP = (/ POM_c_wood, POM_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_OMCOARSE_GROUP = (/ POM_c_wood, POM_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    NVFFUELOC25_GROUP = (/ POM_f_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVFFUELOC25_GROUP = (/ POM_f_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVFFUELOC25_GROUP = (/ POM_f_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    PM10ANTHR_GROUP = (/ POM_c_ffuel, EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_PM10ANTHR_GROUP = (/ POM_c_ffuel, EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_PM10ANTHR_GROUP = (/ POM_c_ffuel, EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    NVFFUELOC_COARSE_GROUP = (/ POM_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVFFUELOC_COARSE_GROUP = (/ POM_c_ffuel /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVFFUELOC_COARSE_GROUP = (/ POM_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    WOODEC_GROUP = (/ EC_f_wood_new, EC_f_wood_age, EC_c_wood /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_WOODEC_GROUP = (/ EC_f_wood_new, EC_f_wood_age, EC_c_wood /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_WOODEC_GROUP = (/ EC_f_wood_new, EC_f_wood_age, EC_c_wood /)
  
  integer, public, target, save, dimension (2) :: &
    WOODECFINE_GROUP = (/ EC_f_wood_new, EC_f_wood_age /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_WOODECFINE_GROUP = (/ EC_f_wood_new, EC_f_wood_age /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_WOODECFINE_GROUP = (/ EC_f_wood_new, EC_f_wood_age /)
  
  integer, public, target, save, dimension (2) :: &
    ECCOARSE_GROUP = (/ EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_ECCOARSE_GROUP = (/ EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_ECCOARSE_GROUP = (/ EC_c_wood, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    FFUELEC_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_FFUELEC_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_FFUELEC_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age, EC_c_ffuel /)
  
  integer, public, target, save, dimension (2) :: &
    FFUELECFINE_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_FFUELECFINE_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_FFUELECFINE_GROUP = (/ EC_f_ffuel_new, EC_f_ffuel_age /)
  
  integer, public, target, save, dimension (20) :: &
    CSTAR_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3  &
    /)
  
  real, public, target, save, dimension (20) :: &
    CSTAR_GROUP_FACTORS = (/  &
      0.1, 1.0, 10.0, 1.0e2, 1.0e3, 0.1, 1.0, 10.0, 1.0e2, 1.0e3,  &
      0.1, 1.0, 10.0, 1.0e2, 1.0e3, 0.1, 1.0, 10.0, 1.0e2, 1.0e3  &
    /)
  
  integer, public, target, save, dimension (20) :: &
    DELTAH_GROUP = (/  &
      ASOC_ng1e2, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      non_C_ASOA_ng1e2, non_C_ASOA_ug1, non_C_ASOA_ug10,  &
      non_C_ASOA_ug1e2, non_C_ASOA_ug1e3, BSOC_ng1e2, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, non_C_BSOA_ng1e2,  &
      non_C_BSOA_ug1, non_C_BSOA_ug10, non_C_BSOA_ug1e2,  &
      non_C_BSOA_ug1e3  &
    /)
  
  real, public, target, save, dimension (20) :: &
    DELTAH_GROUP_FACTORS = (/  &
      30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0,  &
      30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0  &
    /)
  
  integer, public, target, save, dimension (26) :: &
    EXTINC_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, OM25_p, ffire_BC, ffire_remPPM25,  &
      ffire_c, SeaSalt_f, SeaSalt_c, Dust_road_f, Dust_road_c,  &
      Dust_wb_f, Dust_wb_c, Dust_sah_f, Dust_sah_c,  &
      EC_f_wood_new, EC_f_wood_age, EC_c_wood, EC_f_ffuel_new,  &
      EC_f_ffuel_age, EC_c_ffuel, pSO4f, pSO4c, remPPM25,  &
      remPPM_c  &
    /)
  
  character(len=TXTLEN_SHORT), public, target, save, dimension (26) :: &
    EXTINC_GROUP_MAPBACK = [ character(len=TXTLEN_SHORT) :: &
    "SO4", "NO3f", "NO3c", "NH4f", "OC", "EC", "DDf", "DDc",  &
      "SSf", "SSc", "DDf", "DDc", "DDf", "DDc", "DDf", "DDc",  &
      "ECn", "ECa", "EC", "ECn", "ECa", "EC", "SO4", "SO4",  &
      "DDf", "DDc"  &
    ]

contains
  
  subroutine Init_ChemGroups()
    
    chemgroups(1)%name="RO2"
    chemgroups(1)%specs=>RO2_GROUP
    
    chemgroups(2)%name="OXN"
    chemgroups(2)%specs=>OXN_GROUP
    
    chemgroups(3)%name="DAOBS"
    chemgroups(3)%specs=>DAOBS_GROUP
    
    chemgroups(4)%name="DDEP_DAOBS"
    chemgroups(4)%specs=>DDEP_DAOBS_GROUP
    
    chemgroups(5)%name="OX"
    chemgroups(5)%specs=>OX_GROUP
    
    chemgroups(6)%name="DDEP_OX"
    chemgroups(6)%specs=>DDEP_OX_GROUP
    
    chemgroups(7)%name="NOX"
    chemgroups(7)%specs=>NOX_GROUP
    
    chemgroups(8)%name="DDEP_NOX"
    chemgroups(8)%specs=>DDEP_NOX_GROUP
    
    chemgroups(9)%name="DDEP_OXN"
    chemgroups(9)%specs=>DDEP_OXN_GROUP
    
    chemgroups(10)%name="WDEP_OXN"
    chemgroups(10)%specs=>WDEP_OXN_GROUP
    
    chemgroups(11)%name="HSTAR_1P0E5"
    chemgroups(11)%specs=>HSTAR_1P0E5_GROUP
    
    chemgroups(12)%name="WDEP_HSTAR_1P0E5"
    chemgroups(12)%specs=>WDEP_HSTAR_1P0E5_GROUP
    
    chemgroups(13)%name="DDEP_HSTAR_1P0E5"
    chemgroups(13)%specs=>DDEP_HSTAR_1P0E5_GROUP
    
    chemgroups(14)%name="F0_1P0"
    chemgroups(14)%specs=>F0_1P0_GROUP
    
    chemgroups(15)%name="WDEP_F0_1P0"
    chemgroups(15)%specs=>WDEP_F0_1P0_GROUP
    
    chemgroups(16)%name="DDEP_F0_1P0"
    chemgroups(16)%specs=>DDEP_F0_1P0_GROUP
    
    chemgroups(17)%name="DRX_1P36"
    chemgroups(17)%specs=>DRX_1P36_GROUP
    
    chemgroups(18)%name="WDEP_DRX_1P36"
    chemgroups(18)%specs=>WDEP_DRX_1P36_GROUP
    
    chemgroups(19)%name="DDEP_DRX_1P36"
    chemgroups(19)%specs=>DDEP_DRX_1P36_GROUP
    
    chemgroups(20)%name="HSTAR_2P6E5"
    chemgroups(20)%specs=>HSTAR_2P6E5_GROUP
    
    chemgroups(21)%name="WDEP_HSTAR_2P6E5"
    chemgroups(21)%specs=>WDEP_HSTAR_2P6E5_GROUP
    
    chemgroups(22)%name="DDEP_HSTAR_2P6E5"
    chemgroups(22)%specs=>DDEP_HSTAR_2P6E5_GROUP
    
    chemgroups(23)%name="F0_0P5"
    chemgroups(23)%specs=>F0_0P5_GROUP
    
    chemgroups(24)%name="WDEP_F0_0P5"
    chemgroups(24)%specs=>WDEP_F0_0P5_GROUP
    
    chemgroups(25)%name="DDEP_F0_0P5"
    chemgroups(25)%specs=>DDEP_F0_0P5_GROUP
    
    chemgroups(26)%name="DRX_1P6"
    chemgroups(26)%specs=>DRX_1P6_GROUP
    
    chemgroups(27)%name="WDEP_DRX_1P6"
    chemgroups(27)%specs=>WDEP_DRX_1P6_GROUP
    
    chemgroups(28)%name="DDEP_DRX_1P6"
    chemgroups(28)%specs=>DDEP_DRX_1P6_GROUP
    
    chemgroups(29)%name="HSTAR_6P0E4"
    chemgroups(29)%specs=>HSTAR_6P0E4_GROUP
    
    chemgroups(30)%name="WDEP_HSTAR_6P0E4"
    chemgroups(30)%specs=>WDEP_HSTAR_6P0E4_GROUP
    
    chemgroups(31)%name="DDEP_HSTAR_6P0E4"
    chemgroups(31)%specs=>DDEP_HSTAR_6P0E4_GROUP
    
    chemgroups(32)%name="DRX_2P1"
    chemgroups(32)%specs=>DRX_2P1_GROUP
    
    chemgroups(33)%name="WDEP_DRX_2P1"
    chemgroups(33)%specs=>WDEP_DRX_2P1_GROUP
    
    chemgroups(34)%name="DDEP_DRX_2P1"
    chemgroups(34)%specs=>DDEP_DRX_2P1_GROUP
    
    chemgroups(35)%name="BVOC"
    chemgroups(35)%specs=>BVOC_GROUP
    
    chemgroups(36)%name="HSTAR_9P4E2"
    chemgroups(36)%specs=>HSTAR_9P4E2_GROUP
    
    chemgroups(37)%name="DRX_3P6"
    chemgroups(37)%specs=>DRX_3P6_GROUP
    
    chemgroups(38)%name="DRX_3P76"
    chemgroups(38)%specs=>DRX_3P76_GROUP
    
    chemgroups(39)%name="WDEP_DRX_3P76"
    chemgroups(39)%specs=>WDEP_DRX_3P76_GROUP
    
    chemgroups(40)%name="DDEP_DRX_3P76"
    chemgroups(40)%specs=>DDEP_DRX_3P76_GROUP
    
    chemgroups(41)%name="HSTAR_1P1E7"
    chemgroups(41)%specs=>HSTAR_1P1E7_GROUP
    
    chemgroups(42)%name="WDEP_HSTAR_1P1E7"
    chemgroups(42)%specs=>WDEP_HSTAR_1P1E7_GROUP
    
    chemgroups(43)%name="DDEP_HSTAR_1P1E7"
    chemgroups(43)%specs=>DDEP_HSTAR_1P1E7_GROUP
    
    chemgroups(44)%name="RCHO"
    chemgroups(44)%specs=>RCHO_GROUP
    
    chemgroups(45)%name="WDEP_RCHO"
    chemgroups(45)%specs=>WDEP_RCHO_GROUP
    
    chemgroups(46)%name="DDEP_RCHO"
    chemgroups(46)%specs=>DDEP_RCHO_GROUP
    
    chemgroups(47)%name="CARBONYL"
    chemgroups(47)%specs=>CARBONYL_GROUP
    
    chemgroups(48)%name="WDEP_CARBONYL"
    chemgroups(48)%specs=>WDEP_CARBONYL_GROUP
    
    chemgroups(49)%name="DDEP_CARBONYL"
    chemgroups(49)%specs=>DDEP_CARBONYL_GROUP
    
    chemgroups(50)%name="HSTAR_3P2E3"
    chemgroups(50)%specs=>HSTAR_3P2E3_GROUP
    
    chemgroups(51)%name="WDEP_HSTAR_3P2E3"
    chemgroups(51)%specs=>WDEP_HSTAR_3P2E3_GROUP
    
    chemgroups(52)%name="DDEP_HSTAR_3P2E3"
    chemgroups(52)%specs=>DDEP_HSTAR_3P2E3_GROUP
    
    chemgroups(53)%name="F0_0P2"
    chemgroups(53)%specs=>F0_0P2_GROUP
    
    chemgroups(54)%name="WDEP_F0_0P2"
    chemgroups(54)%specs=>WDEP_F0_0P2_GROUP
    
    chemgroups(55)%name="DDEP_F0_0P2"
    chemgroups(55)%specs=>DDEP_F0_0P2_GROUP
    
    chemgroups(56)%name="DRX_1P4"
    chemgroups(56)%specs=>DRX_1P4_GROUP
    
    chemgroups(57)%name="WDEP_DRX_1P4"
    chemgroups(57)%specs=>WDEP_DRX_1P4_GROUP
    
    chemgroups(58)%name="DDEP_DRX_1P4"
    chemgroups(58)%specs=>DDEP_DRX_1P4_GROUP
    
    chemgroups(59)%name="HSTAR_1P3E1"
    chemgroups(59)%specs=>HSTAR_1P3E1_GROUP
    
    chemgroups(60)%name="DDEP_HSTAR_1P3E1"
    chemgroups(60)%specs=>DDEP_HSTAR_1P3E1_GROUP
    
    chemgroups(61)%name="F0_0P05"
    chemgroups(61)%specs=>F0_0P05_GROUP
    
    chemgroups(62)%name="DDEP_F0_0P05"
    chemgroups(62)%specs=>DDEP_F0_0P05_GROUP
    
    chemgroups(63)%name="HSTAR_5P0E0"
    chemgroups(63)%specs=>HSTAR_5P0E0_GROUP
    
    chemgroups(64)%name="DDEP_HSTAR_5P0E0"
    chemgroups(64)%specs=>DDEP_HSTAR_5P0E0_GROUP
    
    chemgroups(65)%name="DRX_2P6"
    chemgroups(65)%specs=>DRX_2P6_GROUP
    
    chemgroups(66)%name="DDEP_DRX_2P6"
    chemgroups(66)%specs=>DDEP_DRX_2P6_GROUP
    
    chemgroups(67)%name="HSTAR_2P0E1"
    chemgroups(67)%specs=>HSTAR_2P0E1_GROUP
    
    chemgroups(68)%name="DDEP_HSTAR_2P0E1"
    chemgroups(68)%specs=>DDEP_HSTAR_2P0E1_GROUP
    
    chemgroups(69)%name="DRX_2P7"
    chemgroups(69)%specs=>DRX_2P7_GROUP
    
    chemgroups(70)%name="DDEP_DRX_2P7"
    chemgroups(70)%specs=>DDEP_DRX_2P7_GROUP
    
    chemgroups(71)%name="HSTAR_3P0E1"
    chemgroups(71)%specs=>HSTAR_3P0E1_GROUP
    
    chemgroups(72)%name="DDEP_HSTAR_3P0E1"
    chemgroups(72)%specs=>DDEP_HSTAR_3P0E1_GROUP
    
    chemgroups(73)%name="HSTAR_4P1E4"
    chemgroups(73)%specs=>HSTAR_4P1E4_GROUP
    
    chemgroups(74)%name="WDEP_HSTAR_4P1E4"
    chemgroups(74)%specs=>WDEP_HSTAR_4P1E4_GROUP
    
    chemgroups(75)%name="DDEP_HSTAR_4P1E4"
    chemgroups(75)%specs=>DDEP_HSTAR_4P1E4_GROUP
    
    chemgroups(76)%name="F0_0P0"
    chemgroups(76)%specs=>F0_0P0_GROUP
    
    chemgroups(77)%name="WDEP_F0_0P0"
    chemgroups(77)%specs=>WDEP_F0_0P0_GROUP
    
    chemgroups(78)%name="DDEP_F0_0P0"
    chemgroups(78)%specs=>DDEP_F0_0P0_GROUP
    
    chemgroups(79)%name="DRX_2P2"
    chemgroups(79)%specs=>DRX_2P2_GROUP
    
    chemgroups(80)%name="WDEP_DRX_2P2"
    chemgroups(80)%specs=>WDEP_DRX_2P2_GROUP
    
    chemgroups(81)%name="DDEP_DRX_2P2"
    chemgroups(81)%specs=>DDEP_DRX_2P2_GROUP
    
    chemgroups(82)%name="ROOH"
    chemgroups(82)%specs=>ROOH_GROUP
    
    chemgroups(83)%name="WDEP_ROOH"
    chemgroups(83)%specs=>WDEP_ROOH_GROUP
    
    chemgroups(84)%name="DDEP_ROOH"
    chemgroups(84)%specs=>DDEP_ROOH_GROUP
    
    chemgroups(85)%name="HSTAR_2P2E4"
    chemgroups(85)%specs=>HSTAR_2P2E4_GROUP
    
    chemgroups(86)%name="WDEP_HSTAR_2P2E4"
    chemgroups(86)%specs=>WDEP_HSTAR_2P2E4_GROUP
    
    chemgroups(87)%name="DDEP_HSTAR_2P2E4"
    chemgroups(87)%specs=>DDEP_HSTAR_2P2E4_GROUP
    
    chemgroups(88)%name="DRX_2P4"
    chemgroups(88)%specs=>DRX_2P4_GROUP
    
    chemgroups(89)%name="WDEP_DRX_2P4"
    chemgroups(89)%specs=>WDEP_DRX_2P4_GROUP
    
    chemgroups(90)%name="DDEP_DRX_2P4"
    chemgroups(90)%specs=>DDEP_DRX_2P4_GROUP
    
    chemgroups(91)%name="HSTAR_8P0E3"
    chemgroups(91)%specs=>HSTAR_8P0E3_GROUP
    
    chemgroups(92)%name="WDEP_HSTAR_8P0E3"
    chemgroups(92)%specs=>WDEP_HSTAR_8P0E3_GROUP
    
    chemgroups(93)%name="DDEP_HSTAR_8P0E3"
    chemgroups(93)%specs=>DDEP_HSTAR_8P0E3_GROUP
    
    chemgroups(94)%name="WDEP_F0_0P05"
    chemgroups(94)%specs=>WDEP_F0_0P05_GROUP
    
    chemgroups(95)%name="WDEP_DRX_2P6"
    chemgroups(95)%specs=>WDEP_DRX_2P6_GROUP
    
    chemgroups(96)%name="HSTAR_3P0E5"
    chemgroups(96)%specs=>HSTAR_3P0E5_GROUP
    
    chemgroups(97)%name="WDEP_HSTAR_3P0E5"
    chemgroups(97)%specs=>WDEP_HSTAR_3P0E5_GROUP
    
    chemgroups(98)%name="DDEP_HSTAR_3P0E5"
    chemgroups(98)%specs=>DDEP_HSTAR_3P0E5_GROUP
    
    chemgroups(99)%name="HSTAR_2P4E4"
    chemgroups(99)%specs=>HSTAR_2P4E4_GROUP
    
    chemgroups(100)%name="WDEP_HSTAR_2P4E4"
    chemgroups(100)%specs=>WDEP_HSTAR_2P4E4_GROUP
    
    chemgroups(101)%name="DDEP_HSTAR_2P4E4"
    chemgroups(101)%specs=>DDEP_HSTAR_2P4E4_GROUP
    
    chemgroups(102)%name="DRX_2P5"
    chemgroups(102)%specs=>DRX_2P5_GROUP
    
    chemgroups(103)%name="WDEP_DRX_2P5"
    chemgroups(103)%specs=>WDEP_DRX_2P5_GROUP
    
    chemgroups(104)%name="DDEP_DRX_2P5"
    chemgroups(104)%specs=>DDEP_DRX_2P5_GROUP
    
    chemgroups(105)%name="HSTAR_2P8E3"
    chemgroups(105)%specs=>HSTAR_2P8E3_GROUP
    
    chemgroups(106)%name="WDEP_HSTAR_2P8E3"
    chemgroups(106)%specs=>WDEP_HSTAR_2P8E3_GROUP
    
    chemgroups(107)%name="DDEP_HSTAR_2P8E3"
    chemgroups(107)%specs=>DDEP_HSTAR_2P8E3_GROUP
    
    chemgroups(108)%name="DRX_2P8"
    chemgroups(108)%specs=>DRX_2P8_GROUP
    
    chemgroups(109)%name="WDEP_DRX_2P8"
    chemgroups(109)%specs=>WDEP_DRX_2P8_GROUP
    
    chemgroups(110)%name="DDEP_DRX_2P8"
    chemgroups(110)%specs=>DDEP_DRX_2P8_GROUP
    
    chemgroups(111)%name="DRX_3P0"
    chemgroups(111)%specs=>DRX_3P0_GROUP
    
    chemgroups(112)%name="WDEP_DRX_3P0"
    chemgroups(112)%specs=>WDEP_DRX_3P0_GROUP
    
    chemgroups(113)%name="DDEP_DRX_3P0"
    chemgroups(113)%specs=>DDEP_DRX_3P0_GROUP
    
    chemgroups(114)%name="HSTAR_1P4E5"
    chemgroups(114)%specs=>HSTAR_1P4E5_GROUP
    
    chemgroups(115)%name="WDEP_HSTAR_1P4E5"
    chemgroups(115)%specs=>WDEP_HSTAR_1P4E5_GROUP
    
    chemgroups(116)%name="DDEP_HSTAR_1P4E5"
    chemgroups(116)%specs=>DDEP_HSTAR_1P4E5_GROUP
    
    chemgroups(117)%name="DRX_2P9"
    chemgroups(117)%specs=>DRX_2P9_GROUP
    
    chemgroups(118)%name="WDEP_DRX_2P9"
    chemgroups(118)%specs=>WDEP_DRX_2P9_GROUP
    
    chemgroups(119)%name="DDEP_DRX_2P9"
    chemgroups(119)%specs=>DDEP_DRX_2P9_GROUP
    
    chemgroups(120)%name="HSTAR_9P3E5"
    chemgroups(120)%specs=>HSTAR_9P3E5_GROUP
    
    chemgroups(121)%name="WDEP_HSTAR_9P3E5"
    chemgroups(121)%specs=>WDEP_HSTAR_9P3E5_GROUP
    
    chemgroups(122)%name="DDEP_HSTAR_9P3E5"
    chemgroups(122)%specs=>DDEP_HSTAR_9P3E5_GROUP
    
    chemgroups(123)%name="HSTAR_7P3E1"
    chemgroups(123)%specs=>HSTAR_7P3E1_GROUP
    
    chemgroups(124)%name="DDEP_HSTAR_7P3E1"
    chemgroups(124)%specs=>DDEP_HSTAR_7P3E1_GROUP
    
    chemgroups(125)%name="HSTAR_3P2E4"
    chemgroups(125)%specs=>HSTAR_3P2E4_GROUP
    
    chemgroups(126)%name="WDEP_HSTAR_3P2E4"
    chemgroups(126)%specs=>WDEP_HSTAR_3P2E4_GROUP
    
    chemgroups(127)%name="DDEP_HSTAR_3P2E4"
    chemgroups(127)%specs=>DDEP_HSTAR_3P2E4_GROUP
    
    chemgroups(128)%name="HSTAR_6P0E5"
    chemgroups(128)%specs=>HSTAR_6P0E5_GROUP
    
    chemgroups(129)%name="WDEP_HSTAR_6P0E5"
    chemgroups(129)%specs=>WDEP_HSTAR_6P0E5_GROUP
    
    chemgroups(130)%name="DDEP_HSTAR_6P0E5"
    chemgroups(130)%specs=>DDEP_HSTAR_6P0E5_GROUP
    
    chemgroups(131)%name="DRX_3P1"
    chemgroups(131)%specs=>DRX_3P1_GROUP
    
    chemgroups(132)%name="WDEP_DRX_3P1"
    chemgroups(132)%specs=>WDEP_DRX_3P1_GROUP
    
    chemgroups(133)%name="DDEP_DRX_3P1"
    chemgroups(133)%specs=>DDEP_DRX_3P1_GROUP
    
    chemgroups(134)%name="HSTAR_1P0E2"
    chemgroups(134)%specs=>HSTAR_1P0E2_GROUP
    
    chemgroups(135)%name="DDEP_HSTAR_1P0E2"
    chemgroups(135)%specs=>DDEP_HSTAR_1P0E2_GROUP
    
    chemgroups(136)%name="ACID"
    chemgroups(136)%specs=>ACID_GROUP
    
    chemgroups(137)%name="WDEP_ACID"
    chemgroups(137)%specs=>WDEP_ACID_GROUP
    
    chemgroups(138)%name="DDEP_ACID"
    chemgroups(138)%specs=>DDEP_ACID_GROUP
    
    chemgroups(139)%name="HSTAR_4P2E7"
    chemgroups(139)%specs=>HSTAR_4P2E7_GROUP
    
    chemgroups(140)%name="WDEP_HSTAR_4P2E7"
    chemgroups(140)%specs=>WDEP_HSTAR_4P2E7_GROUP
    
    chemgroups(141)%name="DDEP_HSTAR_4P2E7"
    chemgroups(141)%specs=>DDEP_HSTAR_4P2E7_GROUP
    
    chemgroups(142)%name="HSTAR_1P3E10"
    chemgroups(142)%specs=>HSTAR_1P3E10_GROUP
    
    chemgroups(143)%name="WDEP_HSTAR_1P3E10"
    chemgroups(143)%specs=>WDEP_HSTAR_1P3E10_GROUP
    
    chemgroups(144)%name="DDEP_HSTAR_1P3E10"
    chemgroups(144)%specs=>DDEP_HSTAR_1P3E10_GROUP
    
    chemgroups(145)%name="HSTAR_3P0E2"
    chemgroups(145)%specs=>HSTAR_3P0E2_GROUP
    
    chemgroups(146)%name="DDEP_HSTAR_3P0E2"
    chemgroups(146)%specs=>DDEP_HSTAR_3P0E2_GROUP
    
    chemgroups(147)%name="DRX_1P9"
    chemgroups(147)%specs=>DRX_1P9_GROUP
    
    chemgroups(148)%name="DDEP_DRX_1P9"
    chemgroups(148)%specs=>DDEP_DRX_1P9_GROUP
    
    chemgroups(149)%name="HSTAR_3P3E2"
    chemgroups(149)%specs=>HSTAR_3P3E2_GROUP
    
    chemgroups(150)%name="DDEP_HSTAR_3P3E2"
    chemgroups(150)%specs=>DDEP_HSTAR_3P3E2_GROUP
    
    chemgroups(151)%name="DRX_2P3"
    chemgroups(151)%specs=>DRX_2P3_GROUP
    
    chemgroups(152)%name="DDEP_DRX_2P3"
    chemgroups(152)%specs=>DDEP_DRX_2P3_GROUP
    
    chemgroups(153)%name="HSTAR_6P2E1"
    chemgroups(153)%specs=>HSTAR_6P2E1_GROUP
    
    chemgroups(154)%name="DDEP_HSTAR_6P2E1"
    chemgroups(154)%specs=>DDEP_HSTAR_6P2E1_GROUP
    
    chemgroups(155)%name="DRX_3P75"
    chemgroups(155)%specs=>DRX_3P75_GROUP
    
    chemgroups(156)%name="DDEP_DRX_3P75"
    chemgroups(156)%specs=>DDEP_DRX_3P75_GROUP
    
    chemgroups(157)%name="HSTAR_1P3E6"
    chemgroups(157)%specs=>HSTAR_1P3E6_GROUP
    
    chemgroups(158)%name="WDEP_HSTAR_1P3E6"
    chemgroups(158)%specs=>WDEP_HSTAR_1P3E6_GROUP
    
    chemgroups(159)%name="DDEP_HSTAR_1P3E6"
    chemgroups(159)%specs=>DDEP_HSTAR_1P3E6_GROUP
    
    chemgroups(160)%name="HSTAR_9P0E4"
    chemgroups(160)%specs=>HSTAR_9P0E4_GROUP
    
    chemgroups(161)%name="WDEP_HSTAR_9P0E4"
    chemgroups(161)%specs=>WDEP_HSTAR_9P0E4_GROUP
    
    chemgroups(162)%name="DDEP_HSTAR_9P0E4"
    chemgroups(162)%specs=>DDEP_HSTAR_9P0E4_GROUP
    
    chemgroups(163)%name="HSTAR_1P6E8"
    chemgroups(163)%specs=>HSTAR_1P6E8_GROUP
    
    chemgroups(164)%name="WDEP_HSTAR_1P6E8"
    chemgroups(164)%specs=>WDEP_HSTAR_1P6E8_GROUP
    
    chemgroups(165)%name="DDEP_HSTAR_1P6E8"
    chemgroups(165)%specs=>DDEP_HSTAR_1P6E8_GROUP
    
    chemgroups(166)%name="DRX_3P55"
    chemgroups(166)%specs=>DRX_3P55_GROUP
    
    chemgroups(167)%name="WDEP_DRX_3P55"
    chemgroups(167)%specs=>WDEP_DRX_3P55_GROUP
    
    chemgroups(168)%name="DDEP_DRX_3P55"
    chemgroups(168)%specs=>DDEP_DRX_3P55_GROUP
    
    chemgroups(169)%name="F0_0P3"
    chemgroups(169)%specs=>F0_0P3_GROUP
    
    chemgroups(170)%name="WDEP_F0_0P3"
    chemgroups(170)%specs=>WDEP_F0_0P3_GROUP
    
    chemgroups(171)%name="DDEP_F0_0P3"
    chemgroups(171)%specs=>DDEP_F0_0P3_GROUP
    
    chemgroups(172)%name="HSTAR_3P1E6"
    chemgroups(172)%specs=>HSTAR_3P1E6_GROUP
    
    chemgroups(173)%name="WDEP_HSTAR_3P1E6"
    chemgroups(173)%specs=>WDEP_HSTAR_3P1E6_GROUP
    
    chemgroups(174)%name="DDEP_HSTAR_3P1E6"
    chemgroups(174)%specs=>DDEP_HSTAR_3P1E6_GROUP
    
    chemgroups(175)%name="DRX_3P88"
    chemgroups(175)%specs=>DRX_3P88_GROUP
    
    chemgroups(176)%name="WDEP_DRX_3P88"
    chemgroups(176)%specs=>WDEP_DRX_3P88_GROUP
    
    chemgroups(177)%name="DDEP_DRX_3P88"
    chemgroups(177)%specs=>DDEP_DRX_3P88_GROUP
    
    chemgroups(178)%name="HSTAR_1P2E5"
    chemgroups(178)%specs=>HSTAR_1P2E5_GROUP
    
    chemgroups(179)%name="WDEP_HSTAR_1P2E5"
    chemgroups(179)%specs=>WDEP_HSTAR_1P2E5_GROUP
    
    chemgroups(180)%name="DDEP_HSTAR_1P2E5"
    chemgroups(180)%specs=>DDEP_HSTAR_1P2E5_GROUP
    
    chemgroups(181)%name="DRX_3P3"
    chemgroups(181)%specs=>DRX_3P3_GROUP
    
    chemgroups(182)%name="WDEP_DRX_3P3"
    chemgroups(182)%specs=>WDEP_DRX_3P3_GROUP
    
    chemgroups(183)%name="DDEP_DRX_3P3"
    chemgroups(183)%specs=>DDEP_DRX_3P3_GROUP
    
    chemgroups(184)%name="DRX_3P2"
    chemgroups(184)%specs=>DRX_3P2_GROUP
    
    chemgroups(185)%name="WDEP_DRX_3P2"
    chemgroups(185)%specs=>WDEP_DRX_3P2_GROUP
    
    chemgroups(186)%name="DDEP_DRX_3P2"
    chemgroups(186)%specs=>DDEP_DRX_3P2_GROUP
    
    chemgroups(187)%name="HSTAR_4P4E8"
    chemgroups(187)%specs=>HSTAR_4P4E8_GROUP
    
    chemgroups(188)%name="WDEP_HSTAR_4P4E8"
    chemgroups(188)%specs=>WDEP_HSTAR_4P4E8_GROUP
    
    chemgroups(189)%name="DDEP_HSTAR_4P4E8"
    chemgroups(189)%specs=>DDEP_HSTAR_4P4E8_GROUP
    
    chemgroups(190)%name="HSTAR_3P5E8"
    chemgroups(190)%specs=>HSTAR_3P5E8_GROUP
    
    chemgroups(191)%name="WDEP_HSTAR_3P5E8"
    chemgroups(191)%specs=>WDEP_HSTAR_3P5E8_GROUP
    
    chemgroups(192)%name="DDEP_HSTAR_3P5E8"
    chemgroups(192)%specs=>DDEP_HSTAR_3P5E8_GROUP
    
    chemgroups(193)%name="HSTAR_1P4E8"
    chemgroups(193)%specs=>HSTAR_1P4E8_GROUP
    
    chemgroups(194)%name="WDEP_HSTAR_1P4E8"
    chemgroups(194)%specs=>WDEP_HSTAR_1P4E8_GROUP
    
    chemgroups(195)%name="DDEP_HSTAR_1P4E8"
    chemgroups(195)%specs=>DDEP_HSTAR_1P4E8_GROUP
    
    chemgroups(196)%name="DRX_4P1"
    chemgroups(196)%specs=>DRX_4P1_GROUP
    
    chemgroups(197)%name="WDEP_DRX_4P1"
    chemgroups(197)%specs=>WDEP_DRX_4P1_GROUP
    
    chemgroups(198)%name="DDEP_DRX_4P1"
    chemgroups(198)%specs=>DDEP_DRX_4P1_GROUP
    
    chemgroups(199)%name="PEROXYACID"
    chemgroups(199)%specs=>PEROXYACID_GROUP
    
    chemgroups(200)%name="WDEP_PEROXYACID"
    chemgroups(200)%specs=>WDEP_PEROXYACID_GROUP
    
    chemgroups(201)%name="DDEP_PEROXYACID"
    chemgroups(201)%specs=>DDEP_PEROXYACID_GROUP
    
    chemgroups(202)%name="HSTAR_8P3E2"
    chemgroups(202)%specs=>HSTAR_8P3E2_GROUP
    
    chemgroups(203)%name="WDEP_HSTAR_8P3E2"
    chemgroups(203)%specs=>WDEP_HSTAR_8P3E2_GROUP
    
    chemgroups(204)%name="DDEP_HSTAR_8P3E2"
    chemgroups(204)%specs=>DDEP_HSTAR_8P3E2_GROUP
    
    chemgroups(205)%name="HSTAR_6P8E6"
    chemgroups(205)%specs=>HSTAR_6P8E6_GROUP
    
    chemgroups(206)%name="WDEP_HSTAR_6P8E6"
    chemgroups(206)%specs=>WDEP_HSTAR_6P8E6_GROUP
    
    chemgroups(207)%name="DDEP_HSTAR_6P8E6"
    chemgroups(207)%specs=>DDEP_HSTAR_6P8E6_GROUP
    
    chemgroups(208)%name="EPOXIDE"
    chemgroups(208)%specs=>EPOXIDE_GROUP
    
    chemgroups(209)%name="WDEP_EPOXIDE"
    chemgroups(209)%specs=>WDEP_EPOXIDE_GROUP
    
    chemgroups(210)%name="DDEP_EPOXIDE"
    chemgroups(210)%specs=>DDEP_EPOXIDE_GROUP
    
    chemgroups(211)%name="HSTAR_0P0E0"
    chemgroups(211)%specs=>HSTAR_0P0E0_GROUP
    
    chemgroups(212)%name="DDEP_HSTAR_0P0E0"
    chemgroups(212)%specs=>DDEP_HSTAR_0P0E0_GROUP
    
    chemgroups(213)%name="NITRATE"
    chemgroups(213)%specs=>NITRATE_GROUP
    
    chemgroups(214)%name="WDEP_NITRATE"
    chemgroups(214)%specs=>WDEP_NITRATE_GROUP
    
    chemgroups(215)%name="DDEP_NITRATE"
    chemgroups(215)%specs=>DDEP_NITRATE_GROUP
    
    chemgroups(216)%name="ORGNO3"
    chemgroups(216)%specs=>ORGNO3_GROUP
    
    chemgroups(217)%name="WDEP_ORGNO3"
    chemgroups(217)%specs=>WDEP_ORGNO3_GROUP
    
    chemgroups(218)%name="DDEP_ORGNO3"
    chemgroups(218)%specs=>DDEP_ORGNO3_GROUP
    
    chemgroups(219)%name="HSTAR_1P5E8"
    chemgroups(219)%specs=>HSTAR_1P5E8_GROUP
    
    chemgroups(220)%name="WDEP_HSTAR_1P5E8"
    chemgroups(220)%specs=>WDEP_HSTAR_1P5E8_GROUP
    
    chemgroups(221)%name="DDEP_HSTAR_1P5E8"
    chemgroups(221)%specs=>DDEP_HSTAR_1P5E8_GROUP
    
    chemgroups(222)%name="DRX_3P4"
    chemgroups(222)%specs=>DRX_3P4_GROUP
    
    chemgroups(223)%name="WDEP_DRX_3P4"
    chemgroups(223)%specs=>WDEP_DRX_3P4_GROUP
    
    chemgroups(224)%name="DDEP_DRX_3P4"
    chemgroups(224)%specs=>DDEP_DRX_3P4_GROUP
    
    chemgroups(225)%name="HSTAR_7P0E1"
    chemgroups(225)%specs=>HSTAR_7P0E1_GROUP
    
    chemgroups(226)%name="DRX_4P0"
    chemgroups(226)%specs=>DRX_4P0_GROUP
    
    chemgroups(227)%name="HSTAR_8P3E4"
    chemgroups(227)%specs=>HSTAR_8P3E4_GROUP
    
    chemgroups(228)%name="WDEP_HSTAR_8P3E4"
    chemgroups(228)%specs=>WDEP_HSTAR_8P3E4_GROUP
    
    chemgroups(229)%name="DDEP_HSTAR_8P3E4"
    chemgroups(229)%specs=>DDEP_HSTAR_8P3E4_GROUP
    
    chemgroups(230)%name="HSTAR_8P1E6"
    chemgroups(230)%specs=>HSTAR_8P1E6_GROUP
    
    chemgroups(231)%name="WDEP_HSTAR_8P1E6"
    chemgroups(231)%specs=>WDEP_HSTAR_8P1E6_GROUP
    
    chemgroups(232)%name="DDEP_HSTAR_8P1E6"
    chemgroups(232)%specs=>DDEP_HSTAR_8P1E6_GROUP
    
    chemgroups(233)%name="HSTAR_5P5E3"
    chemgroups(233)%specs=>HSTAR_5P5E3_GROUP
    
    chemgroups(234)%name="WDEP_HSTAR_5P5E3"
    chemgroups(234)%specs=>WDEP_HSTAR_5P5E3_GROUP
    
    chemgroups(235)%name="DDEP_HSTAR_5P5E3"
    chemgroups(235)%specs=>DDEP_HSTAR_5P5E3_GROUP
    
    chemgroups(236)%name="WDEP_DRX_2P7"
    chemgroups(236)%specs=>WDEP_DRX_2P7_GROUP
    
    chemgroups(237)%name="HSTAR_1P0E3"
    chemgroups(237)%specs=>HSTAR_1P0E3_GROUP
    
    chemgroups(238)%name="WDEP_HSTAR_1P0E3"
    chemgroups(238)%specs=>WDEP_HSTAR_1P0E3_GROUP
    
    chemgroups(239)%name="DDEP_HSTAR_1P0E3"
    chemgroups(239)%specs=>DDEP_HSTAR_1P0E3_GROUP
    
    chemgroups(240)%name="HSTAR_5P0E4"
    chemgroups(240)%specs=>HSTAR_5P0E4_GROUP
    
    chemgroups(241)%name="WDEP_HSTAR_5P0E4"
    chemgroups(241)%specs=>WDEP_HSTAR_5P0E4_GROUP
    
    chemgroups(242)%name="DDEP_HSTAR_5P0E4"
    chemgroups(242)%specs=>DDEP_HSTAR_5P0E4_GROUP
    
    chemgroups(243)%name="WDEP_DRX_3P6"
    chemgroups(243)%specs=>WDEP_DRX_3P6_GROUP
    
    chemgroups(244)%name="DDEP_DRX_3P6"
    chemgroups(244)%specs=>DDEP_DRX_3P6_GROUP
    
    chemgroups(245)%name="HSTAR_4P2E3"
    chemgroups(245)%specs=>HSTAR_4P2E3_GROUP
    
    chemgroups(246)%name="WDEP_HSTAR_4P2E3"
    chemgroups(246)%specs=>WDEP_HSTAR_4P2E3_GROUP
    
    chemgroups(247)%name="DDEP_HSTAR_4P2E3"
    chemgroups(247)%specs=>DDEP_HSTAR_4P2E3_GROUP
    
    chemgroups(248)%name="DRX_3P5"
    chemgroups(248)%specs=>DRX_3P5_GROUP
    
    chemgroups(249)%name="WDEP_DRX_3P5"
    chemgroups(249)%specs=>WDEP_DRX_3P5_GROUP
    
    chemgroups(250)%name="DDEP_DRX_3P5"
    chemgroups(250)%specs=>DDEP_DRX_3P5_GROUP
    
    chemgroups(251)%name="DRX_3P77"
    chemgroups(251)%specs=>DRX_3P77_GROUP
    
    chemgroups(252)%name="WDEP_DRX_3P77"
    chemgroups(252)%specs=>WDEP_DRX_3P77_GROUP
    
    chemgroups(253)%name="DDEP_DRX_3P77"
    chemgroups(253)%specs=>DDEP_DRX_3P77_GROUP
    
    chemgroups(254)%name="HSTAR_3P1E9"
    chemgroups(254)%specs=>HSTAR_3P1E9_GROUP
    
    chemgroups(255)%name="WDEP_HSTAR_3P1E9"
    chemgroups(255)%specs=>WDEP_HSTAR_3P1E9_GROUP
    
    chemgroups(256)%name="DDEP_HSTAR_3P1E9"
    chemgroups(256)%specs=>DDEP_HSTAR_3P1E9_GROUP
    
    chemgroups(257)%name="HSTAR_2P0E13"
    chemgroups(257)%specs=>HSTAR_2P0E13_GROUP
    
    chemgroups(258)%name="WDEP_HSTAR_2P0E13"
    chemgroups(258)%specs=>WDEP_HSTAR_2P0E13_GROUP
    
    chemgroups(259)%name="DDEP_HSTAR_2P0E13"
    chemgroups(259)%specs=>DDEP_HSTAR_2P0E13_GROUP
    
    chemgroups(260)%name="DRX_4P7"
    chemgroups(260)%specs=>DRX_4P7_GROUP
    
    chemgroups(261)%name="WDEP_DRX_4P7"
    chemgroups(261)%specs=>WDEP_DRX_4P7_GROUP
    
    chemgroups(262)%name="DDEP_DRX_4P7"
    chemgroups(262)%specs=>DDEP_DRX_4P7_GROUP
    
    chemgroups(263)%name="PANS"
    chemgroups(263)%specs=>PANS_GROUP
    
    chemgroups(264)%name="DDEP_PANS"
    chemgroups(264)%specs=>DDEP_PANS_GROUP
    
    chemgroups(265)%name="HSTAR_3P0E0"
    chemgroups(265)%specs=>HSTAR_3P0E0_GROUP
    
    chemgroups(266)%name="DDEP_HSTAR_3P0E0"
    chemgroups(266)%specs=>DDEP_HSTAR_3P0E0_GROUP
    
    chemgroups(267)%name="HSTAR_5P5E1"
    chemgroups(267)%specs=>HSTAR_5P5E1_GROUP
    
    chemgroups(268)%name="DDEP_HSTAR_5P5E1"
    chemgroups(268)%specs=>DDEP_HSTAR_5P5E1_GROUP
    
    chemgroups(269)%name="HSTAR_2P9E0"
    chemgroups(269)%specs=>HSTAR_2P9E0_GROUP
    
    chemgroups(270)%name="DDEP_HSTAR_2P9E0"
    chemgroups(270)%specs=>DDEP_HSTAR_2P9E0_GROUP
    
    chemgroups(271)%name="WDEP_PANS"
    chemgroups(271)%specs=>WDEP_PANS_GROUP
    
    chemgroups(272)%name="HSTAR_8P1E4"
    chemgroups(272)%specs=>HSTAR_8P1E4_GROUP
    
    chemgroups(273)%name="WDEP_HSTAR_8P1E4"
    chemgroups(273)%specs=>WDEP_HSTAR_8P1E4_GROUP
    
    chemgroups(274)%name="DDEP_HSTAR_8P1E4"
    chemgroups(274)%specs=>DDEP_HSTAR_8P1E4_GROUP
    
    chemgroups(275)%name="DRX_3P65"
    chemgroups(275)%specs=>DRX_3P65_GROUP
    
    chemgroups(276)%name="WDEP_DRX_3P65"
    chemgroups(276)%specs=>WDEP_DRX_3P65_GROUP
    
    chemgroups(277)%name="DDEP_DRX_3P65"
    chemgroups(277)%specs=>DDEP_DRX_3P65_GROUP
    
    chemgroups(278)%name="HSTAR_2P4E3"
    chemgroups(278)%specs=>HSTAR_2P4E3_GROUP
    
    chemgroups(279)%name="WDEP_HSTAR_2P4E3"
    chemgroups(279)%specs=>WDEP_HSTAR_2P4E3_GROUP
    
    chemgroups(280)%name="DDEP_HSTAR_2P4E3"
    chemgroups(280)%specs=>DDEP_HSTAR_2P4E3_GROUP
    
    chemgroups(281)%name="HSTAR_2P7E14"
    chemgroups(281)%specs=>HSTAR_2P7E14_GROUP
    
    chemgroups(282)%name="WDEP_HSTAR_2P7E14"
    chemgroups(282)%specs=>WDEP_HSTAR_2P7E14_GROUP
    
    chemgroups(283)%name="DDEP_HSTAR_2P7E14"
    chemgroups(283)%specs=>DDEP_HSTAR_2P7E14_GROUP
    
    chemgroups(284)%name="DRX_4P95"
    chemgroups(284)%specs=>DRX_4P95_GROUP
    
    chemgroups(285)%name="WDEP_DRX_4P95"
    chemgroups(285)%specs=>WDEP_DRX_4P95_GROUP
    
    chemgroups(286)%name="DDEP_DRX_4P95"
    chemgroups(286)%specs=>DDEP_DRX_4P95_GROUP
    
    chemgroups(287)%name="MONOTERP"
    chemgroups(287)%specs=>MONOTERP_GROUP
    
    chemgroups(288)%name="HSTAR_1P5E6"
    chemgroups(288)%specs=>HSTAR_1P5E6_GROUP
    
    chemgroups(289)%name="WDEP_HSTAR_1P5E6"
    chemgroups(289)%specs=>WDEP_HSTAR_1P5E6_GROUP
    
    chemgroups(290)%name="DDEP_HSTAR_1P5E6"
    chemgroups(290)%specs=>DDEP_HSTAR_1P5E6_GROUP
    
    chemgroups(291)%name="DRX_4P5"
    chemgroups(291)%specs=>DRX_4P5_GROUP
    
    chemgroups(292)%name="WDEP_DRX_4P5"
    chemgroups(292)%specs=>WDEP_DRX_4P5_GROUP
    
    chemgroups(293)%name="DDEP_DRX_4P5"
    chemgroups(293)%specs=>DDEP_DRX_4P5_GROUP
    
    chemgroups(294)%name="SOX"
    chemgroups(294)%specs=>SOX_GROUP
    
    chemgroups(295)%name="WDEP_SOX"
    chemgroups(295)%specs=>WDEP_SOX_GROUP
    
    chemgroups(296)%name="DDEP_SOX"
    chemgroups(296)%specs=>DDEP_SOX_GROUP
    
    chemgroups(297)%name="PM10"
    chemgroups(297)%specs=>PM10_GROUP
    
    chemgroups(298)%name="WDEP_PM10"
    chemgroups(298)%specs=>WDEP_PM10_GROUP
    
    chemgroups(299)%name="DDEP_PM10"
    chemgroups(299)%specs=>DDEP_PM10_GROUP
    
    chemgroups(300)%name="PMFINE"
    chemgroups(300)%specs=>PMFINE_GROUP
    
    chemgroups(301)%name="WDEP_PMFINE"
    chemgroups(301)%specs=>WDEP_PMFINE_GROUP
    
    chemgroups(302)%name="DDEP_PMFINE"
    chemgroups(302)%specs=>DDEP_PMFINE_GROUP
    
    chemgroups(303)%name="SIA"
    chemgroups(303)%specs=>SIA_GROUP
    
    chemgroups(304)%name="WDEP_SIA"
    chemgroups(304)%specs=>WDEP_SIA_GROUP
    
    chemgroups(305)%name="DDEP_SIA"
    chemgroups(305)%specs=>DDEP_SIA_GROUP
    
    chemgroups(306)%name="RDN"
    chemgroups(306)%specs=>RDN_GROUP
    
    chemgroups(307)%name="WDEP_RDN"
    chemgroups(307)%specs=>WDEP_RDN_GROUP
    
    chemgroups(308)%name="DDEP_RDN"
    chemgroups(308)%specs=>DDEP_RDN_GROUP
    
    chemgroups(309)%name="TNO3"
    chemgroups(309)%specs=>TNO3_GROUP
    
    chemgroups(310)%name="WDEP_TNO3"
    chemgroups(310)%specs=>WDEP_TNO3_GROUP
    
    chemgroups(311)%name="DDEP_TNO3"
    chemgroups(311)%specs=>DDEP_TNO3_GROUP
    
    chemgroups(312)%name="PMCOARSE"
    chemgroups(312)%specs=>PMCOARSE_GROUP
    
    chemgroups(313)%name="WDEP_PMCOARSE"
    chemgroups(313)%specs=>WDEP_PMCOARSE_GROUP
    
    chemgroups(314)%name="DDEP_PMCOARSE"
    chemgroups(314)%specs=>DDEP_PMCOARSE_GROUP
    
    chemgroups(315)%name="OM25"
    chemgroups(315)%specs=>OM25_GROUP
    
    chemgroups(316)%name="NONVOLPCM"
    chemgroups(316)%specs=>NONVOLPCM_GROUP
    
    chemgroups(317)%name="NVABSOM"
    chemgroups(317)%specs=>NVABSOM_GROUP
    
    chemgroups(318)%name="OC"
    chemgroups(318)%specs=>OC_GROUP
    
    chemgroups(319)%name="WDEP_OM25"
    chemgroups(319)%specs=>WDEP_OM25_GROUP
    
    chemgroups(320)%name="DDEP_OM25"
    chemgroups(320)%specs=>DDEP_OM25_GROUP
    
    chemgroups(321)%name="PCM"
    chemgroups(321)%specs=>PCM_GROUP
    
    chemgroups(322)%name="WDEP_PCM"
    chemgroups(322)%specs=>WDEP_PCM_GROUP
    
    chemgroups(323)%name="DDEP_PCM"
    chemgroups(323)%specs=>DDEP_PCM_GROUP
    
    chemgroups(324)%name="ASOA"
    chemgroups(324)%specs=>ASOA_GROUP
    
    chemgroups(325)%name="WDEP_ASOA"
    chemgroups(325)%specs=>WDEP_ASOA_GROUP
    
    chemgroups(326)%name="DDEP_ASOA"
    chemgroups(326)%specs=>DDEP_ASOA_GROUP
    
    chemgroups(327)%name="BSOA"
    chemgroups(327)%specs=>BSOA_GROUP
    
    chemgroups(328)%name="WDEP_BSOA"
    chemgroups(328)%specs=>WDEP_BSOA_GROUP
    
    chemgroups(329)%name="DDEP_BSOA"
    chemgroups(329)%specs=>DDEP_BSOA_GROUP
    
    chemgroups(330)%name="TMPX"
    chemgroups(330)%specs=>TMPX_GROUP
    
    chemgroups(331)%name="DDEP_TMPX"
    chemgroups(331)%specs=>DDEP_TMPX_GROUP
    
    chemgroups(332)%name="WDEP_OC"
    chemgroups(332)%specs=>WDEP_OC_GROUP
    
    chemgroups(333)%name="DDEP_OC"
    chemgroups(333)%specs=>DDEP_OC_GROUP
    
    chemgroups(334)%name="PPM25_FIRE"
    chemgroups(334)%specs=>PPM25_FIRE_GROUP
    
    chemgroups(335)%name="WDEP_PPM25_FIRE"
    chemgroups(335)%specs=>WDEP_PPM25_FIRE_GROUP
    
    chemgroups(336)%name="DDEP_PPM25_FIRE"
    chemgroups(336)%specs=>DDEP_PPM25_FIRE_GROUP
    
    chemgroups(337)%name="PPM10_FIRE"
    chemgroups(337)%specs=>PPM10_FIRE_GROUP
    
    chemgroups(338)%name="WDEP_PPM10_FIRE"
    chemgroups(338)%specs=>WDEP_PPM10_FIRE_GROUP
    
    chemgroups(339)%name="DDEP_PPM10_FIRE"
    chemgroups(339)%specs=>DDEP_PPM10_FIRE_GROUP
    
    chemgroups(340)%name="WDEP_NONVOLPCM"
    chemgroups(340)%specs=>WDEP_NONVOLPCM_GROUP
    
    chemgroups(341)%name="DDEP_NONVOLPCM"
    chemgroups(341)%specs=>DDEP_NONVOLPCM_GROUP
    
    chemgroups(342)%name="WDEP_NVABSOM"
    chemgroups(342)%specs=>WDEP_NVABSOM_GROUP
    
    chemgroups(343)%name="DDEP_NVABSOM"
    chemgroups(343)%specs=>DDEP_NVABSOM_GROUP
    
    chemgroups(344)%name="FBBPOA25"
    chemgroups(344)%specs=>FBBPOA25_GROUP
    
    chemgroups(345)%name="WDEP_FBBPOA25"
    chemgroups(345)%specs=>WDEP_FBBPOA25_GROUP
    
    chemgroups(346)%name="DDEP_FBBPOA25"
    chemgroups(346)%specs=>DDEP_FBBPOA25_GROUP
    
    chemgroups(347)%name="EC_F"
    chemgroups(347)%specs=>EC_F_GROUP
    
    chemgroups(348)%name="WDEP_EC_F"
    chemgroups(348)%specs=>WDEP_EC_F_GROUP
    
    chemgroups(349)%name="DDEP_EC_F"
    chemgroups(349)%specs=>DDEP_EC_F_GROUP
    
    chemgroups(350)%name="FFIREBC"
    chemgroups(350)%specs=>FFIREBC_GROUP
    
    chemgroups(351)%name="WDEP_FFIREBC"
    chemgroups(351)%specs=>WDEP_FFIREBC_GROUP
    
    chemgroups(352)%name="DDEP_FFIREBC"
    chemgroups(352)%specs=>DDEP_FFIREBC_GROUP
    
    chemgroups(353)%name="ECFINE"
    chemgroups(353)%specs=>ECFINE_GROUP
    
    chemgroups(354)%name="WDEP_ECFINE"
    chemgroups(354)%specs=>WDEP_ECFINE_GROUP
    
    chemgroups(355)%name="DDEP_ECFINE"
    chemgroups(355)%specs=>DDEP_ECFINE_GROUP
    
    chemgroups(356)%name="SS"
    chemgroups(356)%specs=>SS_GROUP
    
    chemgroups(357)%name="WDEP_SS"
    chemgroups(357)%specs=>WDEP_SS_GROUP
    
    chemgroups(358)%name="DDEP_SS"
    chemgroups(358)%specs=>DDEP_SS_GROUP
    
    chemgroups(359)%name="DUST"
    chemgroups(359)%specs=>DUST_GROUP
    
    chemgroups(360)%name="WDEP_DUST"
    chemgroups(360)%specs=>WDEP_DUST_GROUP
    
    chemgroups(361)%name="DDEP_DUST"
    chemgroups(361)%specs=>DDEP_DUST_GROUP
    
    chemgroups(362)%name="DUST_ANT_F"
    chemgroups(362)%specs=>DUST_ANT_F_GROUP
    
    chemgroups(363)%name="WDEP_DUST_ANT_F"
    chemgroups(363)%specs=>WDEP_DUST_ANT_F_GROUP
    
    chemgroups(364)%name="DDEP_DUST_ANT_F"
    chemgroups(364)%specs=>DDEP_DUST_ANT_F_GROUP
    
    chemgroups(365)%name="DUST_ANT_C"
    chemgroups(365)%specs=>DUST_ANT_C_GROUP
    
    chemgroups(366)%name="WDEP_DUST_ANT_C"
    chemgroups(366)%specs=>WDEP_DUST_ANT_C_GROUP
    
    chemgroups(367)%name="DDEP_DUST_ANT_C"
    chemgroups(367)%specs=>DDEP_DUST_ANT_C_GROUP
    
    chemgroups(368)%name="DUST_NAT_F"
    chemgroups(368)%specs=>DUST_NAT_F_GROUP
    
    chemgroups(369)%name="WDEP_DUST_NAT_F"
    chemgroups(369)%specs=>WDEP_DUST_NAT_F_GROUP
    
    chemgroups(370)%name="DDEP_DUST_NAT_F"
    chemgroups(370)%specs=>DDEP_DUST_NAT_F_GROUP
    
    chemgroups(371)%name="DUST_NAT_C"
    chemgroups(371)%specs=>DUST_NAT_C_GROUP
    
    chemgroups(372)%name="WDEP_DUST_NAT_C"
    chemgroups(372)%specs=>WDEP_DUST_NAT_C_GROUP
    
    chemgroups(373)%name="DDEP_DUST_NAT_C"
    chemgroups(373)%specs=>DDEP_DUST_NAT_C_GROUP
    
    chemgroups(374)%name="ASH"
    chemgroups(374)%specs=>ASH_GROUP
    
    chemgroups(375)%name="WDEP_ASH"
    chemgroups(375)%specs=>WDEP_ASH_GROUP
    
    chemgroups(376)%name="DDEP_ASH"
    chemgroups(376)%specs=>DDEP_ASH_GROUP
    
    chemgroups(377)%name="PPM25"
    chemgroups(377)%specs=>PPM25_GROUP
    
    chemgroups(378)%name="WDEP_PPM25"
    chemgroups(378)%specs=>WDEP_PPM25_GROUP
    
    chemgroups(379)%name="DDEP_PPM25"
    chemgroups(379)%specs=>DDEP_PPM25_GROUP
    
    chemgroups(380)%name="PPM10"
    chemgroups(380)%specs=>PPM10_GROUP
    
    chemgroups(381)%name="WDEP_PPM10"
    chemgroups(381)%specs=>WDEP_PPM10_GROUP
    
    chemgroups(382)%name="DDEP_PPM10"
    chemgroups(382)%specs=>DDEP_PPM10_GROUP
    
    chemgroups(383)%name="NVWOODOC25"
    chemgroups(383)%specs=>NVWOODOC25_GROUP
    
    chemgroups(384)%name="WDEP_NVWOODOC25"
    chemgroups(384)%specs=>WDEP_NVWOODOC25_GROUP
    
    chemgroups(385)%name="DDEP_NVWOODOC25"
    chemgroups(385)%specs=>DDEP_NVWOODOC25_GROUP
    
    chemgroups(386)%name="PPM_C"
    chemgroups(386)%specs=>PPM_C_GROUP
    
    chemgroups(387)%name="WDEP_PPM_C"
    chemgroups(387)%specs=>WDEP_PPM_C_GROUP
    
    chemgroups(388)%name="DDEP_PPM_C"
    chemgroups(388)%specs=>DDEP_PPM_C_GROUP
    
    chemgroups(389)%name="NVWOODOC_COARSE"
    chemgroups(389)%specs=>NVWOODOC_COARSE_GROUP
    
    chemgroups(390)%name="WDEP_NVWOODOC_COARSE"
    chemgroups(390)%specs=>WDEP_NVWOODOC_COARSE_GROUP
    
    chemgroups(391)%name="DDEP_NVWOODOC_COARSE"
    chemgroups(391)%specs=>DDEP_NVWOODOC_COARSE_GROUP
    
    chemgroups(392)%name="OMCOARSE"
    chemgroups(392)%specs=>OMCOARSE_GROUP
    
    chemgroups(393)%name="WDEP_OMCOARSE"
    chemgroups(393)%specs=>WDEP_OMCOARSE_GROUP
    
    chemgroups(394)%name="DDEP_OMCOARSE"
    chemgroups(394)%specs=>DDEP_OMCOARSE_GROUP
    
    chemgroups(395)%name="NVFFUELOC25"
    chemgroups(395)%specs=>NVFFUELOC25_GROUP
    
    chemgroups(396)%name="WDEP_NVFFUELOC25"
    chemgroups(396)%specs=>WDEP_NVFFUELOC25_GROUP
    
    chemgroups(397)%name="DDEP_NVFFUELOC25"
    chemgroups(397)%specs=>DDEP_NVFFUELOC25_GROUP
    
    chemgroups(398)%name="PM10ANTHR"
    chemgroups(398)%specs=>PM10ANTHR_GROUP
    
    chemgroups(399)%name="WDEP_PM10ANTHR"
    chemgroups(399)%specs=>WDEP_PM10ANTHR_GROUP
    
    chemgroups(400)%name="DDEP_PM10ANTHR"
    chemgroups(400)%specs=>DDEP_PM10ANTHR_GROUP
    
    chemgroups(401)%name="NVFFUELOC_COARSE"
    chemgroups(401)%specs=>NVFFUELOC_COARSE_GROUP
    
    chemgroups(402)%name="WDEP_NVFFUELOC_COARSE"
    chemgroups(402)%specs=>WDEP_NVFFUELOC_COARSE_GROUP
    
    chemgroups(403)%name="DDEP_NVFFUELOC_COARSE"
    chemgroups(403)%specs=>DDEP_NVFFUELOC_COARSE_GROUP
    
    chemgroups(404)%name="WOODEC"
    chemgroups(404)%specs=>WOODEC_GROUP
    
    chemgroups(405)%name="WDEP_WOODEC"
    chemgroups(405)%specs=>WDEP_WOODEC_GROUP
    
    chemgroups(406)%name="DDEP_WOODEC"
    chemgroups(406)%specs=>DDEP_WOODEC_GROUP
    
    chemgroups(407)%name="WOODECFINE"
    chemgroups(407)%specs=>WOODECFINE_GROUP
    
    chemgroups(408)%name="WDEP_WOODECFINE"
    chemgroups(408)%specs=>WDEP_WOODECFINE_GROUP
    
    chemgroups(409)%name="DDEP_WOODECFINE"
    chemgroups(409)%specs=>DDEP_WOODECFINE_GROUP
    
    chemgroups(410)%name="ECCOARSE"
    chemgroups(410)%specs=>ECCOARSE_GROUP
    
    chemgroups(411)%name="WDEP_ECCOARSE"
    chemgroups(411)%specs=>WDEP_ECCOARSE_GROUP
    
    chemgroups(412)%name="DDEP_ECCOARSE"
    chemgroups(412)%specs=>DDEP_ECCOARSE_GROUP
    
    chemgroups(413)%name="FFUELEC"
    chemgroups(413)%specs=>FFUELEC_GROUP
    
    chemgroups(414)%name="WDEP_FFUELEC"
    chemgroups(414)%specs=>WDEP_FFUELEC_GROUP
    
    chemgroups(415)%name="DDEP_FFUELEC"
    chemgroups(415)%specs=>DDEP_FFUELEC_GROUP
    
    chemgroups(416)%name="FFUELECFINE"
    chemgroups(416)%specs=>FFUELECFINE_GROUP
    
    chemgroups(417)%name="WDEP_FFUELECFINE"
    chemgroups(417)%specs=>WDEP_FFUELECFINE_GROUP
    
    chemgroups(418)%name="DDEP_FFUELECFINE"
    chemgroups(418)%specs=>DDEP_FFUELECFINE_GROUP
    
    chemgroups_factors(1)%name="CSTAR"
    chemgroups_factors(1)%species=>CSTAR_GROUP
    chemgroups_factors(1)%factors=>CSTAR_GROUP_FACTORS
    
    chemgroups_factors(2)%name="DELTAH"
    chemgroups_factors(2)%species=>DELTAH_GROUP
    chemgroups_factors(2)%factors=>DELTAH_GROUP_FACTORS
    
    chemgroups_maps(1)%name="EXTINC"
    chemgroups_maps(1)%species=>EXTINC_GROUP
    chemgroups_maps(1)%maps=>EXTINC_GROUP_MAPBACK
  
  end subroutine Init_ChemGroups

end module ChemGroups_mod
