character(len=8), save, dimension(NEMIS_Specs), public :: EMIS_Specs = (/ &
  "NO      " &
, "NO2     " &
, "SO2     " &
, "SO4     " &
, "CO      " &
, "NH3     " &
, "C2H6    " &
, "NC4H10  " &
, "C2H4    " &
, "C3H6    " &
, "OXYL    " &
, "BENZENE " &
, "TOLUENE " &
, "HCHO    " &
, "CH3CHO  " &
, "MEK     " &
, "C2H5OH  " &
, "CH3OH   " &
, "GLYOX   " &
, "MGLYOX  " &
, "C5H8    " &
, "SHIPNOX " &
, "EC_F_NEW" &
, "EC_F_AGE" &
/)
