! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  CRIv2R5Em PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis
module ChemRates_mod

  use AeroConstants_mod  ! => AERO%PM etc, ...
  use AeroFunctions_mod  ! => UptakeRates, ...
  use ChemDims_mod       ! => NSPEC_TOT, NCHEMRATES, ....
  use ChemFunctions_mod  ! => IUPAC_troe, RiemerN2O5, ....
  use ChemSpecs_mod      ! => PINALD, .... for FgasJ08
  use DefPhotolysis_mod  ! => IDNO2 etc.
  use ZchemData_mod      ! => rct
  
  implicit none
  private
  character(len=*),parameter, public :: CM_schemes_ChemRates = " CRIv2R5Em PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis"
  
  
  public :: setChemRates
  public :: setPhotolUsed
  
  ! Photolysis rates
  integer, save, public, dimension(NPHOTOLRATES) :: photol_used

contains
  
  subroutine setPhotolUsed()
    photol_used = (/ &
        IDO3_O1D  &
      , IDO3_O3P  &
      , IDH2O2  &
      , IDNO2  &
      , IDNO3_NO  &
      , IDNO3_NO2  &
      , IDHONO  &
      , IDHNO3  &
      , IDHCHO_H  &
      , IDHCHO_H2  &
      , IDCH3CHO  &
      , IDMEK  &
      , IDACETON  &
      , IDRCOCHO  &
      , IDCH3O2H  &
      , IDCH3COY  &
    /)  
  end subroutine setPhotolUsed
  
  subroutine setChemRates()
    !integer, intent(in) :: debug_level
  
    rct(1,:) = 5.6e-34*((TEMP/300)**(-2.6))*O2*N2
    rct(2,:) = 6.0e-34*((TEMP/300)**(-2.6))*O2*O2
    rct(3,:) = 8.0e-12*EXP(-2060*TINV)
    rct(4,:) = (((1.0e-31*M*(TEMP/300)**(-1.6))*(5.0e-11*(TEMP/300)  &
             & **(-0.3)))*(10**(LOG10(0.85)  &
             & /(1+(LOG10(((1.0e-31*M*(TEMP/300)**(-1.6))  &
             & /(5.0e-11*(TEMP/300)**(-0.3))))/(0.75-1.27*(LOG10(0.85))))  &
             & **2)))/((1.0e-31*M*(TEMP/300)**(-1.6))+(5.0e-11*(TEMP/300)  &
             & **(-0.3))))
    rct(5,:) = 5.5e-12*EXP(188*TINV)
    rct(6,:) = (((1.3e-31*M*(TEMP/300)**(-1.5))*(2.3e-11*(TEMP/300)**0.24))  &
             & *(10**(LOG10(0.6)/(1+(LOG10(((1.3e-31*M*(TEMP/300)**(-1.5))  &
             & /(2.3e-11*(TEMP/300)**0.24)))/(0.75-1.27*(LOG10(0.6))))  &
             & **2)))/((1.3e-31*M*(TEMP/300)**(-1.5))+(2.3e-11*(TEMP/300)  &
             & **0.24)))
    rct(7,:) = 3.2e-11*EXP(67*TINV)*O2
    rct(8,:) = 2.15e-11*EXP(110*TINV)*N2
    rct(9,:) = 1.4e-12*EXP(-1310*TINV)
    rct(10,:) = 1.4e-13*EXP(-2470*TINV)
    rct(11,:) = 3.3e-39*EXP(530*TINV)*O2
    rct(12,:) = 1.8e-11*EXP(110*TINV)
    rct(13,:) = 4.5e-14*EXP(-1260*TINV)
    rct(14,:) = (((3.6e-30*M*(TEMP/300)**(-4.1))*(1.9e-12*(TEMP/300)**0.2))  &
              & *(10**(LOG10(0.35)/(1+(LOG10(((3.6e-30*M*(TEMP/300)**(-4.1))  &
              & /(1.9e-12*(TEMP/300)**0.2)))/(0.75-1.27*(LOG10(0.35))))  &
              & **2)))/((3.6e-30*M*(TEMP/300)**(-4.1))+(1.9e-12*(TEMP/300)  &
              & **0.2)))
    rct(15,:) = (((1.3e-3*M*(TEMP/300)**(-3.5)*EXP(-11000*TINV))  &
              & *(9.7e+14*(TEMP/300)**0.1*EXP(-11080*TINV)))  &
              & *(10**(LOG10(0.35)/(1+(LOG10(((1.3e-3*M*(TEMP/300)**(-3.5)  &
              & *EXP(-11000*TINV))/(9.7e+14*(TEMP/300)  &
              & **0.1*EXP(-11080*TINV))))/(0.75-1.27*(LOG10(0.35))))**2)))  &
              & /((1.3e-3*M*(TEMP/300)**(-3.5)*EXP(-11000*TINV))  &
              & +(9.7e+14*(TEMP/300)**0.1*EXP(-11080*TINV))))
    rct(16,:) = 2.14e-10*H2O
    rct(17,:) = 1.7e-12*EXP(-940*TINV)
    rct(18,:) = 7.7e-12*EXP(-2100*TINV)
    rct(19,:) = (1.44e-13+(M*3.43e-33))
    rct(20,:) = 2.9e-12*EXP(-160*TINV)
    rct(21,:) = 2.03e-16*((TEMP/300)**(4.57))*EXP(693*TINV)
    rct(22,:) = 4.8e-11*EXP(250*TINV)
    rct(23,:) = 2.2e-13*EXP(600*TINV)*(1+(1.40e-21*EXP(2200*TINV)*H2O))
    rct(24,:) = 1.9e-33*EXP(980*TINV)*(1+(1.40e-21*EXP(2200*TINV)*H2O))*M
    rct(25,:) = (((7.4e-31*M*(TEMP/300)**(-2.4))*(3.3e-11*(TEMP/300)  &
              & **(-0.3)))*(10**(LOG10((EXP(-TEMP/1420)))  &
              & /(1+(LOG10(((7.4e-31*M*(TEMP/300)**(-2.4))  &
              & /(3.3e-11*(TEMP/300)**(-0.3))))  &
              & /(0.75-1.27*(LOG10((EXP(-TEMP/1420))))))**2)))  &
              & /((7.4e-31*M*(TEMP/300)**(-2.4))+(3.3e-11*(TEMP/300)  &
              & **(-0.3))))
    rct(26,:) = (((3.2e-30*M*(TEMP/300)**(-4.5))*(3.0e-11))  &
              & *(10**(LOG10(0.41)/(1+(LOG10(((3.2e-30*M*(TEMP/300)**(-4.5))  &
              & /(3.0e-11)))/(0.75-1.27*(LOG10(0.41))))**2)))  &
              & /((3.2e-30*M*(TEMP/300)**(-4.5))+(3.0e-11)))
    rct(27,:) = 3.45e-12*EXP(270*TINV)
    rct(28,:) = (((1.4e-31*M*(TEMP/300)**(-3.1))*(4.0e-12))*(10**(LOG10(0.4)  &
              & /(1+(LOG10(((1.4e-31*M*(TEMP/300)**(-3.1))/(4.0e-12)))  &
              & /(0.75-1.27*(LOG10(0.4))))**2)))/((1.4e-31*M*(TEMP/300)  &
              & **(-3.1))+(4.0e-12)))
    rct(29,:) = (((4.10e-05*M*EXP(-10650*TINV))*(6.0e+15*EXP(-11170*TINV)))  &
              & *(10**(LOG10(0.4)/(1+(LOG10(((4.10e-05*M*EXP(-10650*TINV))  &
              & /(6.0e+15*EXP(-11170*TINV))))/(0.75-1.27*(LOG10(0.4))))  &
              & **2)))/((4.10e-05*M*EXP(-10650*TINV))  &
              & +(6.0e+15*EXP(-11170*TINV))))
    rct(30,:) = 3.2e-13*EXP(690*TINV)
    rct(31,:) = 2.5e-12*EXP(260*TINV)
    rct(32,:) = ((2.4e-14*EXP(460*TINV))+(((6.5e-34*EXP(1335*TINV))*M)  &
              & /(1+((6.5e-34*EXP(1335*TINV))*M/(2.7e-17*EXP(2199*TINV))))))
    rct(33,:) = 6.38e-18*TEMP**2*EXP(144*TINV)
    rct(34,:) = 6.7e-18*TEMP**2*EXP(511*TINV)
    rct(35,:) = 4.6e-12*EXP(70*TINV)
    rct(36,:) = 2.6e-12*EXP(200*TINV)
    rct(37,:) = 1.25e-17*TEMP**2*EXP(615*TINV)
    rct(38,:) = 2.0e-12*EXP(-2440*TINV)
    rct(39,:) = 4.7e-12*EXP(345*TINV)
    rct(40,:) = (1.4e-12*EXP(-1860*TINV))
    rct(41,:) = 4.9e-12*EXP(405*TINV)
    rct(42,:) = 3.24e-12*EXP(-1860*TINV)
    rct(43,:) = 1.85e-20*(TEMP**2.82)*EXP(-987*TINV)
    rct(44,:) = 1.49e-17*TEMP**2*EXP(-499*TINV)
    rct(45,:) = 1.65e-17*TEMP**2*EXP(-87*TINV)
    rct(46,:) = 9.8e-12*EXP(-425*TINV)
    rct(47,:) = (((8.6e-29*M*(TEMP/300)**(-3.1))*(9.0e-12*(TEMP/300)  &
              & **(-0.85)))*(10**(LOG10(0.48)  &
              & /(1+(LOG10(((8.6e-29*M*(TEMP/300)**(-3.1))  &
              & /(9.0e-12*(TEMP/300)**(-0.85))))/(0.75-1.27*(LOG10(0.48))))  &
              & **2)))/((8.6e-29*M*(TEMP/300)**(-3.1))+(9.0e-12*(TEMP/300)  &
              & **(-0.85))))
    rct(48,:) = 3.3e-12*EXP(-2880*TINV)
    rct(49,:) = 6.82e-15*EXP(-2500*TINV)
    rct(50,:) = (((8e-27*M*(TEMP/300)**(-3.5))*(3.0e-11*(TEMP/300)**(-1)))  &
              & *(10**(LOG10(0.5)/(1+(LOG10(((8e-27*M*(TEMP/300)**(-3.5))  &
              & /(3.0e-11*(TEMP/300)**(-1))))/(0.75-1.27*(LOG10(0.5))))  &
              & **2)))/((8e-27*M*(TEMP/300)**(-3.5))+(3.0e-11*(TEMP/300)  &
              & **(-1))))
    rct(51,:) = 4.6e-13*EXP(-1155*TINV)
    rct(52,:) = 5.77e-15*EXP(-1880*TINV)
    rct(53,:) = 1.01e-11*EXP(550*TINV)
    rct(54,:) = 7.0e-15*EXP(-1060*TINV)
    rct(55,:) = (((5.0e-30*M*(TEMP/300)**(-1.5))*(1.0e-12)  &
              & *(10**(LOG10((0.17*EXP(-51/TEMP)+EXP(-TEMP/204)))  &
              & /(1.0+(LOG10(((5.0e-30*M*(TEMP/300)**(-1.5))/(1.0e-12)))  &
              & /(0.75-1.27*(LOG10((0.17*EXP(-51/TEMP)+EXP(-TEMP/204))))))  &
              & **2))))/((5.0e-30*M*(TEMP/300)**(-1.5))+(1.0e-12)))
    rct(56,:) = 2.3e-12*EXP(-190*TINV)
    rct(57,:) = 1.8e-12*EXP(340*TINV)
    rct(58,:) = 2.70e-11*EXP(390*TINV)
    rct(59,:) = 2.95e-12*EXP(-450*TINV)
    rct(60,:) = 1.03e-14*EXP(-1995*TINV)
    rct(61,:) = 8.8e-12*EXP(-1320*TINV)+1.70e-14*EXP(423*TINV)
    rct(62,:) = 1.5e-12*EXP(-90*TINV)
    rct(63,:) = 1.34e-11*EXP(410*TINV)
    rct(64,:) = 1.20e-12*EXP(490*TINV)
    rct(65,:) = 8.22e-16*EXP(-640*TINV)
    rct(66,:) = 1.62e-11*EXP(460*TINV)
    rct(67,:) = 1.39e-15*EXP(-1280*TINV)
    rct(68,:) = 4.0e-14*EXP(850*TINV)
    rct(69,:) = 8.0e-12*EXP(380*TINV)
    rct(70,:) = 1.4e-15*EXP(-2100*TINV)
    rct(71,:) = 2.6e-12*EXP(610*TINV)
    rct(72,:) = 8.5e-16*EXP(-1520*TINV)
    rct(73,:) = 3.1e-12*EXP(340*TINV)
    rct(74,:) = 1.9e-12*EXP(575*TINV)
    rct(75,:) = 1.6e-12*EXP(305*TINV)
    rct(76,:) = (1.4e-12*EXP(-1860*TINV))*4.0
    rct(77,:) = (1.4e-12*EXP(-1860*TINV))*4.25
    rct(78,:) = (1.4e-12*EXP(-1860*TINV))*5.5
    rct(79,:) = 5.3e-12*EXP(190*TINV)
    rct(80,:) = 4.0e-13*EXP(-845*TINV)
    rct(81,:) = 6.7e-13*EXP(-395*TINV)
    rct(82,:) = 6.2e-13*EXP(-230*TINV)
    rct(83,:) = 3.18e-12*O2
    rct(84,:) = 2.31e16*EXP(-10420*TINV)
    rct(85,:) = 3.11e-12*O2
    rct(86,:) = 7.9e15*EXP(-11370*TINV)
    rct(87,:) = 2.5e-12*EXP(-480*TINV)*O2
    rct(88,:) = 5.95e14*EXP(-9465*TINV)
    rct(89,:) = 3.02e-12*O2
    rct(90,:) = 6.34e15*EXP(-10760*TINV)
    rct(91,:) = 1.78e10*EXP(-8483*TINV)*EXP(1.0e8*(TINV**3))
    rct(92,:) = 1.38e11*EXP(-9750*TINV)
    rct(93,:) = 7.0e11*EXP(-3160*TINV)
    rct(94,:) = 5.0e-12*O2
    rct(95,:) = 5.0e-12*O2*3.2*(1-EXP(-550*TINV))
    rct(96,:) = 5.0e-12*O2*3.2*EXP(-550*TINV)
    rct(97,:) = (3.00e7*EXP(-5300*TINV))
    rct(98,:) = (3.00e7*EXP(-5300*TINV))*0.008
    rct(99,:) = (3.00e7*EXP(-5300*TINV))*0.85
    rct(100,:) = (((3.28e-28*M*(TEMP/300)**(-6.87))*(1.125e-11*(TEMP/300)  &
               & **(-1.105)))*(10**(LOG10(0.30)  &
               & /(1+(LOG10(((3.28e-28*M*(TEMP/300)**(-6.87))  &
               & /(1.125e-11*(TEMP/300)**(-1.105))))  &
               & /(0.75-1.27*(LOG10(0.30))))**2)))/((3.28e-28*M*(TEMP/300)  &
               & **(-6.87))+(1.125e-11*(TEMP/300)**(-1.105))))
    rct(101,:) = (((1.10e-5*EXP(-10100*TINV)*M)*(1.9e+17*EXP(-14100*TINV)))  &
               & *(10**(LOG10(0.30)/(1+(LOG10(((1.10e-5*EXP(-10100*TINV)*M)  &
               & /(1.9e+17*EXP(-14100*TINV))))/(0.75-1.27*(LOG10(0.30))))  &
               & **2)))/((1.10e-5*EXP(-10100*TINV)*M)  &
               & +(1.9e+17*EXP(-14100*TINV))))
    rct(102,:) = (((1.7e-03*EXP(-11280*TINV)*M)*(8.3e+16*EXP(-13940*TINV)))  &
               & *(10**(LOG10(0.36)/(1+(LOG10(((1.7e-03*EXP(-11280*TINV)*M)  &
               & /(8.3e+16*EXP(-13940*TINV))))/(0.75-1.27*(LOG10(0.36))))  &
               & **2)))/((1.7e-03*EXP(-11280*TINV)*M)  &
               & +(8.3e+16*EXP(-13940*TINV))))
    rct(103,:) = 1.6e+16*EXP(-13500*TINV)
    rct(104,:) = (((3.28e-28*M*(TEMP/300)**(-6.87))*(1.125e-11*(TEMP/300)  &
               & **(-1.105)))*(10**(LOG10(0.30)  &
               & /(1+(LOG10(((3.28e-28*M*(TEMP/300)**(-6.87))  &
               & /(1.125e-11*(TEMP/300)**(-1.105))))  &
               & /(0.75-1.27*(LOG10(0.30))))**2)))/((3.28e-28*M*(TEMP/300)  &
               & **(-6.87))+(1.125e-11*(TEMP/300)**(-1.105))))*0.722
    rct(105,:) = 2.3e-12*EXP(360*TINV)
    rct(106,:) = 2.55e-12*EXP(380*TINV)
    rct(107,:) = 2.9e-12*EXP(350*TINV)
    rct(108,:) = 2.7e-12*EXP(360*TINV)
    rct(109,:) = (2.7e-12*EXP(360*TINV))
    rct(110,:) = (7.5e-12*EXP(290*TINV))
    rct(111,:) = 8.7e-12*EXP(290*TINV)
    rct(112,:) = (2.3e-12)*0.4
    rct(113,:) = (2.3e-12)
    rct(114,:) = (2.3e-12)*1.6
    rct(115,:) = (2.3e-12)*1.74
    rct(116,:) = 3.8e-13*EXP(780*TINV)
    rct(117,:) = 6.4e-13*EXP(710*TINV)
    rct(118,:) = (2.91e-13*EXP(1300*TINV))*0.520
    rct(119,:) = 2.03e-13*EXP(1250*TINV)
    rct(120,:) = (2.91e-13*EXP(1300*TINV))*0.625
    rct(121,:) = (2.91e-13*EXP(1300*TINV))*0.52
    rct(122,:) = (2.91e-13*EXP(1300*TINV))*0.706
    rct(123,:) = (2.91e-13*EXP(1300*TINV))*0.77
    rct(124,:) = (2.91e-13*EXP(1300*TINV))*0.820
    rct(125,:) = (2.91e-13*EXP(1300*TINV))*0.859
    rct(126,:) = (2.91e-13*EXP(1300*TINV))*0.89
    rct(127,:) = (2.91e-13*EXP(1300*TINV))*0.914
    rct(128,:) = (2.91e-13*EXP(1300*TINV))*0.387
    rct(129,:) = (3.14e-12*EXP(580*TINV))
    rct(130,:) = 7.4e-13*EXP(-520*TINV)*2
    rct(131,:) = 2*(1.03e-13*EXP(365*TINV)-7.4e-13*EXP(-520*TINV))
    rct(132,:) = 2.3e-12*EXP(-190.0*TINV)
    rct(133,:) = 1.8e-12*EXP(340.0*TINV)
    rct(134,:) = 9.8e-12*EXP(-425.0*TINV)
    rct(135,:) = 2.7e-11*EXP(390.0*TINV)
    rct(136,:) = 1.34e-11*EXP(410.0*TINV)
    rct(137,:) = 8.22e-16*EXP(-640.0*TINV)
    rct(138,:) = 1.2e-12*EXP(490.0*TINV)
    rct(139,:) = 4.0e-12*FGAS(ASOC_UG1,  &
               & :)
    rct(140,:) = 4.0e-12*FGAS(ASOC_UG10,  &
               & :)
    rct(141,:) = 4.0e-12*FGAS(ASOC_UG1e2,  &
               & :)
    rct(142,:) = 4.0e-12*FGAS(ASOC_UG1e3,  &
               & :)
    rct(143,:) = 4.0e-12*FGAS(NON_C_ASOA_UG1,  &
               & :)
    rct(144,:) = 4.0e-12*FGAS(NON_C_ASOA_UG10,  &
               & :)
    rct(145,:) = 4.0e-12*FGAS(NON_C_ASOA_UG1e2,  &
               & :)
    rct(146,:) = 4.0e-12*FGAS(NON_C_ASOA_UG1e3,  &
               & :)
    rct(147,:) = 4.0e-12*FGAS(BSOC_UG1,  &
               & :)
    rct(148,:) = 4.0e-12*FGAS(BSOC_UG10,  &
               & :)
    rct(149,:) = 4.0e-12*FGAS(BSOC_UG1e2,  &
               & :)
    rct(150,:) = 4.0e-12*FGAS(BSOC_UG1e3,  &
               & :)
    rct(151,:) = 4.0e-12*FGAS(NON_C_BSOA_UG1,  &
               & :)
    rct(152,:) = 4.0e-12*FGAS(NON_C_BSOA_UG10,  &
               & :)
    rct(153,:) = 4.0e-12*FGAS(NON_C_BSOA_UG1e2,  &
               & :)
    rct(154,:) = 4.0e-12*FGAS(NON_C_BSOA_UG1e3,  &
               & :)
    rct(155,:) = HYDROLYSISN2O5()
    rct(156,:) = UPTAKERATE(CNO3,  &
               & GAM=0.001,  &
               & S=S_M2M3(AERO%PM,  &
               & :))
    rct(157,:) = UPTAKERATE(CHNO3,  &
               & GAM=0.1,  &
               & S=S_M2M3(AERO%DU_C,  &
               & :))
    rct(158,:) = UPTAKERATE(CHNO3,  &
               & GAM=0.01,  &
               & S=S_M2M3(AERO%SS_C,  &
               & :))
    rct(159,:) = UPTAKERATE(CHO2,  &
               & GAM=0.2,  &
               & S=S_M2M3(AERO%PM,  &
               & :))
    rct(160,:) = EC_AGEING_RATE()
  
  end subroutine setChemRates

end module ChemRates_mod
