! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  CRIv2R5Em PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis
module ChemDims_mod

  implicit none
  character(len=*),parameter, public :: CM_schemes_ChemDims = " CRIv2R5Em PM_VBS_EmChem19 Aqueous_EmChem16x Aero2017nx ShipNOx PM_FFireInert SeaSalt DustExtended Ash PM_WoodFFuelInert EC_ageing BVOC_SQT_NV BVOC_IsoMT1_emis"
  

    ! NSPEC for TOT : All reacting species
    integer, public, parameter :: NSPEC_TOT=272
    
    ! NSPEC for ADV : Advected species
    integer, public, parameter :: NSPEC_ADV=213
    
    ! NSPEC for SHL : Short-lived (non-advected) species
    integer, public, parameter :: NSPEC_SHL=59
    
    ! NSPEC for SEMIVOL : Semi-volatile organic aerosols
    integer, public, parameter :: NSPEC_SEMIVOL=20
        
    ! No. DRY deposition species
    integer, public, parameter :: NDRYDEP_ADV = 181
    
    ! No. WET deposition species
    integer, public, parameter :: NWETDEP_ADV = 148
    
    ! No. rate coefficients
    integer, parameter, public :: NCHEMRATES = 160
    
    ! No. photolysis rates used
    integer, parameter, public :: NPHOTOLRATES = 16
    
    ! No. emission Files
    integer, parameter, public :: NEMIS_File = 7
    
    ! No. emission Specss
    integer, parameter, public :: NEMIS_Specs = 62

end module ChemDims_mod
