! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem19a VBS_EmChem19 APINENE_BVOC_emis BVOC_EmChem19 Aqueous_EmChem16x Aero2017nx Ash_EmChem16z ShipNOx16z FFireInert16z SeaSalt16z DustExtended16z Pollen
module ChemDims_mod

  implicit none
  character(len=*),parameter, public :: CM_schemes_ChemDims = " EmChem19a VBS_EmChem19 APINENE_BVOC_emis BVOC_EmChem19 Aqueous_EmChem16x Aero2017nx Ash_EmChem16z ShipNOx16z FFireInert16z SeaSalt16z DustExtended16z Pollen"
  

    ! NSPEC for TOT : All reacting species
    integer, public, parameter :: NSPEC_TOT=136
    
    ! NSPEC for ADV : Advected species
    integer, public, parameter :: NSPEC_ADV=120
    
    ! NSPEC for SHL : Short-lived (non-advected) species
    integer, public, parameter :: NSPEC_SHL=16
    
    ! NSPEC for SEMIVOL : Semi-volatile organic aerosols
    integer, public, parameter :: NSPEC_SEMIVOL=20
        
    ! No. DRY deposition species
    integer, public, parameter :: NDRYDEP_ADV = 97
    
    ! No. WET deposition species
    integer, public, parameter :: NWETDEP_ADV = 83
    
    ! No. rate coefficients
    integer, parameter, public :: NCHEMRATES = 102
    
    ! No. photolysis rates used
    integer, parameter, public :: NPHOTOLRATES = 16
    
    ! No. emission Files
    integer, parameter, public :: NEMIS_File = 7
    
    ! No. emission Specss
    integer, parameter, public :: NEMIS_Specs = 52

end module ChemDims_mod
