module My_LAPACK77_ml
  INTERFACE
    FUNCTION SLAMCH(CMACH)
      REAL(KIND=4)       SLAMCH
      CHARACTER          CMACH
    END FUNCTION SLAMCH
#ifndef MKL
    SUBROUTINE SSPEV(JOBZ,UPLO,N,AP,W,Z,LDZ,WORK,INFO)
      CHARACTER          JOBZ,UPLO
      INTEGER            INFO,LDZ,N
      REAL(KIND=4)       AP(*),W(*),WORK(*),Z(LDZ,*)
    END SUBROUTINE SSPEV
    SUBROUTINE SSPEVX(JOBZ,RANGE,UPLO,N,AP,VL,VU,IL,IU,ABSTOL,M,W,Z,&
                      LDZ,WORK,IWORK,IFAIL,INFO)
      CHARACTER          JOBZ,RANGE,UPLO
      INTEGER            IL,INFO,IU,LDZ,M,N
      REAL(KIND=4)       ABSTOL,VL,VU
      INTEGER            IFAIL(*),IWORK(*)
      REAL(KIND=4)       AP(*),W(*),WORK(*),Z(LDZ,*)
    END SUBROUTINE SSPEVX
#endif
  END INTERFACE

  INTERFACE
    FUNCTION DLAMCH(CMACH)
      REAL(KIND=8)       DLAMCH
      CHARACTER          CMACH
    END FUNCTION DLAMCH
#ifndef MKL
    SUBROUTINE DSPEV(JOBZ,UPLO,N,AP,W,Z,LDZ,WORK,INFO)
      CHARACTER          JOBZ,UPLO
      INTEGER            INFO,LDZ,N
      REAL(KIND=8)       AP(*),W(*),WORK(*),Z(LDZ,*)
    END SUBROUTINE DSPEV
    SUBROUTINE DSPEVX(JOBZ,RANGE,UPLO,N,AP,VL,VU,IL,IU,ABSTOL,M,W,Z,&
                      LDZ,WORK,IWORK,IFAIL,INFO)
      CHARACTER          JOBZ,RANGE,UPLO
      INTEGER            IL,INFO,IU,LDZ,M,N
      REAL(KIND=8)       ABSTOL,VL,VU
      INTEGER            IFAIL(*),IWORK(*)
      REAL(KIND=8)       AP(*),W(*),WORK(*),Z(LDZ,*)
    END SUBROUTINE DSPEVX
#endif
  END INTERFACE
end module My_LAPACK77_ml