! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  Emergency Radiation Ash7bin
module ChemDims_mod

  implicit none
  character(len=*),parameter, public :: CM_schemes_ChemDims = " Emergency Radiation Ash7bin"
  

    ! NSPEC for TOT : All reacting species
    integer, public, parameter :: NSPEC_TOT=43
    
    ! NSPEC for ADV : Advected species
    integer, public, parameter :: NSPEC_ADV=43
    
    ! NSPEC for SHL : Short-lived (non-advected) species
    integer, public, parameter :: NSPEC_SHL=0
    
    ! NSPEC for SEMIVOL : Semi-volatile organic aerosols
    integer, public, parameter :: NSPEC_SEMIVOL=0
        
    ! No. DRY deposition species
    integer, public, parameter :: NDRYDEP_ADV = 21
    
    ! No. WET deposition species
    integer, public, parameter :: NWETDEP_ADV = 19
    
    ! No. rate coefficients
    integer, parameter, public :: NCHEMRATES = 0
    
    ! No. photolysis rates used
    integer, parameter, public :: NPHOTOLRATES = 0
    
    ! No. emission Files
    integer, parameter, public :: NEMIS_File = 1
    
    ! No. emission Specss
    integer, parameter, public :: NEMIS_Specs = 14

end module ChemDims_mod
