! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem16x ShipNOx BVOC_EmChem16x Aero2017nx VBS_acp2012 FFireInert SeaSalt DustExtended
module ChemDims_mod

  implicit none
  character(len=*),parameter, public :: CM_schemes_ChemDims = " EmChem16x ShipNOx BVOC_EmChem16x Aero2017nx VBS_acp2012 FFireInert SeaSalt DustExtended"
  

    ! NSPEC for TOT : All reacting species
    integer, public, parameter :: NSPEC_TOT=127
    
    ! NSPEC for ADV : Advected species
    integer, public, parameter :: NSPEC_ADV=110
    
    ! NSPEC for SHL : Short-lived (non-advected) species
    integer, public, parameter :: NSPEC_SHL=17
    
    ! NSPEC for SEMIVOL : Semi-volatile organic aerosols
    integer, public, parameter :: NSPEC_SEMIVOL=22
        
    ! No. DRY deposition species
    integer, public, parameter :: NDRYDEP_ADV = 65
    
    ! No. WET deposition species
    integer, public, parameter :: NWETDEP_ADV = 56
    
    ! No. rate coefficients
    integer, parameter, public :: NCHEMRATES = 118
    
    ! No. photolysis rates used
    integer, parameter, public :: NPHOTOLRATES = 15
    
    ! No. emission Files
    integer, parameter, public :: NEMIS_File = 7
    
    ! No. emission Specss
    integer, parameter, public :: NEMIS_Specs = 41

end module ChemDims_mod
