! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChemTest
module ChemDims_mod

  implicit none
  character(len=*),parameter, public :: CM_schemes_ChemDims = " EmChemTest"
  

    ! NSPEC for TOT : All reacting species
    integer, public, parameter :: NSPEC_TOT=78+1 !DS +SHIPNOX
    
    ! NSPEC for ADV : Advected species
    integer, public, parameter :: NSPEC_ADV=75+1 !DS +SHIPNOX
    
    ! NSPEC for SHL : Short-lived (non-advected) species
    integer, public, parameter :: NSPEC_SHL=3
    
    ! NSPEC for SEMIVOL : Semi-volatile organic aerosols
    integer, public, parameter :: NSPEC_SEMIVOL=0
        
    ! No. DRY deposition species
    integer, public, parameter :: NDRYDEP_ADV = 19
    
    ! No. WET deposition species
    integer, public, parameter :: NWETDEP_ADV = 10
    
    ! No. rate coefficients
    integer, parameter, public :: NCHEMRATES = 72
    
    ! No. photolysis rates used
    integer, parameter, public :: NPHOTOLRATES = 17
    
    ! No. emission Files
    integer, parameter, public :: NEMIS_File = 5
    
    ! No. emission Specss
    integer, parameter, public :: NEMIS_Specs = 19

end module ChemDims_mod
