! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChemTest TestX VBS_acp2012 Tracers
module ChemDims_mod

  implicit none
  character(len=*),parameter, public :: CM_schemes_ChemDims = " EmChemTest TestX VBS_acp2012 Tracers"
  

    ! NSPEC for TOT : All reacting species
    integer, public, parameter :: NSPEC_TOT=121
    
    ! NSPEC for ADV : Advected species
    integer, public, parameter :: NSPEC_ADV=118
    
    ! NSPEC for SHL : Short-lived (non-advected) species
    integer, public, parameter :: NSPEC_SHL=3
    
    ! NSPEC for SEMIVOL : Semi-volatile organic aerosols
    integer, public, parameter :: NSPEC_SEMIVOL=23
        
    ! No. DRY deposition species
    integer, public, parameter :: NDRYDEP_ADV = 53
    
    ! No. WET deposition species
    integer, public, parameter :: NWETDEP_ADV = 47
    
    ! No. rate coefficients
    integer, parameter, public :: NCHEMRATES = 93
    
    ! No. photolysis rates used
    integer, parameter, public :: NPHOTOLRATES = 17
    
    ! No. emission Files
    integer, parameter, public :: NEMIS_File = 7
    
    ! No. emission Specss
    integer, parameter, public :: NEMIS_Specs = 32

end module ChemDims_mod
