! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  EmChem16x BVOC_EmChem16x Aqueous_EmChem16x Aero2017nx VBS_EmChem16x Ash_EmChem16x ShipNOx FFireInert SeaSalt DustExtended Pollen
module ChemGroups_mod

  use ChemSpecs_mod        ! => species indices
  use OwnDataTypes_mod  ! => typ_sp, typ_factors, typ_maps
  
  implicit none
  private
  character(len=*),parameter, public :: CM_schemes_ChemGroups = " EmChem16x BVOC_EmChem16x Aqueous_EmChem16x Aero2017nx VBS_EmChem16x Ash_EmChem16x ShipNOx FFireInert SeaSalt DustExtended Pollen"
  
  
  ! Assignment of groups from GenIn_Species.csv
  public :: Init_ChemGroups
  
  type(typ_sp), dimension(299), public, save :: chemgroups
  type(typ_factors), dimension(2), public, save :: chemgroups_factors
  type(typ_maps), dimension(1), public, save :: chemgroups_maps
  
  integer, public, target, save, dimension (14) :: &
    RO2_GROUP = (/  &
      CH3O2, C2H5O2, SECC4H9O2, ISRO2, ETRO2, PRRO2, OXYO2, MEKO2,  &
      MALO2, MACRO2, CH3CO3, TERPO2, XMTO3_RO2, TERPPeroxy  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    DAOBS_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_daObs_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    OX_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_OX_GROUP = (/ O3, NO2 /)
  
  integer, public, target, save, dimension (3) :: &
    NOX_GROUP = (/ NO, NO2, SHIPNOX /)
  
  integer, public, target, save, dimension (15) :: &
    OXN_GROUP = (/  &
      NO, NO2, PAN, MPAN, NO3, N2O5, HNO3, HONO, HO2NO2, ISON,  &
      ISON, NALD, NO3_f, NO3_c, SHIPNOX  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_NOX_GROUP = (/ NO2, SHIPNOX /)
  
  integer, public, target, save, dimension (13) :: &
    DDEP_OXN_GROUP = (/  &
      NO2, PAN, MPAN, N2O5, HNO3, HONO, HO2NO2, ISON, ISON, NALD,  &
      NO3_f, NO3_c, SHIPNOX  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    PAN_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_PAN_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    HSTAR_3P0E0_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_Hstar_3p0e0_GROUP = (/ PAN, MPAN /)
  
  integer, public, target, save, dimension (2) :: &
    F0_0P5_GROUP = (/ PAN, HONO /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_f0_0p5_GROUP = (/ PAN, HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P8_GROUP = (/ PAN /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_2p8_GROUP = (/ PAN /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P4_GROUP = (/ MPAN /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_3p4_GROUP = (/ MPAN /)
  
  integer, public, target, save, dimension (9) :: &
    WDEP_OXN_GROUP = (/ N2O5, HNO3, HONO, HO2NO2, ISON, ISON, NALD, NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P6E5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_2p6e5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_2p6e5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_f0_0p5_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_1p6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_1p6_GROUP = (/ HONO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P0E4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_6p0e4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_6p0e4_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    F0_1P0_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_f0_1p0_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_f0_1p0_GROUP = (/ HO2NO2 /)
  
  integer, public, target, save, dimension (3) :: &
    DRX_2P1_GROUP = (/ HO2NO2, GLYOX, CH3CHO /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRx_2p1_GROUP = (/ HO2NO2, GLYOX /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_DRx_2p1_GROUP = (/ HO2NO2, GLYOX, CH3CHO /)
  
  integer, public, target, save, dimension (10) :: &
    RCHO_GROUP = (/  &
      MACR, GLYOX, MGLYOX, MAL, HCHO, CH3CHO, MALO2H, NALD, HPALD,  &
      PACALD  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    DDEP_RCHO_GROUP = (/  &
      MACR, GLYOX, MGLYOX, MAL, HCHO, CH3CHO, MALO2H, NALD, HPALD,  &
      PACALD  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P0E0_GROUP = (/ MACR /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_5p0e0_GROUP = (/ MACR /)
  
  integer, public, target, save, dimension (4) :: &
    F0_0P05_GROUP = (/ MACR, MEK, CH3CHO, ACETOL /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_f0_0p05_GROUP = (/ MACR, MEK, CH3CHO, ACETOL /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P6_GROUP = (/ MACR, ACETOL /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRx_2p6_GROUP = (/ MACR, ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    NITRATE_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_nitrate_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_nitrate_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P0E4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_5p0e4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_5p0e4_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (2) :: &
    F0_0P3_GROUP = (/ ISON, MALO2H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_f0_0p3_GROUP = (/ ISON, MALO2H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_f0_0p3_GROUP = (/ ISON, MALO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_3p6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_3p6_GROUP = (/ ISON /)
  
  integer, public, target, save, dimension (8) :: &
    WDEP_RCHO_GROUP = (/ GLYOX, MGLYOX, MAL, HCHO, MALO2H, NALD, HPALD, PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P0E5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_3p0e5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_3p0e5_GROUP = (/ GLYOX /)
  
  integer, public, target, save, dimension (12) :: &
    CARBONYL_GROUP = (/  &
      MGLYOX, MAL, MEK, HCHO, CH3CHO, MEKO2H, MALO2H, MACROOH,  &
      ACETOL, NALD, HPALD, PACALD  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    WDEP_carbonyl_GROUP = (/  &
      MGLYOX, MAL, HCHO, MEKO2H, MALO2H, MACROOH, ACETOL, NALD,  &
      HPALD, PACALD  &
    /)
  
  integer, public, target, save, dimension (12) :: &
    DDEP_carbonyl_GROUP = (/  &
      MGLYOX, MAL, MEK, HCHO, CH3CHO, MEKO2H, MALO2H, MACROOH,  &
      ACETOL, NALD, HPALD, PACALD  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P4E4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_2p4e4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_2p4e4_GROUP = (/ MGLYOX /)
  
  integer, public, target, save, dimension (7) :: &
    F0_0P2_GROUP = (/ MGLYOX, HCHO, CH3OOH, C2H5OOH, ETRO2H, OXYO2H, CH3CO3H /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_f0_0p2_GROUP = (/ MGLYOX, HCHO, ETRO2H, OXYO2H /)
  
  integer, public, target, save, dimension (7) :: &
    DDEP_f0_0p2_GROUP = (/ MGLYOX, HCHO, CH3OOH, C2H5OOH, ETRO2H, OXYO2H, CH3CO3H /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P5_GROUP = (/ MGLYOX, ETRO2H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRx_2p5_GROUP = (/ MGLYOX, ETRO2H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRx_2p5_GROUP = (/ MGLYOX, ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P0E5_GROUP = (/ MAL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_6p0e5_GROUP = (/ MAL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_6p0e5_GROUP = (/ MAL /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_3P1_GROUP = (/ MAL, MEKO2H /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DRx_3p1_GROUP = (/ MAL, MEKO2H /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRx_3p1_GROUP = (/ MAL, MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_2P0E1_GROUP = (/ MEK /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_2p0e1_GROUP = (/ MEK /)
  
  integer, public, target, save, dimension (2) :: &
    DRX_2P7_GROUP = (/ MEK, NALD /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DRx_2p7_GROUP = (/ MEK, NALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P2E3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_3p2e3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_3p2e3_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_1p4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_1p4_GROUP = (/ HCHO /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P3E1_GROUP = (/ CH3CHO /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_1p3e1_GROUP = (/ CH3CHO /)
  
  integer, public, target, save, dimension (5) :: &
    BVOC_GROUP = (/ C5H8, APINENE, MVK, BPINENE, XTERP /)
  
  integer, public, target, save, dimension (3) :: &
    MONOTERP_GROUP = (/ APINENE, BPINENE, XTERP /)
  
  integer, public, target, save, dimension (13) :: &
    ROOH_GROUP = (/  &
      CH3OOH, C2H5OOH, BURO2H, ETRO2H, PRRO2H, OXYO2H, MEKO2H,  &
      MALO2H, MACROOH, ISRO2H, H2O2, HPALD, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (13) :: &
    DDEP_ROOH_GROUP = (/  &
      CH3OOH, C2H5OOH, BURO2H, ETRO2H, PRRO2H, OXYO2H, MEKO2H,  &
      MALO2H, MACROOH, ISRO2H, H2O2, HPALD, TERPOOH  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P0E2_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_3p0e2_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_1P9_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_1p9_GROUP = (/ CH3OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P3E2_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_3p3e2_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P3_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_2p3_GROUP = (/ C2H5OOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_6P2E1_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_6p2e1_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P0_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_3p0_GROUP = (/ BURO2H /)
  
  integer, public, target, save, dimension (9) :: &
    WDEP_ROOH_GROUP = (/  &
      ETRO2H, PRRO2H, OXYO2H, MEKO2H, MALO2H, MACROOH, ISRO2H,  &
      H2O2, HPALD  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P3E6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_1p3e6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_1p3e6_GROUP = (/ ETRO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P4E8_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_1p4e8_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_1p4e8_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_4P1_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_4p1_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_4p1_GROUP = (/ OXYO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_9P0E4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_9p0e4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_9p0e4_GROUP = (/ MEKO2H /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P6E8_GROUP = (/ MALO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_1p6e8_GROUP = (/ MALO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_1p6e8_GROUP = (/ MALO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P55_GROUP = (/ MALO2H /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_3p55_GROUP = (/ MALO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_3p55_GROUP = (/ MALO2H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P2_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_3p2_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_3p2_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_3P5E8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_3p5e8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_3p5e8_GROUP = (/ MACROOH /)
  
  integer, public, target, save, dimension (2) :: &
    PEROXYACID_GROUP = (/ CH3CO3H, PACALD /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_peroxyacid_GROUP = (/ CH3CO3H, PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P3E2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_8p3e2_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_2P4_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_2p4_GROUP = (/ CH3CO3H /)
  
  integer, public, target, save, dimension (1) :: &
    HYDROXYKETONE_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_hydroxyketone_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_hydroxyketone_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_8P0E3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_8p0e3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_8p0e3_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_f0_0p05_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_2p6_GROUP = (/ ACETOL /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_5P5E3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_5p5e3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_5p5e3_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_2p7_GROUP = (/ NALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P2E5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_1p2e5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_1p2e5_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P3_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_3p3_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_3p3_GROUP = (/ HPALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_peroxyacid_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    HSTAR_1P5E6_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_Hstar_1p5e6_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_Hstar_1p5e6_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    DRX_3P47_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DRx_3p47_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DRx_3p47_GROUP = (/ PACALD /)
  
  integer, public, target, save, dimension (1) :: &
    EPOXIDE_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_epoxide_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_epoxide_GROUP = (/ IEPOX /)
  
  integer, public, target, save, dimension (2) :: &
    SOX_GROUP = (/ SO2, SO4 /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_SOX_GROUP = (/ SO2, SO4 /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_SOX_GROUP = (/ SO2, SO4 /)
  
  integer, public, target, save, dimension (28) :: &
    PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, POM_c_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new, EC_f_FFUEL_age,  &
      EC_c_FFUEL, REMPPM25, REMPPM_c, OM25_p, VBS_TEST, Ash_f,  &
      Ash_c, FFIRE_BC, FFIRE_REMPPM25, ffire_c, SeaSalt_f,  &
      SeaSalt_c, Dust_ROAD_f, Dust_ROAD_c, Dust_WB_f, Dust_WB_c,  &
      Dust_SAH_f, Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (26) :: &
    WDEP_PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, POM_c_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new, EC_f_FFUEL_age,  &
      EC_c_FFUEL, REMPPM25, REMPPM_c, Ash_f, Ash_c, FFIRE_BC,  &
      FFIRE_REMPPM25, ffire_c, SeaSalt_f, SeaSalt_c, Dust_ROAD_f,  &
      Dust_ROAD_c, Dust_WB_f, Dust_WB_c, Dust_SAH_f, Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (26) :: &
    DDEP_PM10_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, POM_c_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new, EC_f_FFUEL_age,  &
      EC_c_FFUEL, REMPPM25, REMPPM_c, Ash_f, Ash_c, FFIRE_BC,  &
      FFIRE_REMPPM25, ffire_c, SeaSalt_f, SeaSalt_c, Dust_ROAD_f,  &
      Dust_ROAD_c, Dust_WB_f, Dust_WB_c, Dust_SAH_f, Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (17) :: &
    PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, EC_f_WOOD_new, EC_f_WOOD_age,  &
      EC_f_FFUEL_new, EC_f_FFUEL_age, REMPPM25, OM25_p, VBS_TEST,  &
      Ash_f, FFIRE_BC, FFIRE_REMPPM25, SeaSalt_f, Dust_ROAD_f,  &
      Dust_WB_f, Dust_SAH_f  &
    /)
  
  integer, public, target, save, dimension (15) :: &
    WDEP_PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, EC_f_WOOD_new, EC_f_WOOD_age,  &
      EC_f_FFUEL_new, EC_f_FFUEL_age, REMPPM25, Ash_f, FFIRE_BC,  &
      FFIRE_REMPPM25, SeaSalt_f, Dust_ROAD_f, Dust_WB_f,  &
      Dust_SAH_f  &
    /)
  
  integer, public, target, save, dimension (15) :: &
    DDEP_PMFINE_GROUP = (/  &
      SO4, NO3_f, NH4_f, EC_f_WOOD_new, EC_f_WOOD_age,  &
      EC_f_FFUEL_new, EC_f_FFUEL_age, REMPPM25, Ash_f, FFIRE_BC,  &
      FFIRE_REMPPM25, SeaSalt_f, Dust_ROAD_f, Dust_WB_f,  &
      Dust_SAH_f  &
    /)
  
  integer, public, target, save, dimension (4) :: &
    SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_SIA_GROUP = (/ SO4, NO3_f, NO3_c, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_RDN_GROUP = (/ NH3, NH4_f /)
  
  integer, public, target, save, dimension (2) :: &
    TNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_TNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_TNO3_GROUP = (/ NO3_f, NO3_c /)
  
  integer, public, target, save, dimension (9) :: &
    PMCO_GROUP = (/  &
      NO3_c, POM_c_FFUEL, REMPPM_c, Ash_c, ffire_c, SeaSalt_c,  &
      Dust_ROAD_c, Dust_WB_c, Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (9) :: &
    WDEP_PMCO_GROUP = (/  &
      NO3_c, POM_c_FFUEL, REMPPM_c, Ash_c, ffire_c, SeaSalt_c,  &
      Dust_ROAD_c, Dust_WB_c, Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (9) :: &
    DDEP_PMCO_GROUP = (/  &
      NO3_c, POM_c_FFUEL, REMPPM_c, Ash_c, ffire_c, SeaSalt_c,  &
      Dust_ROAD_c, Dust_WB_c, Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (13) :: &
    NONVOLPCM_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, POM_c_FFUEL,  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, EC_c_FFUEL, OM25_BGND, FFIRE_OM, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (12) :: &
    WDEP_NONVOLPCM_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, POM_c_FFUEL,  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, EC_c_FFUEL, FFIRE_OM, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (12) :: &
    DDEP_NONVOLPCM_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, POM_c_FFUEL,  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, EC_c_FFUEL, FFIRE_OM, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    NVABSOM_GROUP = (/ SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, OM25_BGND, FFIRE_OM /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_NVABSOM_GROUP = (/ SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, FFIRE_OM /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_NVABSOM_GROUP = (/ SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, FFIRE_OM /)
  
  integer, public, target, save, dimension (27) :: &
    OM25_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, OM25_BGND, ASOC_ng100,  &
      ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100,  &
      NON_C_BSOA_ug1, NON_C_BSOA_ug10, NON_C_BSOA_ug1e2,  &
      NON_C_BSOA_ug1e3, FFFUEL_ng10, WOODOA_ng10, FFIRE_OM  &
    /)
  
  integer, public, target, save, dimension (26) :: &
    WDEP_OM25_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, ASOC_ng100, ASOC_ug1,  &
      ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3, NON_C_ASOA_ng100,  &
      NON_C_ASOA_ug1, NON_C_ASOA_ug10, NON_C_ASOA_ug1e2,  &
      NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1, BSOC_ug10,  &
      BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100, NON_C_BSOA_ug1,  &
      NON_C_BSOA_ug10, NON_C_BSOA_ug1e2, NON_C_BSOA_ug1e3,  &
      FFFUEL_ng10, WOODOA_ng10, FFIRE_OM  &
    /)
  
  integer, public, target, save, dimension (24) :: &
    DDEP_OM25_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, ASOC_ng100, ASOC_ug1,  &
      ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3, NON_C_ASOA_ng100,  &
      NON_C_ASOA_ug1, NON_C_ASOA_ug10, NON_C_ASOA_ug1e2,  &
      NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1, BSOC_ug10,  &
      BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100, NON_C_BSOA_ug1,  &
      NON_C_BSOA_ug10, NON_C_BSOA_ug1e2, NON_C_BSOA_ug1e3,  &
      FFIRE_OM  &
    /)
  
  integer, public, target, save, dimension (31) :: &
    PCM_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_f_FFUEL_new, EC_f_FFUEL_age, ASOC_ng100,  &
      ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100,  &
      NON_C_BSOA_ug1, NON_C_BSOA_ug10, NON_C_BSOA_ug1e2,  &
      NON_C_BSOA_ug1e3, FFFUEL_ng10, WOODOA_ng10, FFIRE_OM,  &
      FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (31) :: &
    WDEP_PCM_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_f_FFUEL_new, EC_f_FFUEL_age, ASOC_ng100,  &
      ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100,  &
      NON_C_BSOA_ug1, NON_C_BSOA_ug10, NON_C_BSOA_ug1e2,  &
      NON_C_BSOA_ug1e3, FFFUEL_ng10, WOODOA_ng10, FFIRE_OM,  &
      FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (29) :: &
    DDEP_PCM_GROUP = (/  &
      SQT_SOA_NV, POM_f_WOOD, POM_f_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_f_FFUEL_new, EC_f_FFUEL_age, ASOC_ng100,  &
      ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100,  &
      NON_C_BSOA_ug1, NON_C_BSOA_ug10, NON_C_BSOA_ug1e2,  &
      NON_C_BSOA_ug1e3, FFIRE_OM, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    BSOA_GROUP = (/  &
      SQT_SOA_NV, BSOC_ng100, BSOC_ug1, BSOC_ug10, BSOC_ug1e2,  &
      BSOC_ug1e3, NON_C_BSOA_ng100, NON_C_BSOA_ug1,  &
      NON_C_BSOA_ug10, NON_C_BSOA_ug1e2, NON_C_BSOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    WDEP_BSOA_GROUP = (/  &
      SQT_SOA_NV, BSOC_ng100, BSOC_ug1, BSOC_ug10, BSOC_ug1e2,  &
      BSOC_ug1e3, NON_C_BSOA_ng100, NON_C_BSOA_ug1,  &
      NON_C_BSOA_ug10, NON_C_BSOA_ug1e2, NON_C_BSOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_BSOA_GROUP = (/  &
      SQT_SOA_NV, BSOC_ng100, BSOC_ug1, BSOC_ug10, BSOC_ug1e2,  &
      BSOC_ug1e3, NON_C_BSOA_ng100, NON_C_BSOA_ug1,  &
      NON_C_BSOA_ug10, NON_C_BSOA_ug1e2, NON_C_BSOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (7) :: &
    PPM25_GROUP = (/  &
      POM_f_WOOD, POM_f_FFUEL, EC_f_WOOD_new, EC_f_WOOD_age,  &
      EC_f_FFUEL_new, EC_f_FFUEL_age, REMPPM25  &
    /)
  
  integer, public, target, save, dimension (7) :: &
    WDEP_PPM25_GROUP = (/  &
      POM_f_WOOD, POM_f_FFUEL, EC_f_WOOD_new, EC_f_WOOD_age,  &
      EC_f_FFUEL_new, EC_f_FFUEL_age, REMPPM25  &
    /)
  
  integer, public, target, save, dimension (7) :: &
    DDEP_PPM25_GROUP = (/  &
      POM_f_WOOD, POM_f_FFUEL, EC_f_WOOD_new, EC_f_WOOD_age,  &
      EC_f_FFUEL_new, EC_f_FFUEL_age, REMPPM25  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    PPM10_GROUP = (/  &
      POM_f_WOOD, POM_f_FFUEL, POM_c_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new, EC_f_FFUEL_age,  &
      EC_c_FFUEL, REMPPM25, REMPPM_c  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    WDEP_PPM10_GROUP = (/  &
      POM_f_WOOD, POM_f_FFUEL, POM_c_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new, EC_f_FFUEL_age,  &
      EC_c_FFUEL, REMPPM25, REMPPM_c  &
    /)
  
  integer, public, target, save, dimension (11) :: &
    DDEP_PPM10_GROUP = (/  &
      POM_f_WOOD, POM_f_FFUEL, POM_c_FFUEL, EC_f_WOOD_new,  &
      EC_f_WOOD_age, EC_c_WOOD, EC_f_FFUEL_new, EC_f_FFUEL_age,  &
      EC_c_FFUEL, REMPPM25, REMPPM_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    NVWOODOC25_GROUP = (/ POM_f_WOOD /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVWOODOC25_GROUP = (/ POM_f_WOOD /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVWOODOC25_GROUP = (/ POM_f_WOOD /)
  
  integer, public, target, save, dimension (1) :: &
    NVFFUELOC25_GROUP = (/ POM_f_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVFFUELOC25_GROUP = (/ POM_f_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVFFUELOC25_GROUP = (/ POM_f_FFUEL /)
  
  integer, public, target, save, dimension (4) :: &
    PPM_C_GROUP = (/ POM_c_FFUEL, EC_c_WOOD, EC_c_FFUEL, REMPPM_c /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_PPM_c_GROUP = (/ POM_c_FFUEL, EC_c_WOOD, EC_c_FFUEL, REMPPM_c /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_PPM_c_GROUP = (/ POM_c_FFUEL, EC_c_WOOD, EC_c_FFUEL, REMPPM_c /)
  
  integer, public, target, save, dimension (3) :: &
    PM10ANTHR_GROUP = (/ POM_c_FFUEL, EC_c_WOOD, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_PM10anthr_GROUP = (/ POM_c_FFUEL, EC_c_WOOD, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_PM10anthr_GROUP = (/ POM_c_FFUEL, EC_c_WOOD, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    NVFFUELOC_COARSE_GROUP = (/ POM_c_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVFFUELOC_COARSE_GROUP = (/ POM_c_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVFFUELOC_COARSE_GROUP = (/ POM_c_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    OMCOARSE_GROUP = (/ POM_c_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_OMCOARSE_GROUP = (/ POM_c_FFUEL /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_OMCOARSE_GROUP = (/ POM_c_FFUEL /)
  
  integer, public, target, save, dimension (5) :: &
    EC_F_GROUP = (/  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_EC_f_GROUP = (/  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_EC_f_GROUP = (/  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (3) :: &
    WOODEC_GROUP = (/ EC_f_WOOD_new, EC_f_WOOD_age, EC_c_WOOD /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_WOODEC_GROUP = (/ EC_f_WOOD_new, EC_f_WOOD_age, EC_c_WOOD /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_WOODEC_GROUP = (/ EC_f_WOOD_new, EC_f_WOOD_age, EC_c_WOOD /)
  
  integer, public, target, save, dimension (2) :: &
    WOODECFINE_GROUP = (/ EC_f_WOOD_new, EC_f_WOOD_age /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_woodECfine_GROUP = (/ EC_f_WOOD_new, EC_f_WOOD_age /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_woodECfine_GROUP = (/ EC_f_WOOD_new, EC_f_WOOD_age /)
  
  integer, public, target, save, dimension (5) :: &
    ECFINE_GROUP = (/  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    WDEP_ECFINE_GROUP = (/  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (5) :: &
    DDEP_ECFINE_GROUP = (/  &
      EC_f_WOOD_new, EC_f_WOOD_age, EC_f_FFUEL_new,  &
      EC_f_FFUEL_age, FFIRE_BC  &
    /)
  
  integer, public, target, save, dimension (2) :: &
    ECCOARSE_GROUP = (/ EC_c_WOOD, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_ECCOARSE_GROUP = (/ EC_c_WOOD, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_ECCOARSE_GROUP = (/ EC_c_WOOD, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (3) :: &
    FFUELEC_GROUP = (/ EC_f_FFUEL_new, EC_f_FFUEL_age, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_FFUELEC_GROUP = (/ EC_f_FFUEL_new, EC_f_FFUEL_age, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_FFUELEC_GROUP = (/ EC_f_FFUEL_new, EC_f_FFUEL_age, EC_c_FFUEL /)
  
  integer, public, target, save, dimension (2) :: &
    FFUELECFINE_GROUP = (/ EC_f_FFUEL_new, EC_f_FFUEL_age /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_ffuelECfine_GROUP = (/ EC_f_FFUEL_new, EC_f_FFUEL_age /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_ffuelECfine_GROUP = (/ EC_f_FFUEL_new, EC_f_FFUEL_age /)
  
  integer, public, target, save, dimension (3) :: &
    OC_GROUP = (/ OM25_p, VBS_TEST, FFIRE_OM /)
  
  integer, public, target, save, dimension (10) :: &
    ASOA_GROUP = (/  &
      ASOC_ng100, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    WDEP_ASOA_GROUP = (/  &
      ASOC_ng100, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (10) :: &
    DDEP_ASOA_GROUP = (/  &
      ASOC_ng100, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    PFFUELOA25_GROUP = (/ FFFUEL_ng10 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_PFFUELOA25_GROUP = (/ FFFUEL_ng10 /)
  
  integer, public, target, save, dimension (1) :: &
    SVFFUELOA25_GROUP = (/ FFFUEL_ng10 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_SVFFUELOA25_GROUP = (/ FFFUEL_ng10 /)
  
  integer, public, target, save, dimension (1) :: &
    PWOODOA25_GROUP = (/ WOODOA_ng10 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_PWOODOA25_GROUP = (/ WOODOA_ng10 /)
  
  integer, public, target, save, dimension (1) :: &
    SVWOODOA25_GROUP = (/ WOODOA_ng10 /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_SVWOODOA25_GROUP = (/ WOODOA_ng10 /)
  
  integer, public, target, save, dimension (2) :: &
    ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_ASH_GROUP = (/ Ash_f, Ash_c /)
  
  integer, public, target, save, dimension (1) :: &
    TMPX_GROUP = (/ SHIPNOX /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_TMPX_GROUP = (/ SHIPNOX /)
  
  integer, public, target, save, dimension (1) :: &
    TRACER_GROUP = (/ FFIRE_CO /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_OC_GROUP = (/ FFIRE_OM /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_OC_GROUP = (/ FFIRE_OM /)
  
  integer, public, target, save, dimension (3) :: &
    PPM25_FIRE_GROUP = (/ FFIRE_OM, FFIRE_BC, FFIRE_REMPPM25 /)
  
  integer, public, target, save, dimension (3) :: &
    WDEP_PPM25_FIRE_GROUP = (/ FFIRE_OM, FFIRE_BC, FFIRE_REMPPM25 /)
  
  integer, public, target, save, dimension (3) :: &
    DDEP_PPM25_FIRE_GROUP = (/ FFIRE_OM, FFIRE_BC, FFIRE_REMPPM25 /)
  
  integer, public, target, save, dimension (1) :: &
    NVFFIREOC25_GROUP = (/ FFIRE_OM /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_NVFFIREOC25_GROUP = (/ FFIRE_OM /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_NVFFIREOC25_GROUP = (/ FFIRE_OM /)
  
  integer, public, target, save, dimension (4) :: &
    PPM10_FIRE_GROUP = (/ FFIRE_OM, FFIRE_BC, FFIRE_REMPPM25, ffire_c /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_PPM10_fire_GROUP = (/ FFIRE_OM, FFIRE_BC, FFIRE_REMPPM25, ffire_c /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_PPM10_fire_GROUP = (/ FFIRE_OM, FFIRE_BC, FFIRE_REMPPM25, ffire_c /)
  
  integer, public, target, save, dimension (1) :: &
    FFIREBC_GROUP = (/ FFIRE_BC /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_FFIREBC_GROUP = (/ FFIRE_BC /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_FFIREBC_GROUP = (/ FFIRE_BC /)
  
  integer, public, target, save, dimension (2) :: &
    SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_SS_GROUP = (/ SeaSalt_f, SeaSalt_c /)
  
  integer, public, target, save, dimension (6) :: &
    DUST_GROUP = (/  &
      Dust_ROAD_f, Dust_ROAD_c, Dust_WB_f, Dust_WB_c, Dust_SAH_f,  &
      Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    WDEP_DUST_GROUP = (/  &
      Dust_ROAD_f, Dust_ROAD_c, Dust_WB_f, Dust_WB_c, Dust_SAH_f,  &
      Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (6) :: &
    DDEP_DUST_GROUP = (/  &
      Dust_ROAD_f, Dust_ROAD_c, Dust_WB_f, Dust_WB_c, Dust_SAH_f,  &
      Dust_SAH_c  &
    /)
  
  integer, public, target, save, dimension (1) :: &
    DUST_ANT_F_GROUP = (/ Dust_ROAD_f /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DUST_ANT_F_GROUP = (/ Dust_ROAD_f /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DUST_ANT_F_GROUP = (/ Dust_ROAD_f /)
  
  integer, public, target, save, dimension (1) :: &
    DUST_ANT_C_GROUP = (/ Dust_ROAD_c /)
  
  integer, public, target, save, dimension (1) :: &
    WDEP_DUST_ANT_C_GROUP = (/ Dust_ROAD_c /)
  
  integer, public, target, save, dimension (1) :: &
    DDEP_DUST_ANT_C_GROUP = (/ Dust_ROAD_c /)
  
  integer, public, target, save, dimension (2) :: &
    DUST_NAT_F_GROUP = (/ Dust_WB_f, Dust_SAH_f /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DUST_NAT_F_GROUP = (/ Dust_WB_f, Dust_SAH_f /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DUST_NAT_F_GROUP = (/ Dust_WB_f, Dust_SAH_f /)
  
  integer, public, target, save, dimension (2) :: &
    DUST_NAT_C_GROUP = (/ Dust_WB_c, Dust_SAH_c /)
  
  integer, public, target, save, dimension (2) :: &
    WDEP_DUST_NAT_C_GROUP = (/ Dust_WB_c, Dust_SAH_c /)
  
  integer, public, target, save, dimension (2) :: &
    DDEP_DUST_NAT_C_GROUP = (/ Dust_WB_c, Dust_SAH_c /)
  
  integer, public, target, save, dimension (4) :: &
    POLLEN_GROUP = (/ POLLEN_BIRCH, POLLEN_OLIVE, POLLEN_RWEED, POLLEN_GRASS /)
  
  integer, public, target, save, dimension (4) :: &
    WDEP_POLLEN_GROUP = (/ POLLEN_BIRCH, POLLEN_OLIVE, POLLEN_RWEED, POLLEN_GRASS /)
  
  integer, public, target, save, dimension (4) :: &
    DDEP_POLLEN_GROUP = (/ POLLEN_BIRCH, POLLEN_OLIVE, POLLEN_RWEED, POLLEN_GRASS /)
  
  integer, public, target, save, dimension (22) :: &
    CSTAR_GROUP = (/  &
      ASOC_ng100, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100,  &
      NON_C_BSOA_ug1, NON_C_BSOA_ug10, NON_C_BSOA_ug1e2,  &
      NON_C_BSOA_ug1e3, FFFUEL_ng10, WOODOA_ng10  &
    /)
  
  real, public, target, save, dimension (22) :: &
    CSTAR_GROUP_FACTORS = (/  &
      0.1, 1.0, 10.0, 1.0e2, 1.0e3, 0.1, 1.0, 10.0, 1.0e2, 1.0e3,  &
      0.1, 1.0, 10.0, 1.0e2, 1.0e3, 0.1, 1.0, 10.0, 1.0e2, 1.0e3,  &
      0.01, 0.01  &
    /)
  
  integer, public, target, save, dimension (22) :: &
    DELTAH_GROUP = (/  &
      ASOC_ng100, ASOC_ug1, ASOC_ug10, ASOC_ug1e2, ASOC_ug1e3,  &
      NON_C_ASOA_ng100, NON_C_ASOA_ug1, NON_C_ASOA_ug10,  &
      NON_C_ASOA_ug1e2, NON_C_ASOA_ug1e3, BSOC_ng100, BSOC_ug1,  &
      BSOC_ug10, BSOC_ug1e2, BSOC_ug1e3, NON_C_BSOA_ng100,  &
      NON_C_BSOA_ug1, NON_C_BSOA_ug10, NON_C_BSOA_ug1e2,  &
      NON_C_BSOA_ug1e3, FFFUEL_ng10, WOODOA_ng10  &
    /)
  
  real, public, target, save, dimension (22) :: &
    DELTAH_GROUP_FACTORS = (/  &
      30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0,  &
      30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0,  &
      112.0, 112.0  &
    /)
  
  integer, public, target, save, dimension (24) :: &
    EXTINC_GROUP = (/  &
      SO4, NO3_f, NO3_c, NH4_f, EC_f_WOOD_new, EC_f_WOOD_age,  &
      EC_c_WOOD, EC_f_FFUEL_new, EC_f_FFUEL_age, EC_c_FFUEL,  &
      REMPPM25, REMPPM_c, OM25_p, FFIRE_BC, FFIRE_REMPPM25,  &
      ffire_c, SeaSalt_f, SeaSalt_c, Dust_ROAD_f, Dust_ROAD_c,  &
      Dust_WB_f, Dust_WB_c, Dust_SAH_f, Dust_SAH_c  &
    /)
  
  character(len=TXTLEN_SHORT), public, target, save, dimension (24) :: &
    EXTINC_GROUP_MAPBACK = [ character(len=TXTLEN_SHORT) :: &
    "SO4", "NO3f", "NO3c", "NH4f", "ECn", "ECa", "EC", "ECn",  &
      "ECa", "EC", "DDf", "DDc", "OC", "EC", "DDf", "DDc", "SSf",  &
      "SSc", "DDf", "DDc", "DDf", "DDc", "DDf", "DDc"  &
    ]

contains
  
  subroutine Init_ChemGroups()
    
    chemgroups(1)%name="RO2"
    chemgroups(1)%specs=>RO2_GROUP
    
    chemgroups(2)%name="DAOBS"
    chemgroups(2)%specs=>DAOBS_GROUP
    
    chemgroups(3)%name="DDEP_daObs"
    chemgroups(3)%specs=>DDEP_daObs_GROUP
    
    chemgroups(4)%name="OX"
    chemgroups(4)%specs=>OX_GROUP
    
    chemgroups(5)%name="DDEP_OX"
    chemgroups(5)%specs=>DDEP_OX_GROUP
    
    chemgroups(6)%name="NOX"
    chemgroups(6)%specs=>NOX_GROUP
    
    chemgroups(7)%name="OXN"
    chemgroups(7)%specs=>OXN_GROUP
    
    chemgroups(8)%name="DDEP_NOX"
    chemgroups(8)%specs=>DDEP_NOX_GROUP
    
    chemgroups(9)%name="DDEP_OXN"
    chemgroups(9)%specs=>DDEP_OXN_GROUP
    
    chemgroups(10)%name="PAN"
    chemgroups(10)%specs=>PAN_GROUP
    
    chemgroups(11)%name="DDEP_PAN"
    chemgroups(11)%specs=>DDEP_PAN_GROUP
    
    chemgroups(12)%name="HSTAR_3P0E0"
    chemgroups(12)%specs=>HSTAR_3P0E0_GROUP
    
    chemgroups(13)%name="DDEP_Hstar_3p0e0"
    chemgroups(13)%specs=>DDEP_Hstar_3p0e0_GROUP
    
    chemgroups(14)%name="F0_0P5"
    chemgroups(14)%specs=>F0_0P5_GROUP
    
    chemgroups(15)%name="DDEP_f0_0p5"
    chemgroups(15)%specs=>DDEP_f0_0p5_GROUP
    
    chemgroups(16)%name="DRX_2P8"
    chemgroups(16)%specs=>DRX_2P8_GROUP
    
    chemgroups(17)%name="DDEP_DRx_2p8"
    chemgroups(17)%specs=>DDEP_DRx_2p8_GROUP
    
    chemgroups(18)%name="DRX_3P4"
    chemgroups(18)%specs=>DRX_3P4_GROUP
    
    chemgroups(19)%name="DDEP_DRx_3p4"
    chemgroups(19)%specs=>DDEP_DRx_3p4_GROUP
    
    chemgroups(20)%name="WDEP_OXN"
    chemgroups(20)%specs=>WDEP_OXN_GROUP
    
    chemgroups(21)%name="HSTAR_2P6E5"
    chemgroups(21)%specs=>HSTAR_2P6E5_GROUP
    
    chemgroups(22)%name="WDEP_Hstar_2p6e5"
    chemgroups(22)%specs=>WDEP_Hstar_2p6e5_GROUP
    
    chemgroups(23)%name="DDEP_Hstar_2p6e5"
    chemgroups(23)%specs=>DDEP_Hstar_2p6e5_GROUP
    
    chemgroups(24)%name="WDEP_f0_0p5"
    chemgroups(24)%specs=>WDEP_f0_0p5_GROUP
    
    chemgroups(25)%name="DRX_1P6"
    chemgroups(25)%specs=>DRX_1P6_GROUP
    
    chemgroups(26)%name="WDEP_DRx_1p6"
    chemgroups(26)%specs=>WDEP_DRx_1p6_GROUP
    
    chemgroups(27)%name="DDEP_DRx_1p6"
    chemgroups(27)%specs=>DDEP_DRx_1p6_GROUP
    
    chemgroups(28)%name="HSTAR_6P0E4"
    chemgroups(28)%specs=>HSTAR_6P0E4_GROUP
    
    chemgroups(29)%name="WDEP_Hstar_6p0e4"
    chemgroups(29)%specs=>WDEP_Hstar_6p0e4_GROUP
    
    chemgroups(30)%name="DDEP_Hstar_6p0e4"
    chemgroups(30)%specs=>DDEP_Hstar_6p0e4_GROUP
    
    chemgroups(31)%name="F0_1P0"
    chemgroups(31)%specs=>F0_1P0_GROUP
    
    chemgroups(32)%name="WDEP_f0_1p0"
    chemgroups(32)%specs=>WDEP_f0_1p0_GROUP
    
    chemgroups(33)%name="DDEP_f0_1p0"
    chemgroups(33)%specs=>DDEP_f0_1p0_GROUP
    
    chemgroups(34)%name="DRX_2P1"
    chemgroups(34)%specs=>DRX_2P1_GROUP
    
    chemgroups(35)%name="WDEP_DRx_2p1"
    chemgroups(35)%specs=>WDEP_DRx_2p1_GROUP
    
    chemgroups(36)%name="DDEP_DRx_2p1"
    chemgroups(36)%specs=>DDEP_DRx_2p1_GROUP
    
    chemgroups(37)%name="RCHO"
    chemgroups(37)%specs=>RCHO_GROUP
    
    chemgroups(38)%name="DDEP_RCHO"
    chemgroups(38)%specs=>DDEP_RCHO_GROUP
    
    chemgroups(39)%name="HSTAR_5P0E0"
    chemgroups(39)%specs=>HSTAR_5P0E0_GROUP
    
    chemgroups(40)%name="DDEP_Hstar_5p0e0"
    chemgroups(40)%specs=>DDEP_Hstar_5p0e0_GROUP
    
    chemgroups(41)%name="F0_0P05"
    chemgroups(41)%specs=>F0_0P05_GROUP
    
    chemgroups(42)%name="DDEP_f0_0p05"
    chemgroups(42)%specs=>DDEP_f0_0p05_GROUP
    
    chemgroups(43)%name="DRX_2P6"
    chemgroups(43)%specs=>DRX_2P6_GROUP
    
    chemgroups(44)%name="DDEP_DRx_2p6"
    chemgroups(44)%specs=>DDEP_DRx_2p6_GROUP
    
    chemgroups(45)%name="NITRATE"
    chemgroups(45)%specs=>NITRATE_GROUP
    
    chemgroups(46)%name="WDEP_nitrate"
    chemgroups(46)%specs=>WDEP_nitrate_GROUP
    
    chemgroups(47)%name="DDEP_nitrate"
    chemgroups(47)%specs=>DDEP_nitrate_GROUP
    
    chemgroups(48)%name="HSTAR_5P0E4"
    chemgroups(48)%specs=>HSTAR_5P0E4_GROUP
    
    chemgroups(49)%name="WDEP_Hstar_5p0e4"
    chemgroups(49)%specs=>WDEP_Hstar_5p0e4_GROUP
    
    chemgroups(50)%name="DDEP_Hstar_5p0e4"
    chemgroups(50)%specs=>DDEP_Hstar_5p0e4_GROUP
    
    chemgroups(51)%name="F0_0P3"
    chemgroups(51)%specs=>F0_0P3_GROUP
    
    chemgroups(52)%name="WDEP_f0_0p3"
    chemgroups(52)%specs=>WDEP_f0_0p3_GROUP
    
    chemgroups(53)%name="DDEP_f0_0p3"
    chemgroups(53)%specs=>DDEP_f0_0p3_GROUP
    
    chemgroups(54)%name="DRX_3P6"
    chemgroups(54)%specs=>DRX_3P6_GROUP
    
    chemgroups(55)%name="WDEP_DRx_3p6"
    chemgroups(55)%specs=>WDEP_DRx_3p6_GROUP
    
    chemgroups(56)%name="DDEP_DRx_3p6"
    chemgroups(56)%specs=>DDEP_DRx_3p6_GROUP
    
    chemgroups(57)%name="WDEP_RCHO"
    chemgroups(57)%specs=>WDEP_RCHO_GROUP
    
    chemgroups(58)%name="HSTAR_3P0E5"
    chemgroups(58)%specs=>HSTAR_3P0E5_GROUP
    
    chemgroups(59)%name="WDEP_Hstar_3p0e5"
    chemgroups(59)%specs=>WDEP_Hstar_3p0e5_GROUP
    
    chemgroups(60)%name="DDEP_Hstar_3p0e5"
    chemgroups(60)%specs=>DDEP_Hstar_3p0e5_GROUP
    
    chemgroups(61)%name="CARBONYL"
    chemgroups(61)%specs=>CARBONYL_GROUP
    
    chemgroups(62)%name="WDEP_carbonyl"
    chemgroups(62)%specs=>WDEP_carbonyl_GROUP
    
    chemgroups(63)%name="DDEP_carbonyl"
    chemgroups(63)%specs=>DDEP_carbonyl_GROUP
    
    chemgroups(64)%name="HSTAR_2P4E4"
    chemgroups(64)%specs=>HSTAR_2P4E4_GROUP
    
    chemgroups(65)%name="WDEP_Hstar_2p4e4"
    chemgroups(65)%specs=>WDEP_Hstar_2p4e4_GROUP
    
    chemgroups(66)%name="DDEP_Hstar_2p4e4"
    chemgroups(66)%specs=>DDEP_Hstar_2p4e4_GROUP
    
    chemgroups(67)%name="F0_0P2"
    chemgroups(67)%specs=>F0_0P2_GROUP
    
    chemgroups(68)%name="WDEP_f0_0p2"
    chemgroups(68)%specs=>WDEP_f0_0p2_GROUP
    
    chemgroups(69)%name="DDEP_f0_0p2"
    chemgroups(69)%specs=>DDEP_f0_0p2_GROUP
    
    chemgroups(70)%name="DRX_2P5"
    chemgroups(70)%specs=>DRX_2P5_GROUP
    
    chemgroups(71)%name="WDEP_DRx_2p5"
    chemgroups(71)%specs=>WDEP_DRx_2p5_GROUP
    
    chemgroups(72)%name="DDEP_DRx_2p5"
    chemgroups(72)%specs=>DDEP_DRx_2p5_GROUP
    
    chemgroups(73)%name="HSTAR_6P0E5"
    chemgroups(73)%specs=>HSTAR_6P0E5_GROUP
    
    chemgroups(74)%name="WDEP_Hstar_6p0e5"
    chemgroups(74)%specs=>WDEP_Hstar_6p0e5_GROUP
    
    chemgroups(75)%name="DDEP_Hstar_6p0e5"
    chemgroups(75)%specs=>DDEP_Hstar_6p0e5_GROUP
    
    chemgroups(76)%name="DRX_3P1"
    chemgroups(76)%specs=>DRX_3P1_GROUP
    
    chemgroups(77)%name="WDEP_DRx_3p1"
    chemgroups(77)%specs=>WDEP_DRx_3p1_GROUP
    
    chemgroups(78)%name="DDEP_DRx_3p1"
    chemgroups(78)%specs=>DDEP_DRx_3p1_GROUP
    
    chemgroups(79)%name="HSTAR_2P0E1"
    chemgroups(79)%specs=>HSTAR_2P0E1_GROUP
    
    chemgroups(80)%name="DDEP_Hstar_2p0e1"
    chemgroups(80)%specs=>DDEP_Hstar_2p0e1_GROUP
    
    chemgroups(81)%name="DRX_2P7"
    chemgroups(81)%specs=>DRX_2P7_GROUP
    
    chemgroups(82)%name="DDEP_DRx_2p7"
    chemgroups(82)%specs=>DDEP_DRx_2p7_GROUP
    
    chemgroups(83)%name="HSTAR_3P2E3"
    chemgroups(83)%specs=>HSTAR_3P2E3_GROUP
    
    chemgroups(84)%name="WDEP_Hstar_3p2e3"
    chemgroups(84)%specs=>WDEP_Hstar_3p2e3_GROUP
    
    chemgroups(85)%name="DDEP_Hstar_3p2e3"
    chemgroups(85)%specs=>DDEP_Hstar_3p2e3_GROUP
    
    chemgroups(86)%name="DRX_1P4"
    chemgroups(86)%specs=>DRX_1P4_GROUP
    
    chemgroups(87)%name="WDEP_DRx_1p4"
    chemgroups(87)%specs=>WDEP_DRx_1p4_GROUP
    
    chemgroups(88)%name="DDEP_DRx_1p4"
    chemgroups(88)%specs=>DDEP_DRx_1p4_GROUP
    
    chemgroups(89)%name="HSTAR_1P3E1"
    chemgroups(89)%specs=>HSTAR_1P3E1_GROUP
    
    chemgroups(90)%name="DDEP_Hstar_1p3e1"
    chemgroups(90)%specs=>DDEP_Hstar_1p3e1_GROUP
    
    chemgroups(91)%name="BVOC"
    chemgroups(91)%specs=>BVOC_GROUP
    
    chemgroups(92)%name="MONOTERP"
    chemgroups(92)%specs=>MONOTERP_GROUP
    
    chemgroups(93)%name="ROOH"
    chemgroups(93)%specs=>ROOH_GROUP
    
    chemgroups(94)%name="DDEP_ROOH"
    chemgroups(94)%specs=>DDEP_ROOH_GROUP
    
    chemgroups(95)%name="HSTAR_3P0E2"
    chemgroups(95)%specs=>HSTAR_3P0E2_GROUP
    
    chemgroups(96)%name="DDEP_Hstar_3p0e2"
    chemgroups(96)%specs=>DDEP_Hstar_3p0e2_GROUP
    
    chemgroups(97)%name="DRX_1P9"
    chemgroups(97)%specs=>DRX_1P9_GROUP
    
    chemgroups(98)%name="DDEP_DRx_1p9"
    chemgroups(98)%specs=>DDEP_DRx_1p9_GROUP
    
    chemgroups(99)%name="HSTAR_3P3E2"
    chemgroups(99)%specs=>HSTAR_3P3E2_GROUP
    
    chemgroups(100)%name="DDEP_Hstar_3p3e2"
    chemgroups(100)%specs=>DDEP_Hstar_3p3e2_GROUP
    
    chemgroups(101)%name="DRX_2P3"
    chemgroups(101)%specs=>DRX_2P3_GROUP
    
    chemgroups(102)%name="DDEP_DRx_2p3"
    chemgroups(102)%specs=>DDEP_DRx_2p3_GROUP
    
    chemgroups(103)%name="HSTAR_6P2E1"
    chemgroups(103)%specs=>HSTAR_6P2E1_GROUP
    
    chemgroups(104)%name="DDEP_Hstar_6p2e1"
    chemgroups(104)%specs=>DDEP_Hstar_6p2e1_GROUP
    
    chemgroups(105)%name="DRX_3P0"
    chemgroups(105)%specs=>DRX_3P0_GROUP
    
    chemgroups(106)%name="DDEP_DRx_3p0"
    chemgroups(106)%specs=>DDEP_DRx_3p0_GROUP
    
    chemgroups(107)%name="WDEP_ROOH"
    chemgroups(107)%specs=>WDEP_ROOH_GROUP
    
    chemgroups(108)%name="HSTAR_1P3E6"
    chemgroups(108)%specs=>HSTAR_1P3E6_GROUP
    
    chemgroups(109)%name="WDEP_Hstar_1p3e6"
    chemgroups(109)%specs=>WDEP_Hstar_1p3e6_GROUP
    
    chemgroups(110)%name="DDEP_Hstar_1p3e6"
    chemgroups(110)%specs=>DDEP_Hstar_1p3e6_GROUP
    
    chemgroups(111)%name="HSTAR_1P4E8"
    chemgroups(111)%specs=>HSTAR_1P4E8_GROUP
    
    chemgroups(112)%name="WDEP_Hstar_1p4e8"
    chemgroups(112)%specs=>WDEP_Hstar_1p4e8_GROUP
    
    chemgroups(113)%name="DDEP_Hstar_1p4e8"
    chemgroups(113)%specs=>DDEP_Hstar_1p4e8_GROUP
    
    chemgroups(114)%name="DRX_4P1"
    chemgroups(114)%specs=>DRX_4P1_GROUP
    
    chemgroups(115)%name="WDEP_DRx_4p1"
    chemgroups(115)%specs=>WDEP_DRx_4p1_GROUP
    
    chemgroups(116)%name="DDEP_DRx_4p1"
    chemgroups(116)%specs=>DDEP_DRx_4p1_GROUP
    
    chemgroups(117)%name="HSTAR_9P0E4"
    chemgroups(117)%specs=>HSTAR_9P0E4_GROUP
    
    chemgroups(118)%name="WDEP_Hstar_9p0e4"
    chemgroups(118)%specs=>WDEP_Hstar_9p0e4_GROUP
    
    chemgroups(119)%name="DDEP_Hstar_9p0e4"
    chemgroups(119)%specs=>DDEP_Hstar_9p0e4_GROUP
    
    chemgroups(120)%name="HSTAR_1P6E8"
    chemgroups(120)%specs=>HSTAR_1P6E8_GROUP
    
    chemgroups(121)%name="WDEP_Hstar_1p6e8"
    chemgroups(121)%specs=>WDEP_Hstar_1p6e8_GROUP
    
    chemgroups(122)%name="DDEP_Hstar_1p6e8"
    chemgroups(122)%specs=>DDEP_Hstar_1p6e8_GROUP
    
    chemgroups(123)%name="DRX_3P55"
    chemgroups(123)%specs=>DRX_3P55_GROUP
    
    chemgroups(124)%name="WDEP_DRx_3p55"
    chemgroups(124)%specs=>WDEP_DRx_3p55_GROUP
    
    chemgroups(125)%name="DDEP_DRx_3p55"
    chemgroups(125)%specs=>DDEP_DRx_3p55_GROUP
    
    chemgroups(126)%name="DRX_3P2"
    chemgroups(126)%specs=>DRX_3P2_GROUP
    
    chemgroups(127)%name="WDEP_DRx_3p2"
    chemgroups(127)%specs=>WDEP_DRx_3p2_GROUP
    
    chemgroups(128)%name="DDEP_DRx_3p2"
    chemgroups(128)%specs=>DDEP_DRx_3p2_GROUP
    
    chemgroups(129)%name="HSTAR_3P5E8"
    chemgroups(129)%specs=>HSTAR_3P5E8_GROUP
    
    chemgroups(130)%name="WDEP_Hstar_3p5e8"
    chemgroups(130)%specs=>WDEP_Hstar_3p5e8_GROUP
    
    chemgroups(131)%name="DDEP_Hstar_3p5e8"
    chemgroups(131)%specs=>DDEP_Hstar_3p5e8_GROUP
    
    chemgroups(132)%name="PEROXYACID"
    chemgroups(132)%specs=>PEROXYACID_GROUP
    
    chemgroups(133)%name="DDEP_peroxyacid"
    chemgroups(133)%specs=>DDEP_peroxyacid_GROUP
    
    chemgroups(134)%name="HSTAR_8P3E2"
    chemgroups(134)%specs=>HSTAR_8P3E2_GROUP
    
    chemgroups(135)%name="DDEP_Hstar_8p3e2"
    chemgroups(135)%specs=>DDEP_Hstar_8p3e2_GROUP
    
    chemgroups(136)%name="DRX_2P4"
    chemgroups(136)%specs=>DRX_2P4_GROUP
    
    chemgroups(137)%name="DDEP_DRx_2p4"
    chemgroups(137)%specs=>DDEP_DRx_2p4_GROUP
    
    chemgroups(138)%name="HYDROXYKETONE"
    chemgroups(138)%specs=>HYDROXYKETONE_GROUP
    
    chemgroups(139)%name="WDEP_hydroxyketone"
    chemgroups(139)%specs=>WDEP_hydroxyketone_GROUP
    
    chemgroups(140)%name="DDEP_hydroxyketone"
    chemgroups(140)%specs=>DDEP_hydroxyketone_GROUP
    
    chemgroups(141)%name="HSTAR_8P0E3"
    chemgroups(141)%specs=>HSTAR_8P0E3_GROUP
    
    chemgroups(142)%name="WDEP_Hstar_8p0e3"
    chemgroups(142)%specs=>WDEP_Hstar_8p0e3_GROUP
    
    chemgroups(143)%name="DDEP_Hstar_8p0e3"
    chemgroups(143)%specs=>DDEP_Hstar_8p0e3_GROUP
    
    chemgroups(144)%name="WDEP_f0_0p05"
    chemgroups(144)%specs=>WDEP_f0_0p05_GROUP
    
    chemgroups(145)%name="WDEP_DRx_2p6"
    chemgroups(145)%specs=>WDEP_DRx_2p6_GROUP
    
    chemgroups(146)%name="HSTAR_5P5E3"
    chemgroups(146)%specs=>HSTAR_5P5E3_GROUP
    
    chemgroups(147)%name="WDEP_Hstar_5p5e3"
    chemgroups(147)%specs=>WDEP_Hstar_5p5e3_GROUP
    
    chemgroups(148)%name="DDEP_Hstar_5p5e3"
    chemgroups(148)%specs=>DDEP_Hstar_5p5e3_GROUP
    
    chemgroups(149)%name="WDEP_DRx_2p7"
    chemgroups(149)%specs=>WDEP_DRx_2p7_GROUP
    
    chemgroups(150)%name="HSTAR_1P2E5"
    chemgroups(150)%specs=>HSTAR_1P2E5_GROUP
    
    chemgroups(151)%name="WDEP_Hstar_1p2e5"
    chemgroups(151)%specs=>WDEP_Hstar_1p2e5_GROUP
    
    chemgroups(152)%name="DDEP_Hstar_1p2e5"
    chemgroups(152)%specs=>DDEP_Hstar_1p2e5_GROUP
    
    chemgroups(153)%name="DRX_3P3"
    chemgroups(153)%specs=>DRX_3P3_GROUP
    
    chemgroups(154)%name="WDEP_DRx_3p3"
    chemgroups(154)%specs=>WDEP_DRx_3p3_GROUP
    
    chemgroups(155)%name="DDEP_DRx_3p3"
    chemgroups(155)%specs=>DDEP_DRx_3p3_GROUP
    
    chemgroups(156)%name="WDEP_peroxyacid"
    chemgroups(156)%specs=>WDEP_peroxyacid_GROUP
    
    chemgroups(157)%name="HSTAR_1P5E6"
    chemgroups(157)%specs=>HSTAR_1P5E6_GROUP
    
    chemgroups(158)%name="WDEP_Hstar_1p5e6"
    chemgroups(158)%specs=>WDEP_Hstar_1p5e6_GROUP
    
    chemgroups(159)%name="DDEP_Hstar_1p5e6"
    chemgroups(159)%specs=>DDEP_Hstar_1p5e6_GROUP
    
    chemgroups(160)%name="DRX_3P47"
    chemgroups(160)%specs=>DRX_3P47_GROUP
    
    chemgroups(161)%name="WDEP_DRx_3p47"
    chemgroups(161)%specs=>WDEP_DRx_3p47_GROUP
    
    chemgroups(162)%name="DDEP_DRx_3p47"
    chemgroups(162)%specs=>DDEP_DRx_3p47_GROUP
    
    chemgroups(163)%name="EPOXIDE"
    chemgroups(163)%specs=>EPOXIDE_GROUP
    
    chemgroups(164)%name="WDEP_epoxide"
    chemgroups(164)%specs=>WDEP_epoxide_GROUP
    
    chemgroups(165)%name="DDEP_epoxide"
    chemgroups(165)%specs=>DDEP_epoxide_GROUP
    
    chemgroups(166)%name="SOX"
    chemgroups(166)%specs=>SOX_GROUP
    
    chemgroups(167)%name="WDEP_SOX"
    chemgroups(167)%specs=>WDEP_SOX_GROUP
    
    chemgroups(168)%name="DDEP_SOX"
    chemgroups(168)%specs=>DDEP_SOX_GROUP
    
    chemgroups(169)%name="PM10"
    chemgroups(169)%specs=>PM10_GROUP
    
    chemgroups(170)%name="WDEP_PM10"
    chemgroups(170)%specs=>WDEP_PM10_GROUP
    
    chemgroups(171)%name="DDEP_PM10"
    chemgroups(171)%specs=>DDEP_PM10_GROUP
    
    chemgroups(172)%name="PMFINE"
    chemgroups(172)%specs=>PMFINE_GROUP
    
    chemgroups(173)%name="WDEP_PMFINE"
    chemgroups(173)%specs=>WDEP_PMFINE_GROUP
    
    chemgroups(174)%name="DDEP_PMFINE"
    chemgroups(174)%specs=>DDEP_PMFINE_GROUP
    
    chemgroups(175)%name="SIA"
    chemgroups(175)%specs=>SIA_GROUP
    
    chemgroups(176)%name="WDEP_SIA"
    chemgroups(176)%specs=>WDEP_SIA_GROUP
    
    chemgroups(177)%name="DDEP_SIA"
    chemgroups(177)%specs=>DDEP_SIA_GROUP
    
    chemgroups(178)%name="RDN"
    chemgroups(178)%specs=>RDN_GROUP
    
    chemgroups(179)%name="WDEP_RDN"
    chemgroups(179)%specs=>WDEP_RDN_GROUP
    
    chemgroups(180)%name="DDEP_RDN"
    chemgroups(180)%specs=>DDEP_RDN_GROUP
    
    chemgroups(181)%name="TNO3"
    chemgroups(181)%specs=>TNO3_GROUP
    
    chemgroups(182)%name="WDEP_TNO3"
    chemgroups(182)%specs=>WDEP_TNO3_GROUP
    
    chemgroups(183)%name="DDEP_TNO3"
    chemgroups(183)%specs=>DDEP_TNO3_GROUP
    
    chemgroups(184)%name="PMCO"
    chemgroups(184)%specs=>PMCO_GROUP
    
    chemgroups(185)%name="WDEP_PMCO"
    chemgroups(185)%specs=>WDEP_PMCO_GROUP
    
    chemgroups(186)%name="DDEP_PMCO"
    chemgroups(186)%specs=>DDEP_PMCO_GROUP
    
    chemgroups(187)%name="NONVOLPCM"
    chemgroups(187)%specs=>NONVOLPCM_GROUP
    
    chemgroups(188)%name="WDEP_NONVOLPCM"
    chemgroups(188)%specs=>WDEP_NONVOLPCM_GROUP
    
    chemgroups(189)%name="DDEP_NONVOLPCM"
    chemgroups(189)%specs=>DDEP_NONVOLPCM_GROUP
    
    chemgroups(190)%name="NVABSOM"
    chemgroups(190)%specs=>NVABSOM_GROUP
    
    chemgroups(191)%name="WDEP_NVABSOM"
    chemgroups(191)%specs=>WDEP_NVABSOM_GROUP
    
    chemgroups(192)%name="DDEP_NVABSOM"
    chemgroups(192)%specs=>DDEP_NVABSOM_GROUP
    
    chemgroups(193)%name="OM25"
    chemgroups(193)%specs=>OM25_GROUP
    
    chemgroups(194)%name="WDEP_OM25"
    chemgroups(194)%specs=>WDEP_OM25_GROUP
    
    chemgroups(195)%name="DDEP_OM25"
    chemgroups(195)%specs=>DDEP_OM25_GROUP
    
    chemgroups(196)%name="PCM"
    chemgroups(196)%specs=>PCM_GROUP
    
    chemgroups(197)%name="WDEP_PCM"
    chemgroups(197)%specs=>WDEP_PCM_GROUP
    
    chemgroups(198)%name="DDEP_PCM"
    chemgroups(198)%specs=>DDEP_PCM_GROUP
    
    chemgroups(199)%name="BSOA"
    chemgroups(199)%specs=>BSOA_GROUP
    
    chemgroups(200)%name="WDEP_BSOA"
    chemgroups(200)%specs=>WDEP_BSOA_GROUP
    
    chemgroups(201)%name="DDEP_BSOA"
    chemgroups(201)%specs=>DDEP_BSOA_GROUP
    
    chemgroups(202)%name="PPM25"
    chemgroups(202)%specs=>PPM25_GROUP
    
    chemgroups(203)%name="WDEP_PPM25"
    chemgroups(203)%specs=>WDEP_PPM25_GROUP
    
    chemgroups(204)%name="DDEP_PPM25"
    chemgroups(204)%specs=>DDEP_PPM25_GROUP
    
    chemgroups(205)%name="PPM10"
    chemgroups(205)%specs=>PPM10_GROUP
    
    chemgroups(206)%name="WDEP_PPM10"
    chemgroups(206)%specs=>WDEP_PPM10_GROUP
    
    chemgroups(207)%name="DDEP_PPM10"
    chemgroups(207)%specs=>DDEP_PPM10_GROUP
    
    chemgroups(208)%name="NVWOODOC25"
    chemgroups(208)%specs=>NVWOODOC25_GROUP
    
    chemgroups(209)%name="WDEP_NVWOODOC25"
    chemgroups(209)%specs=>WDEP_NVWOODOC25_GROUP
    
    chemgroups(210)%name="DDEP_NVWOODOC25"
    chemgroups(210)%specs=>DDEP_NVWOODOC25_GROUP
    
    chemgroups(211)%name="NVFFUELOC25"
    chemgroups(211)%specs=>NVFFUELOC25_GROUP
    
    chemgroups(212)%name="WDEP_NVFFUELOC25"
    chemgroups(212)%specs=>WDEP_NVFFUELOC25_GROUP
    
    chemgroups(213)%name="DDEP_NVFFUELOC25"
    chemgroups(213)%specs=>DDEP_NVFFUELOC25_GROUP
    
    chemgroups(214)%name="PPM_C"
    chemgroups(214)%specs=>PPM_C_GROUP
    
    chemgroups(215)%name="WDEP_PPM_c"
    chemgroups(215)%specs=>WDEP_PPM_c_GROUP
    
    chemgroups(216)%name="DDEP_PPM_c"
    chemgroups(216)%specs=>DDEP_PPM_c_GROUP
    
    chemgroups(217)%name="PM10ANTHR"
    chemgroups(217)%specs=>PM10ANTHR_GROUP
    
    chemgroups(218)%name="WDEP_PM10anthr"
    chemgroups(218)%specs=>WDEP_PM10anthr_GROUP
    
    chemgroups(219)%name="DDEP_PM10anthr"
    chemgroups(219)%specs=>DDEP_PM10anthr_GROUP
    
    chemgroups(220)%name="NVFFUELOC_COARSE"
    chemgroups(220)%specs=>NVFFUELOC_COARSE_GROUP
    
    chemgroups(221)%name="WDEP_NVFFUELOC_COARSE"
    chemgroups(221)%specs=>WDEP_NVFFUELOC_COARSE_GROUP
    
    chemgroups(222)%name="DDEP_NVFFUELOC_COARSE"
    chemgroups(222)%specs=>DDEP_NVFFUELOC_COARSE_GROUP
    
    chemgroups(223)%name="OMCOARSE"
    chemgroups(223)%specs=>OMCOARSE_GROUP
    
    chemgroups(224)%name="WDEP_OMCOARSE"
    chemgroups(224)%specs=>WDEP_OMCOARSE_GROUP
    
    chemgroups(225)%name="DDEP_OMCOARSE"
    chemgroups(225)%specs=>DDEP_OMCOARSE_GROUP
    
    chemgroups(226)%name="EC_F"
    chemgroups(226)%specs=>EC_F_GROUP
    
    chemgroups(227)%name="WDEP_EC_f"
    chemgroups(227)%specs=>WDEP_EC_f_GROUP
    
    chemgroups(228)%name="DDEP_EC_f"
    chemgroups(228)%specs=>DDEP_EC_f_GROUP
    
    chemgroups(229)%name="WOODEC"
    chemgroups(229)%specs=>WOODEC_GROUP
    
    chemgroups(230)%name="WDEP_WOODEC"
    chemgroups(230)%specs=>WDEP_WOODEC_GROUP
    
    chemgroups(231)%name="DDEP_WOODEC"
    chemgroups(231)%specs=>DDEP_WOODEC_GROUP
    
    chemgroups(232)%name="WOODECFINE"
    chemgroups(232)%specs=>WOODECFINE_GROUP
    
    chemgroups(233)%name="WDEP_woodECfine"
    chemgroups(233)%specs=>WDEP_woodECfine_GROUP
    
    chemgroups(234)%name="DDEP_woodECfine"
    chemgroups(234)%specs=>DDEP_woodECfine_GROUP
    
    chemgroups(235)%name="ECFINE"
    chemgroups(235)%specs=>ECFINE_GROUP
    
    chemgroups(236)%name="WDEP_ECFINE"
    chemgroups(236)%specs=>WDEP_ECFINE_GROUP
    
    chemgroups(237)%name="DDEP_ECFINE"
    chemgroups(237)%specs=>DDEP_ECFINE_GROUP
    
    chemgroups(238)%name="ECCOARSE"
    chemgroups(238)%specs=>ECCOARSE_GROUP
    
    chemgroups(239)%name="WDEP_ECCOARSE"
    chemgroups(239)%specs=>WDEP_ECCOARSE_GROUP
    
    chemgroups(240)%name="DDEP_ECCOARSE"
    chemgroups(240)%specs=>DDEP_ECCOARSE_GROUP
    
    chemgroups(241)%name="FFUELEC"
    chemgroups(241)%specs=>FFUELEC_GROUP
    
    chemgroups(242)%name="WDEP_FFUELEC"
    chemgroups(242)%specs=>WDEP_FFUELEC_GROUP
    
    chemgroups(243)%name="DDEP_FFUELEC"
    chemgroups(243)%specs=>DDEP_FFUELEC_GROUP
    
    chemgroups(244)%name="FFUELECFINE"
    chemgroups(244)%specs=>FFUELECFINE_GROUP
    
    chemgroups(245)%name="WDEP_ffuelECfine"
    chemgroups(245)%specs=>WDEP_ffuelECfine_GROUP
    
    chemgroups(246)%name="DDEP_ffuelECfine"
    chemgroups(246)%specs=>DDEP_ffuelECfine_GROUP
    
    chemgroups(247)%name="OC"
    chemgroups(247)%specs=>OC_GROUP
    
    chemgroups(248)%name="ASOA"
    chemgroups(248)%specs=>ASOA_GROUP
    
    chemgroups(249)%name="WDEP_ASOA"
    chemgroups(249)%specs=>WDEP_ASOA_GROUP
    
    chemgroups(250)%name="DDEP_ASOA"
    chemgroups(250)%specs=>DDEP_ASOA_GROUP
    
    chemgroups(251)%name="PFFUELOA25"
    chemgroups(251)%specs=>PFFUELOA25_GROUP
    
    chemgroups(252)%name="WDEP_PFFUELOA25"
    chemgroups(252)%specs=>WDEP_PFFUELOA25_GROUP
    
    chemgroups(253)%name="SVFFUELOA25"
    chemgroups(253)%specs=>SVFFUELOA25_GROUP
    
    chemgroups(254)%name="WDEP_SVFFUELOA25"
    chemgroups(254)%specs=>WDEP_SVFFUELOA25_GROUP
    
    chemgroups(255)%name="PWOODOA25"
    chemgroups(255)%specs=>PWOODOA25_GROUP
    
    chemgroups(256)%name="WDEP_PWOODOA25"
    chemgroups(256)%specs=>WDEP_PWOODOA25_GROUP
    
    chemgroups(257)%name="SVWOODOA25"
    chemgroups(257)%specs=>SVWOODOA25_GROUP
    
    chemgroups(258)%name="WDEP_SVWOODOA25"
    chemgroups(258)%specs=>WDEP_SVWOODOA25_GROUP
    
    chemgroups(259)%name="ASH"
    chemgroups(259)%specs=>ASH_GROUP
    
    chemgroups(260)%name="WDEP_ASH"
    chemgroups(260)%specs=>WDEP_ASH_GROUP
    
    chemgroups(261)%name="DDEP_ASH"
    chemgroups(261)%specs=>DDEP_ASH_GROUP
    
    chemgroups(262)%name="TMPX"
    chemgroups(262)%specs=>TMPX_GROUP
    
    chemgroups(263)%name="DDEP_TMPX"
    chemgroups(263)%specs=>DDEP_TMPX_GROUP
    
    chemgroups(264)%name="TRACER"
    chemgroups(264)%specs=>TRACER_GROUP
    
    chemgroups(265)%name="WDEP_OC"
    chemgroups(265)%specs=>WDEP_OC_GROUP
    
    chemgroups(266)%name="DDEP_OC"
    chemgroups(266)%specs=>DDEP_OC_GROUP
    
    chemgroups(267)%name="PPM25_FIRE"
    chemgroups(267)%specs=>PPM25_FIRE_GROUP
    
    chemgroups(268)%name="WDEP_PPM25_FIRE"
    chemgroups(268)%specs=>WDEP_PPM25_FIRE_GROUP
    
    chemgroups(269)%name="DDEP_PPM25_FIRE"
    chemgroups(269)%specs=>DDEP_PPM25_FIRE_GROUP
    
    chemgroups(270)%name="NVFFIREOC25"
    chemgroups(270)%specs=>NVFFIREOC25_GROUP
    
    chemgroups(271)%name="WDEP_NVFFIREOC25"
    chemgroups(271)%specs=>WDEP_NVFFIREOC25_GROUP
    
    chemgroups(272)%name="DDEP_NVFFIREOC25"
    chemgroups(272)%specs=>DDEP_NVFFIREOC25_GROUP
    
    chemgroups(273)%name="PPM10_FIRE"
    chemgroups(273)%specs=>PPM10_FIRE_GROUP
    
    chemgroups(274)%name="WDEP_PPM10_fire"
    chemgroups(274)%specs=>WDEP_PPM10_fire_GROUP
    
    chemgroups(275)%name="DDEP_PPM10_fire"
    chemgroups(275)%specs=>DDEP_PPM10_fire_GROUP
    
    chemgroups(276)%name="FFIREBC"
    chemgroups(276)%specs=>FFIREBC_GROUP
    
    chemgroups(277)%name="WDEP_FFIREBC"
    chemgroups(277)%specs=>WDEP_FFIREBC_GROUP
    
    chemgroups(278)%name="DDEP_FFIREBC"
    chemgroups(278)%specs=>DDEP_FFIREBC_GROUP
    
    chemgroups(279)%name="SS"
    chemgroups(279)%specs=>SS_GROUP
    
    chemgroups(280)%name="WDEP_SS"
    chemgroups(280)%specs=>WDEP_SS_GROUP
    
    chemgroups(281)%name="DDEP_SS"
    chemgroups(281)%specs=>DDEP_SS_GROUP
    
    chemgroups(282)%name="DUST"
    chemgroups(282)%specs=>DUST_GROUP
    
    chemgroups(283)%name="WDEP_DUST"
    chemgroups(283)%specs=>WDEP_DUST_GROUP
    
    chemgroups(284)%name="DDEP_DUST"
    chemgroups(284)%specs=>DDEP_DUST_GROUP
    
    chemgroups(285)%name="DUST_ANT_F"
    chemgroups(285)%specs=>DUST_ANT_F_GROUP
    
    chemgroups(286)%name="WDEP_DUST_ANT_F"
    chemgroups(286)%specs=>WDEP_DUST_ANT_F_GROUP
    
    chemgroups(287)%name="DDEP_DUST_ANT_F"
    chemgroups(287)%specs=>DDEP_DUST_ANT_F_GROUP
    
    chemgroups(288)%name="DUST_ANT_C"
    chemgroups(288)%specs=>DUST_ANT_C_GROUP
    
    chemgroups(289)%name="WDEP_DUST_ANT_C"
    chemgroups(289)%specs=>WDEP_DUST_ANT_C_GROUP
    
    chemgroups(290)%name="DDEP_DUST_ANT_C"
    chemgroups(290)%specs=>DDEP_DUST_ANT_C_GROUP
    
    chemgroups(291)%name="DUST_NAT_F"
    chemgroups(291)%specs=>DUST_NAT_F_GROUP
    
    chemgroups(292)%name="WDEP_DUST_NAT_F"
    chemgroups(292)%specs=>WDEP_DUST_NAT_F_GROUP
    
    chemgroups(293)%name="DDEP_DUST_NAT_F"
    chemgroups(293)%specs=>DDEP_DUST_NAT_F_GROUP
    
    chemgroups(294)%name="DUST_NAT_C"
    chemgroups(294)%specs=>DUST_NAT_C_GROUP
    
    chemgroups(295)%name="WDEP_DUST_NAT_C"
    chemgroups(295)%specs=>WDEP_DUST_NAT_C_GROUP
    
    chemgroups(296)%name="DDEP_DUST_NAT_C"
    chemgroups(296)%specs=>DDEP_DUST_NAT_C_GROUP
    
    chemgroups(297)%name="POLLEN"
    chemgroups(297)%specs=>POLLEN_GROUP
    
    chemgroups(298)%name="WDEP_POLLEN"
    chemgroups(298)%specs=>WDEP_POLLEN_GROUP
    
    chemgroups(299)%name="DDEP_POLLEN"
    chemgroups(299)%specs=>DDEP_POLLEN_GROUP
    
    chemgroups_factors(1)%name="CSTAR"
    chemgroups_factors(1)%species=>CSTAR_GROUP
    chemgroups_factors(1)%factors=>CSTAR_GROUP_FACTORS
    
    chemgroups_factors(2)%name="DELTAH"
    chemgroups_factors(2)%species=>DELTAH_GROUP
    chemgroups_factors(2)%factors=>DELTAH_GROUP_FACTORS
    
    chemgroups_maps(1)%name="EXTINC"
    chemgroups_maps(1)%species=>EXTINC_GROUP
    chemgroups_maps(1)%maps=>EXTINC_GROUP_MAPBACK
  
  end subroutine Init_ChemGroups

end module ChemGroups_mod
