! Generated by GenChem.py - DO NOT EDIT
! scheme(s)  CB6r2emep PM_WoodFfuelInert PM_Hodzic_CB6 Aqueous_EmChem16x Aero2017nx ShipNOx FFireInert SeaSalt DustExtended Ash BVOC_SQT_NV
module ChemRates_mod

  use AeroConstants_mod  ! => AERO%PM etc, ...
  use AeroFunctions_mod  ! => UptakeRates, ...
  use ChemDims_mod       ! => NSPEC_TOT, NCHEMRATES, ....
  use ChemFunctions_mod  ! => IUPAC_troe, RiemerN2O5, ....
  use ChemSpecs_mod      ! => PINALD, .... for FgasJ08
  use DefPhotolysis_mod  ! => IDNO2 etc.
  use ZchemData_mod      ! => rct
  
  implicit none
  private
  character(len=*),parameter, public :: CM_schemes_ChemRates = " CB6r2emep PM_WoodFfuelInert PM_Hodzic_CB6 Aqueous_EmChem16x Aero2017nx ShipNOx FFireInert SeaSalt DustExtended Ash BVOC_SQT_NV"
  
  
  public :: setChemRates
  public :: setPhotolUsed
  
  ! Photolysis rates
  integer, save, public, dimension(NPHOTOLRATES) :: photol_used

contains
  
  subroutine setPhotolUsed()
    photol_used = (/ &
        IDNO2  &
      , IDO3_O3P  &
      , IDO3_O1D  &
      , IDH2O2  &
      , IDNO3  &
      , IDN2O5  &
      , IDHONO  &
      , IDHNO3  &
      , IDHO2NO2  &
      , IDCH3O2H  &
      , IDHCHO_H  &
      , IDHCHO_H2  &
      , IDCH3CHO  &
      , IDMEK  &
      , IDACETON  &
      , IDCHOCHO  &
      , IDRCOCHO  &
    /)  
  end subroutine setPhotolUsed
  
  subroutine setChemRates()
    !integer, intent(in) :: debug_level
  
    rct(1,:) = (((5.68e-34*(TEMP/300.0)**-2.6))*O2)*M
    rct(2,:) = (1.4e-12*EXP(-1310.0*TINV))
    rct(3,:) = ((1e-31*(TEMP/300.0)**-1.6))*M
    rct(4,:) = (5.5e-12*EXP(188.0*TINV))
    rct(5,:) = ((1.3e-31*(TEMP/300.0)**-1.5)*M/(1.0+(1.3e-31*(TEMP/300.0)  &
             & **-1.5)*M/(2.3e-11*(TEMP/300.0)**0.24))  &
             & *0.6**(1.0/(1.0+LOG((1.3e-31*(TEMP/300.0)**-1.5)  &
             & *M/(2.3e-11*(TEMP/300.0)**0.24))**2)))
    rct(6,:) = (8e-12*EXP(-2060.0*TINV))
    rct(7,:) = ((2.23e-11*EXP(115.0*TINV)))*M
    rct(8,:) = ((2.14e-10))*H2O
    rct(9,:) = (1.7e-12*EXP(-940.0*TINV))
    rct(10,:) = (2.03e-16*(TEMP/300.0)**4.57*EXP(693.0*TINV))
    rct(11,:) = (2.4e-11*EXP(110.0*TINV))
    rct(12,:) = (2.7e-11*EXP(224.0*TINV))
    rct(13,:) = (6.2e-14*(TEMP/298.0)**2.6*EXP(945.0*TINV))
    rct(14,:) = ((6.9e-31*(TEMP/300.0)**-0.8)*M/(1.0+(6.9e-31*(TEMP/300.0)  &
              & **-0.8)*M/(2.6e-11))  &
              & *0.5**(1.0/(1.0+(LOG((6.9e-31*(TEMP/300.0)**-0.8)  &
              & *M/(2.6e-11))/1.13)**2)))
    rct(15,:) = (4.8e-11*EXP(250.0*TINV))
    rct(16,:) = (2.2e-13*EXP(600.0*TINV)+1.9e-33*EXP(980.0*TINV)*M)
    rct(17,:) = ((3.08e-34*EXP(2800.0*TINV)+2.66e-54*EXP(3180.0*TINV)*M))  &
              & *H2O
    rct(18,:) = (2.9e-12*EXP(-160.0*TINV))
    rct(19,:) = (1.4e-12*EXP(-2000.0*TINV))
    rct(20,:) = ((3.3e-39*EXP(530.0*TINV)))*O2
    rct(21,:) = (3.45e-12*EXP(270.0*TINV))
    rct(22,:) = (1.4e-13*EXP(-2470.0*TINV))
    rct(23,:) = (1.8e-11*EXP(110.0*TINV))
    rct(24,:) = (4.5e-14*EXP(-1260.0*TINV))
    rct(25,:) = (1.7e-11)
    rct(26,:) = (2e-11)
    rct(27,:) = (4e-12)
    rct(28,:) = (1e-17)
    rct(29,:) = (8.5e-13*EXP(-2450.0*TINV))
    rct(30,:) = ((3.6e-30*(TEMP/300.0)**-4.1)*M/(1.0+(3.6e-30*(TEMP/300.0)  &
              & **-4.1)*M/(1.9e-12*(TEMP/300.0)**0.2))  &
              & *0.35**(1.0/(1.0+(LOG((3.6e-30*(TEMP/300.0)**-4.1)  &
              & *M/(1.9e-12*(TEMP/300.0)**0.2))/1.33)**2)))
    rct(31,:) = ((0.0013*(TEMP/300.0)**-3.5*EXP(-11000.0*TINV))  &
              & *M/(1.0+(0.0013*(TEMP/300.0)**-3.5*EXP(-11000.0*TINV))  &
              & *M/(9.7e+14*(TEMP/300.0)**0.1*EXP(-11080.0*TINV)))  &
              & *0.35**(1.0/(1.0+(LOG((0.0013*(TEMP/300.0)  &
              & **-3.5*EXP(-11000.0*TINV))*M/(9.7e+14*(TEMP/300.0)  &
              & **0.1*EXP(-11080.0*TINV)))/1.33)**2)))
    rct(32,:) = ((1e-22))*H2O
    rct(33,:) = ((7.4e-31*(TEMP/300.0)**-2.4)*M/(1.0+(7.4e-31*(TEMP/300.0)  &
              & **-2.4)*M/(3.3e-11*(TEMP/300.0)**-0.3))  &
              & *0.81**(1.0/(1.0+(LOG((7.4e-31*(TEMP/300.0)**-2.4)  &
              & *M/(3.3e-11*(TEMP/300.0)**-0.3))/0.87)**2)))
    rct(34,:) = ((5e-40))*H2O
    rct(35,:) = (1e-20)
    rct(36,:) = (2.5e-12*EXP(260.0*TINV))
    rct(37,:) = ((1.8e-30*(TEMP/300.0)**-3.0)*M/(1.0+(1.8e-30*(TEMP/300.0)  &
              & **-3.0)*M/(2.8e-11))  &
              & *0.6**(1.0/(1.0+LOG((1.8e-30*(TEMP/300.0)**-3.0)  &
              & *M/(2.8e-11))**2)))
    rct(38,:) = ((2.4e-14*EXP(460.0*TINV))+(6.5e-34*EXP(1335.0*TINV))  &
              & *M/(1.0+(6.5e-34*EXP(1335.0*TINV))  &
              & *M/(2.7e-17*EXP(2199.0*TINV))))
    rct(39,:) = ((1.8e-31*(TEMP/300.0)**-3.2)*M/(1.0+(1.8e-31*(TEMP/300.0)  &
              & **-3.2)*M/(4.7e-12))  &
              & *0.6**(1.0/(1.0+LOG((1.8e-31*(TEMP/300.0)**-3.2)  &
              & *M/(4.7e-12))**2)))
    rct(40,:) = ((4.1e-05*EXP(-10650.0*TINV))  &
              & *M/(1.0+(4.1e-05*EXP(-10650.0*TINV))  &
              & *M/(4.8e+15*EXP(-11170.0*TINV)))  &
              & *0.6**(1.0/(1.0+LOG((4.1e-05*EXP(-10650.0*TINV))  &
              & *M/(4.8e+15*EXP(-11170.0*TINV)))**2)))
    rct(41,:) = (3.2e-13*EXP(690.0*TINV))
    rct(42,:) = (7.5e-12*EXP(290.0*TINV))
    rct(43,:) = ((2.7e-28*(TEMP/300.0)**-7.1)*M/(1.0+(2.7e-28*(TEMP/300.0)  &
              & **-7.1)*M/(1.2e-11*(TEMP/300.0)**-0.9))  &
              & *0.3**(1.0/(1.0+(LOG((2.7e-28*(TEMP/300.0)**-7.1)  &
              & *M/(1.2e-11*(TEMP/300.0)**-0.9))/1.41)**2)))
    rct(44,:) = ((0.0049*EXP(-12100.0*TINV))  &
              & *M/(1.0+(0.0049*EXP(-12100.0*TINV))  &
              & *M/(5.4e+16*EXP(-13830.0*TINV)))  &
              & *0.3**(1.0/(1.0+(LOG((0.0049*EXP(-12100.0*TINV))  &
              & *M/(5.4e+16*EXP(-13830.0*TINV)))/1.41)**2)))
    rct(45,:) = (5.2e-13*EXP(980.0*TINV))
    rct(46,:) = (8.9e-13*EXP(800.0*TINV))
    rct(47,:) = (2.9e-12*EXP(500.0*TINV))
    rct(48,:) = (6.7e-12*EXP(340.0*TINV))
    rct(49,:) = (3.2e-12*EXP(500.0*TINV))
    rct(50,:) = (2.4e-12*EXP(360.0*TINV))
    rct(51,:) = (4.8e-13*EXP(800.0*TINV))
    rct(52,:) = (6.5e-14*EXP(500.0*TINV))
    rct(53,:) = (2.3e-12*EXP(360.0*TINV))
    rct(54,:) = (3.8e-13*EXP(780.0*TINV))
    rct(55,:) = (2e-12*EXP(500.0*TINV))
    rct(56,:) = (2.7e-12*EXP(360.0*TINV))
    rct(57,:) = (6.8e-13*EXP(800.0*TINV))
    rct(58,:) = (5.3e-12*EXP(190.0*TINV))
    rct(59,:) = (2e-12)
    rct(60,:) = (4.5e-13)
    rct(61,:) = (4e-14*EXP(850.0*TINV))
    rct(62,:) = (5.4e-12*EXP(135.0*TINV))
    rct(63,:) = (3.4e-11*EXP(-1600.0*TINV))
    rct(64,:) = (5.5e-16)
    rct(65,:) = (9.7e-15*EXP(625.0*TINV))
    rct(66,:) = (2.4e+12*EXP(-7000.0*TINV))
    rct(67,:) = (5.6e-12)
    rct(68,:) = (5.6e-15*EXP(2300.0*TINV))
    rct(69,:) = (1.8e-11*EXP(-1100.0*TINV))
    rct(70,:) = (4.7e-12*EXP(345.0*TINV))
    rct(71,:) = (1.4e-12*EXP(-1860.0*TINV))
    rct(72,:) = (1.3e-11*EXP(-870.0*TINV))
    rct(73,:) = (4.9e-12*EXP(405.0*TINV))
    rct(74,:) = (6.3e-15)
    rct(75,:) = (8e-12)
    rct(76,:) = (3.1e-12*EXP(340.0*TINV))
    rct(77,:) = (1.9e-12*EXP(575.0*TINV))
    rct(78,:) = (7.7e-12*EXP(-2100.0*TINV))
    rct(79,:) = (1.44e-13+3.43e-33*M)
    rct(80,:) = (1.85e-12*EXP(-1690.0*TINV))
    rct(81,:) = (6.9e-12*EXP(-1000.0*TINV))
    rct(82,:) = (2.85e-12*EXP(-345.0*TINV))
    rct(83,:) = (3e-12*EXP(20.0*TINV))
    rct(84,:) = (1.41e-12*EXP(-620.6*TINV))
    rct(85,:) = (7.6e-12*EXP(-585.0*TINV))
    rct(86,:) = (8.1e-13)
    rct(87,:) = (5.7e+12*EXP(-5780.0*TINV))
    rct(88,:) = ((1.5e-14*EXP(-200.0*TINV)))*O2
    rct(89,:) = (8.6e-12*EXP(400.0*TINV))
    rct(90,:) = ((5e-30*(TEMP/300.0)**-1.5)*M/(1.0+(5e-30*(TEMP/300.0)  &
              & **-1.5)*M/(1e-12))*0.37**(1.0/(1.0+(LOG((5e-30*(TEMP/300.0)  &
              & **-1.5)*M/(1e-12))/1.3)**2)))
    rct(91,:) = (1.04e-11*EXP(-792.0*TINV))
    rct(92,:) = ((8.6e-29*(TEMP/300.0)**-3.1)*M/(1.0+(8.6e-29*(TEMP/300.0)  &
              & **-3.1)*M/(9e-12*(TEMP/300.0)**-0.85))  &
              & *0.48**(1.0/(1.0+(LOG((8.6e-29*(TEMP/300.0)**-3.1)  &
              & *M/(9e-12*(TEMP/300.0)**-0.85))/1.15)**2)))
    rct(93,:) = (9.1e-15*EXP(-2580.0*TINV))
    rct(94,:) = (3.3e-12*EXP(-2880.0*TINV))
    rct(95,:) = (1e-11*EXP(-280.0*TINV))
    rct(96,:) = ((8e-27*(TEMP/300.0)**-3.5)*M/(1.0+(8e-27*(TEMP/300.0)  &
              & **-3.5)*M/(3e-11*300.0/TEMP))  &
              & *0.5**(1.0/(1.0+(LOG((8e-27*(TEMP/300.0)**-3.5)  &
              & *M/(3e-11*300.0/TEMP))/1.13)**2)))
    rct(97,:) = (5.5e-15*EXP(-1880.0*TINV))
    rct(98,:) = (4.6e-13*EXP(-1155.0*TINV))
    rct(99,:) = (2.3e-11)
    rct(100,:) = (1.05e-11*EXP(519.0*TINV))
    rct(101,:) = (4.7e-15*EXP(-1013.0*TINV))
    rct(102,:) = (3.7e-13)
    rct(103,:) = (2.7e-11*EXP(390.0*TINV))
    rct(104,:) = (3e-11)
    rct(105,:) = (2.39e-12*EXP(365.0*TINV))
    rct(106,:) = (7.43e-13*EXP(700.0*TINV))
    rct(107,:) = (3300000000.0*EXP(-8300.0*TINV))
    rct(108,:) = (1.03e-14*EXP(-1995.0*TINV))
    rct(109,:) = (3.03e-12*EXP(-448.0*TINV))
    rct(110,:) = (5.58e-12*EXP(511.0*TINV))
    rct(111,:) = (3.88e-15*EXP(-1770.0*TINV))
    rct(112,:) = (4.1e-12*EXP(-1860.0*TINV))
    rct(113,:) = (2.23e-11*EXP(372.0*TINV))
    rct(114,:) = (6e-12*EXP(-1860.0*TINV))
    rct(115,:) = (5.78e-11*EXP(-400.0*TINV))
    rct(116,:) = (3.1e-11)
    rct(117,:) = (3.6e-11)
    rct(118,:) = (1.5e-11*EXP(449.0*TINV))
    rct(119,:) = (1.2e-15*EXP(-821.0*TINV))
    rct(120,:) = (3.7e-12*EXP(175.0*TINV))
    rct(121,:) = (2.3e-12*EXP(-190.0*TINV))
    rct(122,:) = (1.9e-13*EXP(1300.0*TINV))
    rct(123,:) = (1.8e-12*EXP(340.0*TINV))
    rct(124,:) = (1.85e-11)
    rct(125,:) = (1.7e-12*EXP(950.0*TINV))
    rct(126,:) = (1.4e-11)
    rct(127,:) = (2.1e-12)
    rct(128,:) = (5.5e-12)
    rct(129,:) = (1.53e-12)
    rct(130,:) = (3.8e-12)
    rct(131,:) = (9e-11)
    rct(132,:) = (1.08e-16*EXP(-500.0*TINV))
    rct(133,:) = (3e-12)
    rct(134,:) = (4.4e-11)
    rct(135,:) = (5.4e-17*EXP(-500.0*TINV))
    rct(136,:) = (5e-11)
    rct(137,:) = (1.7e-10)
    rct(138,:) = (1e-11)
    rct(139,:) = (2.3e-05)
    rct(140,:) = EC_AGEING_RATE()
    rct(141,:) = HYDROLYSISN2O5()
    rct(142,:) = UPTAKERATE(CNO3,  &
               & GAM=0.001,  &
               & S=S_M2M3(AERO%PM,  &
               & :))
    rct(143,:) = UPTAKERATE(CHNO3,  &
               & GAM=0.1,  &
               & S=S_M2M3(AERO%DU_C,  &
               & :))
    rct(144,:) = UPTAKERATE(CHNO3,  &
               & GAM=0.01,  &
               & S=S_M2M3(AERO%SS_C,  &
               & :))
    rct(145,:) = UPTAKERATE(CHO2,  &
               & GAM=0.2,  &
               & S=S_M2M3(AERO%PM,  &
               & :))
    rct(146,:) = (((3.2e-30*M*(TEMP/300)**(-4.5))*(3.0e-11))  &
               & *(10**(LOG10(0.41)/(1+(LOG10(((3.2e-30*M*(TEMP/300)**(-4.5))  &
               & /(3.0e-11)))/(0.75-1.27*(LOG10(0.41))))**2)))  &
               & /((3.2e-30*M*(TEMP/300)**(-4.5))+(3.0e-11)))
  
  end subroutine setChemRates

end module ChemRates_mod
