character(len=14), save, dimension(NEMIS_Specs), public :: EMIS_Specs = (/ &
  "NO            " &
, "NO2           " &
, "SO2           " &
, "SO4           " &
, "CO            " &
, "NH3           " &
, "CH4           " &
, "PRPA          " &
, "ETHY          " &
, "BENZ          " &
, "FACD          " &
, "AACD          " &
, "ACET          " &
, "KET           " &
, "GLY           " &
, "MGLY          " &
, "FORM          " &
, "ALD2          " &
, "ALDX          " &
, "ETOH          " &
, "MEOH          " &
, "ETHA          " &
, "PAR           " &
, "ETH           " &
, "OLE           " &
, "IOLE          " &
, "C5H8          " &
, "TERP          " &
, "TOL           " &
, "XYL           " &
, "POM_F_FFUEL   " &
, "POM_C_FFUEL   " &
, "EC_F_FFUEL_NEW" &
, "EC_F_FFUEL_AGE" &
, "EC_C_FFUEL    " &
, "POM_F_WOOD    " &
, "EC_F_WOOD_NEW " &
, "EC_F_WOOD_AGE " &
, "REMPPM25      " &
, "REMPPM_C      " &
, "PSO4F         " &
, "PSO4C         " &
, "SHIPNOX       " &
, "FFIRE_OM      " &
, "FFIRE_BC      " &
, "FFIRE_REMPPM25" &
, "SEASALT_F     " &
, "SEASALT_C     " &
, "DUST_WB_F     " &
, "DUST_WB_C     " &
, "DUST_ROAD_F   " &
, "DUST_ROAD_C   " &
, "DUST_SAH_F    " &
, "DUST_SAH_C    " &
, "ASH_F         " &
, "ASH_C         " &
/)
